### ISSUE TITLE
Linger process

### ISSUE THREAD

**Issue by NedFlanders2** [sandboxie-plus/Sandboxie#2751] opened 2023-03-15 08:46 UTC
### Describe what you noticed and did

I have Linger process set but the mbam process won't terminate naturally this only just started happening recently, i can terminate from the context menu in the tray bar manually and it will work but its not doing it as it normally would function when quitting the web browser...

![mb](https://user-images.githubusercontent.com/74814763/225253367-daaffb89-758c-4b5d-946e-0883ae9e8981.png)

![mb2](https://user-images.githubusercontent.com/74814763/225253873-070f26c9-cb84-46af-86ff-79016e2cc6b6.png)

I never realized that the application was so far behind compared to the GitHub releases so i will also try and update to the newest version from here instead of doing it through the app itself and see if it changes anything. 

I will also come back and do a trace upload at a later time if need be i just don't have the time atm. 

### How often did you encounter it so far?

Frequency is 100% so everytime i shutdown my browser the process lingers

### Affected program

Malwarebytes  4.5.24

### Download link

...

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

The process to terminate when the web browser is closed. 

### What is your Windows edition and version?

Windows 10 21H2 build: 19044,2604

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Malwarebytes

### What version of Sandboxie are you running?

Sandboxie Plus 1.5.3

### Is it a new installation of Sandboxie?

No.

### Is it a regression?

since around 1.5.2 or 3 roughly

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Never tried but i expect the same results.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=Edge_Fix
Template=RpcPortBindings
Template=7zipShellEx
Template=RTSS
Template=WindowsLive
Template=OfficeLicensing
TemplateReject=BitDefenderInternetSecurity
TemplateReject=WindowsRasMan
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EnableObjectFiltering=n
ForceDisableSeconds=600

[UserSettings_04C20136]

SbieCtrl_UserName=ben
SbieCtrl_NextUpdateCheck=1628290382
SbieCtrl_WindowCoords=435,229,903,632
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_AutoApplySettings=y
SbieCtrl_HideWindowNotify=n
SbieCtrl_TerminateNotify=y
SbieCtrl_TerminateWarn=y
SbieCtrl_ExplorerNotify=y
SbieCtrl_ExplorerWarn=y
SbieCtrl_EditConfNotify=y
SbieCtrl_ReloadConfNotify=y
SbieCtrl_ProcSettingsNotify=y
SbieCtrl_SettingChangeNotify=y
SbieCtrl_ShortcutNotify=y
SbieCtrl_UpdateCheckNotify=y
SbieCtrl_ShouldDeleteNotify=y
SbieCtrl_ShowWelcome=y
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y
SbieCtrl_BoxExpandedView=,
BoxDisplayOrder=DD1,DD2

[Firefox]

ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=Firefox_Session_DirectAccess
Template=Firefox_Profile_DirectAccess
Template=Firefox_Bookmarks_DirectAccess
Template=OpenSmartCard
Template=OpenBluetooth
Template=Firefox_Cookies_DirectAccess
Template=Firefox_Force
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
RecoverFolder=D:\Download
RecoverFolder=%Desktop%
RecoverFolder=%Favorites%
RecoverFolder=%Personal%
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
BorderColor=#ff0000,ttl,6
Enabled=y
BoxNameTitle=n
ForceFolder=C:\Program Files\Mozilla Firefox
LingerProcess=MbamBgNativeMsg.exe
LingerProcess=firefox.exe
CopyLimitKb=1024000
AutoDelete=y
ProcessGroup=<StartRunAccess>,MbamBgNativeMsg.exe,firefox.exe
ProcessGroup=<InternetAccess>,firefox.exe
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
OpenWinClass=#
RpcMgmtSetComTimeout=n
ClosePrintSpooler=y
ClosedIpcPath=!<StartRunAccess>,*
SandboxieLogon=y
DropAdminRights=y

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
```

**Comment by mysteriously** [comment] 2023-03-15 13:41
I have the same issue with Edge for many months. If I clear sandbox it helps... for a few weeks

**Comment by offhub** [comment] 2023-03-15 13:47
Can you try with the following settings:

Remove:
```
LingerProcess=MbamBgNativeMsg.exe
LingerProcess=firefox.exe
```

Add:
```
LeaderProcess=firefox.exe
```

**Comment by NedFlanders2** [comment] 2023-03-16 03:20
I tried your suggestion to no avail. This is an issue that only started occurring very recently like i only noticed it like the last few weeks, up until now there was no issue with the process lingering and i initially never had any linger parameters set either and have been using the same sandbox for a few years now.

**Comment by offhub** [comment] 2023-03-16 18:37
Can you try with the following setting.

`Sandbox Options` > `Advanced Options` > `Compatibility` > `Allow use of nested job objects (works on Windows 8 and later)`

```
AllowBoxedJobs=y
```

**Comment by NedFlanders2** [comment] 2023-03-17 21:21
That did the trick setting `LingerProcess=MbamBgNativeMsg.exe` with `AllowBoxedJobs=y` 

Thanks

**Comment by DavidXanatos** [comment] 2023-03-26 20:00
since we have a workaround and it seams to reproduce this issue malware bytes is required i opt for closing this issue

**Closed by DavidXanatos** 2023-03-26 20:00 UTC
Labels: Confirmation pending, Workaround
