### ISSUE TITLE
SandMan 0.9.0a UserSettings bug

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#1054] opened 2021-07-29 19:33 UTC
-**Bug description**
Does not use existing BoxDisplayOrder for groups ( from `UserSettings_#` section )
Creating a new group will create a new `[UserSettings]` in the ini with BoxDisplayOrder along with box specific settings

-**related suggestion**
For groups instead of "`Box groupe`" to have no shown status (empty/null)

OS Windows 7 Ultimate 64-bit SP1 x64

**Comment by isaak654** [comment] 2021-07-30 13:51
I'm not able to reproduce the duplicate [UserSettings] on a clean Windows 7 SP1 x86 with 0.9.0a, so I would need exact steps.

**Comment by RandomGOTI** [comment] 2021-07-30 18:54
To reformulate
`[UserSettings]` section being created by 0.9.0a it's the bug not having it duplicated
0.8.9c creates the section as `[UserSettings_XXXXXXXX]` hence it doesn't break classic or ini's created prior to 0.9.0a

Stepts:

1. Fresh (no sandboxie.ini) install 0.9.0a
2. Start sandman
3. create 2 groups

<details>

<summary> How the section looks with a clean default ini creating only 2 groups in 0.9.0a </summary>

```
[UserSettings]

BoxDisplayOrder=group1(),group2()
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
```
</details>

Add `Enabled=y` and you have a box

`[UserSettings_Default]`
`[UserSettings_Portable]`
Are also ignored by both 0.9.0a and 0.8.9c
[https://sandboxie-website-archive.github.io/www.sandboxie.com/SandboxieIni.html](url)

**Comment by isaak654** [comment] 2021-08-01 11:31
@DavidXanatos I think this needs further investigation too.

**Comment by offhub** [comment] 2021-08-04 21:56
Installed 0.9.1 over 0.8.9.

-App Templates editing feature is broken. (empty)

-When you add a ProcessGroup to the box, it adds all the ProcessGroups defined in the configuration to the box.

**Comment by DavidXanatos** [comment] 2021-08-07 18:35
> -When you add a ProcessGroup to the box, it adds all the ProcessGroups defined in the configuration to the box.
>

??? 
please explain

**Comment by offhub** [comment] 2021-08-07 20:26
1. Add a new Program Group to the box from UI. (with attached config. **PW**: 20210807)
[TESTESTBox.zip](https://github.com/sandboxie-plus/Sandboxie/files/6949752/TESTESTBox.zip)
![sbiep02](https://user-images.githubusercontent.com/6871698/128613052-0bcc4507-9b84-4280-a0b8-91e7cd227707.png)

**Comment by DavidXanatos** [comment] 2021-08-08 07:16
I see, will be fixed in the next build

**Comment by isaak654** [comment] 2021-08-08 09:28
@RandomGOTI Just for the record, also your issue explained in the third post was fixed.

**Closed** 2021-08-08 17:58 UTC
Labels: bug, fixed in next build, compatibility regression, Issue reproduced
