### ISSUE TITLE
PDFs Not Working in Brave Web Browser

### ISSUE THREAD

**Issue by qazero** [sandboxie-plus/Sandboxie#817] opened 2021-04-27 19:59 UTC
**Describe the bug**
Unable to open PDFs in the latest version of Brave web browser inside of Sandboxie. I've been running Brave sandboxed inside of Sandboxie for years without any problem. However, in one of the recent Brave updates, PDFs no longer open inside of sandboxed Brave but they work fine without using the Sandboxie sandbox for Brave.

**To Reproduce**
1. Set Brave as your default web browser and PDF viewer in Windows
2. Configure Sandboxie to force Brave to run inside the sandbox
3. Double click on any PDF file on your computer (if your configuration is correct per above, Brave will open sandboxed inside Sandboxie)
4. The PDF doesn't display, it says "Couldn't load plugin" per the screenshot below

![image](https://user-images.githubusercontent.com/10906010/116304218-9183d580-a75f-11eb-87c5-94050789878d.png)

**Expected behavior**
The PDF should be displayed in Brave running sandboxed with Sandboxie. I tried opening the PDF without running sandboxed and it displays fine. Interestingly, PDFs work fine in Chrome running sandboxed with Sandboxie so I'm not sure what the issue is with Brave.

**Screenshots**
See screenshot above.

**System details and installed software (please provide the following information):**
Sandboxie: 5.49.7 (64 bit)
Brave | 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)
-- | --
Revision | 5bc145d831c180d9ff94f29a0d7a2e1cbd30ef36-refs/branch-heads/4430@{#1311}
OS | Windows 10 OS Version 2009 (Build 19042.928)

**Sandboxie configuration**
<details>
 
<summary>My initial sandboxie.ini settings</summary>
 
```

[GlobalSettings]
Template=RpcPortBindings
Template=Windows10CoreUI
Template=FireFix_for_Win7
Template=Kaspersky
Template=InternetDownloadManager
Template=AdobeDistiller
Template=Avira_Antivirus
Template=KeyScrambler
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
ActivationPrompt=n
ClosedFilePath=*\Windows.System.Launcher.dll
SpecialImage=firefox,brave.exe

.....

[UserSettings_08DA01C0]
SbieCtrl_UserName=user
SbieCtrl_NextUpdateCheck=1619633987
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_WindowCoords=505,612,1553,884
SbieCtrl_ActiveView=40021
SbieCtrl_AutoApplySettings=y
SbieCtrl_SettingChangeNotify=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_HideMessage=1320,[19748]
SbieCtrl_HideMessage=1319,[19748]
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_BoxExpandedView=DefaultBox,Test

.....

ConfigLevel=8
AutoRecover=y
BlockNetworkFiles=y
Template=SkipHook
Template=FileCopy
Template=Firefox_Force
Template=Chrome_Force
Template=IExplore_Favorites_RecoverFolder
Template=IExplore_Force
Template=qWave
Template=WindowsFontCache
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%Desktop%
BorderColor=#00FFFF,off
Enabled=y
BoxNameTitle=-
AutoDelete=y
NeverDelete=n
ForceProcess=brave.exe
ForceProcess=microsoftedge.exe

.....

```

</details>

**Comment by isaak654** [comment] 2021-04-29 14:48
This post won't fix your issue, but in order to improve your configuration, I would suggest to remove these lines from GlobalSettings:

```
Template=Windows10CoreUI
Template=FireFix_for_Win7
ActivationPrompt=n
SpecialImage=firefox,brave.exe
ClosedFilePath=*\Windows.System.Launcher.dll
```

The first three lines are outdated, the fourth one is as useless as wrong (basically it says that brave is a firefox fork - this mistake was made by David months ago and then fixed later), while the fifth one is related to an old workaround that's no longer needed.

**Comment by qazero** [comment] 2021-05-21 20:06
Any update regarding this?

**Comment by isaak654** [comment] 2021-06-05 18:12
Release v0.7.5 / 5.49.8 is out, please confirm whether the issue is fixed or not.

**Comment by NewKidOnTheBlock** [comment] 2021-06-08 16:20
SB 5.49.8 + Brave Portable 1.25.68-74
Bug confirmed.
This error message appears for all PDFs, not just local ones.
If I try to open a random .pdf in sandboxed Brave, it throws the "Couldn't load plugin" message.

**Comment by isaak654** [comment] 2021-06-09 17:26
I'm able to reproduce it right now in Plus 0.7.5.

**Comment by isaak654** [comment] 2021-06-14 12:54
Somebody confirmed that it can be reproduced with Sandboxie Classic 5.50.1 (issue #903)

**Comment by qazero** [comment] 2021-06-14 16:04
Why was this closed? Is there a fix planned?

**Comment by isaak654** [comment] 2021-06-14 16:23
> 
> 
> Why was this closed? Is there a fix planned?

This is still open, I think you're making confusion with another closed issue.

**Comment by qazero** [comment] 2021-06-14 16:50
Thank you :)

**Closed** 2021-07-06 06:50 UTC
Labels: Chromium 90+ compatibility issue, Issue reproduced, fixed in next build
