### ISSUE TITLE
Can't open second instance of Vivaldi in the same sandbox

### ISSUE THREAD

**Issue by NotepadPlusUser** [sandboxie-plus/Sandboxie#1835] opened 2022-05-02 01:47 UTC
### What happened?

I open Vivaldi in the default sandbox using the command   
Sandboxie /Box:LoginBox Vivaldi
I run this command again, and nothing happens.  

When I run the simple command 'Vivaldi' twice, however, I do get the expected two instances.

If I replace 'Vivaldi' with either 'Firefox' or 'MSEdge' in the command, I also get the expected two instances.

### Download link

Not relevant

### To Reproduce

As described above.

### Expected behavior

This should open a second instance in the same sandbox.  

### What is your Windows edition and version?

Windows 10 Pro 21H2 V10.0.19044.1682

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

ESET Internet Security

### What version of Sandboxie are you running?

Sandboxie-Plus-x64-v1.0.20

### Is it a regression?

For the last three months or so.  There have been upgrades of both Sandboxie and Vivaldi.  Up until a week ago, this behaviour only occurred sometimes, now it occurs regularly all the time.

### List of affected browsers

Only Vivaldi

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No --- only that I have used GPEdit to prevent Windows updating itself without my permission.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=Microsoft_MSMQ
Template=RpcPortBindings
Template=VirtuaWin
Template=NOD32
Template=7zipShellEx
Template=LogitechSetPoint
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun
Template=RoboForm
ActivationPrompt=n
FileRootPath=D:\Sandbox\BillPender\%SANDBOX%
ForceDisableSeconds=600
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
NetworkEnableWFP=n
EnableObjectFiltering=n
EnableWin32kHooks=y
StartRunAlertDenied=y
NotifyStartRunAccessDenied=y
AlertProcess="C:\Program Files\The Bat!\thebat64.exe"

[DefaultBox]

ConfigLevel=9
AutoRecover=n
BlockNetworkFiles=y
Template=FileCopy
Template=Vivaldi_Force
Template=Firefox_Force
Template=SkipHook
Template=IExplore_Favorites_RecoverFolder
Template=IExplore_Force
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,on,6
Enabled=y
CopyLimitKb=838330
NotifyStartRunAccessDenied=y
ProcessGroup=<ChromePrograms>,vivaldi.exe,opera.exe,msedge.exe,Maxthon.exe,iron.exe,dragon.exe,chrome.exe,browser.exe,brave.exe
ProcessGroup=<FirefoxPrograms>,waterfox.exe,seamonkey.exe,palemoon.exe,firefox.exe
ProcessGroup=<StartRunAccess>,theBat64.exe
ClosedIpcPath=<StartRunAccess>,*
ForceProcess=IExplore
ForceProcess=msedge.exe
ForceProcess=firefox.exe
ForceProcess=vivaldi.exe
BoxNameTitle=n
BlockNetParam=y
DropAdminRights=n
FakeAdminRights=y
ClosePrintSpooler=n
OpenPrintSpooler=n
AllowSpoolerPrintToFile=n
PromptForFileMigration=y
CopyLimitSilent=n
NeverDelete=n
AutoDelete=n
AllowRawDiskRead=n
NotifyDirectDiskAccess=n

[UserSettings_2D380422]

SbieCtrl_UserName=billpender
SbieCtrl_NextUpdateCheck=1619406536
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_AutoApplySettings=n
SbieCtrl_WindowCoords=2,0,1024,633
SbieCtrl_ActiveView=40021
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_EnableLogonStart=y
SbieCtrl_EnableAutoStart=n
SbieCtrl_AddDesktopIcon=y
SbieCtrl_AddQuickLaunchIcon=y
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=y
SbieCtrl_BoxExpandedView=BodgieBox,DefaultBox,TrueBox
SbieCtrl_HideMessage=1301,firefox.exe
SbieCtrl_HideMessage=1301, vivaldi.exe
SbieCtrl_AutoStartAgent=SandMan.exe
BoxCollapsedView=DefaultBox

[BodgieBox]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=FileCopy
Template=SkipHook
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#8000ff,on,6
BoxNameTitle=n
CopyLimitKb=306178
ProcessGroup=<ChromePrograms>,vivaldi.exe,opera.exe,msedge.exe,Maxthon.exe,iron.exe,dragon.exe,chrome.exe,browser.exe,brave.exe
ProcessGroup=<FirefoxPrograms>,waterfox.exe,seamonkey.exe,palemoon.exe,firefox.exe
ProcessGroup=<StartRunAccess>,theBat64.exe
ClosedIpcPath=<StartRunAccess>,*
BlockNetParam=y
DropAdminRights=n
FakeAdminRights=n
ClosePrintSpooler=n
OpenPrintSpooler=n
AllowSpoolerPrintToFile=n
PromptForFileMigration=y
CopyLimitSilent=n
NeverDelete=n
AutoDelete=n
AllowRawDiskRead=n
NotifyDirectDiskAccess=n

[OrderBox]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=FileCopy
Template=SkipHook
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#23ad00,on,6
BoxNameTitle=n
CopyLimitKb=306178
ProcessGroup=<ChromePrograms>,vivaldi.exe,opera.exe,msedge.exe,Maxthon.exe,iron.exe,dragon.exe,chrome.exe,browser.exe,brave.exe
ProcessGroup=<FirefoxPrograms>,waterfox.exe,seamonkey.exe,palemoon.exe,firefox.exe
ProcessGroup=<StartRunAccess>,theBat64.exe
ClosedIpcPath=<StartRunAccess>,*
BlockNetParam=y
DropAdminRights=n
FakeAdminRights=n
ClosePrintSpooler=n
OpenPrintSpooler=n
AllowSpoolerPrintToFile=n
PromptForFileMigration=y
CopyLimitSilent=n
NeverDelete=n
AutoDelete=n
AllowRawDiskRead=n
NotifyDirectDiskAccess=n

[TrueBox]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=FileCopy
Template=SkipHook
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#ff8000,on,6
BoxNameTitle=n
CopyLimitKb=306178
ProcessGroup=<ChromePrograms>,vivaldi.exe,opera.exe,msedge.exe,Maxthon.exe,iron.exe,dragon.exe,chrome.exe,browser.exe,brave.exe
ProcessGroup=<FirefoxPrograms>,waterfox.exe,seamonkey.exe,palemoon.exe,firefox.exe
ProcessGroup=<StartRunAccess>,theBat64.exe
ClosedIpcPath=<StartRunAccess>,*
BlockNetParam=y
DropAdminRights=n
FakeAdminRights=n
ClosePrintSpooler=n
OpenPrintSpooler=n
AllowSpoolerPrintToFile=n
PromptForFileMigration=y
CopyLimitSilent=n
NeverDelete=n
AutoDelete=n
AllowRawDiskRead=n
NotifyDirectDiskAccess=n

[UserSettings]

SbieCtrl_AutoStartAgent=SandMan.exe
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
SbieCtrl_HideMessage=1301, vivaldi.exe
SbieCtrl_EnableAutoStart=y

[LoginBox]

Enabled=y
ConfigLevel=9
Template=AutoRecoverIgnore
Template=Firefox_Phishing_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=SkipHook
Template=FileCopy
RecoverFolder=%Desktop%
RecoverFolder=%Favorites%
RecoverFolder=%Personal%
BorderColor=#00ffaa,on,6
BoxNameTitle=n
CopyLimitKb=306178
ProcessGroup=<StartRunAccess>,theBat64.exe
ProcessGroup=<FirefoxPrograms>,waterfox.exe,seamonkey.exe,palemoon.exe,firefox.exe
ProcessGroup=<ChromePrograms>,vivaldi.exe,opera.exe,msedge.exe,Maxthon.exe,iron.exe,dragon.exe,chrome.exe,browser.exe,brave.exe
ClosedIpcPath=<StartRunAccess>,*
DropAdminRights=n
FakeAdminRights=n
```

**Comment by NotepadPlusUser** [comment] 2022-05-16 08:51
Several updates have come in since my post, and the behaviour is slightly worse: 
Sandboxie-Plus—>1.0.22
Vivaldi—> 5.2.2623.46
Windows—>10.0.19044.1706 (May update)
PC and Notebook (both 64-bit) display the same problems. 

Contrary to my earlier post, the final detail below affects Firefox and IE:
 - - - - - - - -

THE PRESENT SITUATION:  I have five sandboxes, and five browsers that are forced to open in DefaultBox. Perform these steps in order, being careful to close windows or leave them open.

 * "sandboxie /dfp vivaldi" correctly opens Vivaldi unsandboxed.  Close it again.
  — "sandboxie /Box:DefaultBox vivaldi" correctly opens Vivaldi in DefaultBox.  Close it again.
  — "vivaldi" correctly opens Vivaldi in DefaultBox.  Close it again.

 * Now use "vivaldi" to open an instance of Vivaldi in DefaultBox, and leave it open.
  — "sandboxie /dfp vivaldi" now opens a second instance of Vivaldi in DefaultBox — not unsandboxed — and repeats of this command open further instances in DefaultBox.  Leave them all open.
  — "sandboxie /Box:DefaultBox vivaldi" and "vivaldi", however, do not open further instances, which they used to do.

 * Leave all these instances of Vivaldi in DefaultBox open. 
  — "sandboxie /Box:LoginBox vivaldi" opens a new instance in LoginBox.  Leave everything open.
  — "sandboxie /dfp vivaldi" now opens a second instance of Vivaldi in LoginBox (presumably going back to the most recently opened instance of Vivaldi), and repeats of this command open further instances in LoginBox.  Leave everything open.
  — "sandboxie /Box:LoginBox vivaldi", however, does not open any further instance.
 
 * Disabling forcing makes the predictable changes to these details.
 - - - - - - - -

 AN EXPERIMENT: Eventually I went to Sandboxie-Plus UI —> DefaultBox RightClick —> Sandbox Options —> Forced Programs, and removed all five browsers, so that there were no forced programs left.  

 * "Vivaldi" and "sandboxie /dfp vivaldi" now correctly open unsandboxed instances.  Close them again.
  — Then use "sandboxie /Box:DefaultBox vivaldi" to open Vivaldi in DefaultBox.  
  — With this window still open, the commands "Vivaldi" and "sandboxie /dfp vivaldi" now open Vivaldi in DefaultBox.

 * ASTONISHINGLY, I found that the two browsers Firefox and IE opened in DefaultBox with the bare commands "Firefox" and "IExplore", but the other three browsers did not!
  — I hunted about and found Sandbox Options —> App Templates, and found that there were ticks against "Force Mozilla Firefox to run in this sandbox" and "Force Internet Explorer to run in this sandbox".
  — I  unticked both these, and Firefox and IE then opened unsandboxed with the bare commands "Firefox" and "IExplore", as they should have.  
  — But surely these two ticks should have been turned off when I removed the browsers from forcing?  I checked that the corresponding items for Vivaldi, Edge and Brave were all unticked.

 * Does all this perhaps indicate that Sandboxie is not remembering its intended configurations correctly?
 - - - - - - - -

I am not a techie, so all I can do is describe the situation, and suggest that there is some bug.  David, so much detail!  You are going well.

**Comment by offhub** [comment] 2022-07-23 09:28
Probably caused by Vivaldi workaround: [1783](https://github.com/sandboxie-plus/Sandboxie/issues/1783)

From Sandboxie:
UseVivaldiWorkaround=n

From Vivaldi:
Uncheck "Enable Internal PDF Viewer"

**Comment by isaak654** [comment] 2022-09-18 16:46
The issue is still there, however I'm going to close this issue as duplicate in favour of the original https://github.com/sandboxie-plus/Sandboxie/issues/1783
I prefer to see the same details in one place.

**Closed by isaak654** 2022-09-18 16:46 UTC
Labels: Confirmation pending
