### ISSUE TITLE
SBie (file/save as context windows load extremely slowly in Firefox)

### ISSUE THREAD

**Issue by rugabunda** [sandboxie-plus/Sandboxie#109] opened 2020-08-01 07:22 UTC
Anyone else having this issue or know how to mitigate? I don't have this problem in chromium based browsers. Seems my VM's with the same configuration are a lot quicker too.

Thanks!

**Comment by rwasef1830** [comment] 2020-08-10 01:51
Duplicate of https://github.com/sandboxie-plus/Sandboxie/issues/69
Also affects print and almost any shell dialog or control (even native dropdown menus on sites take a second or 2 to appear).

**Closed** 2021-01-09 02:47 UTC
