### ISSUE TITLE
Any program that uses "mklink /j" folder cannot work in sandboxie

### ISSUE THREAD

**Issue by 6Tom** [sandboxie-plus/Sandboxie#3340] opened 2023-09-27 19:09 UTC
### Describe what you noticed and did

Well, this issue is quite difficult to describe. Any Program that uses "mklink /j" folder has this issue. Such as [Microsoft VSCode](https://code.visualstudio.com/updates), [Neat Download Manager](http://neatdownloadmanager.com), [Hibit Uninstaller](https://www.hibitsoft.ir/Uninstaller.html), etc.

Let me give an example to make it easier to understand:

This is a free software called "Neat Download Manager". You can get it here: [http://neatdownloadmanager.com/file/NeatDM_setup.exe](http://neatdownloadmanager.com/file/NeatDM_setup.exe)

After starting it, It will create a new folder `%appdata%\NeatDM`. If you start it in a sandbox now, it can run normally.

But, if you make a "mklink" like this, the program will not work in any sandbox. `mklink /j "C:\test" "%appdata%\NeatDM"`

**This is just an example. If you don't have the “[Neat Download Manager](http://neatdownloadmanager.com)”, you can also experiment with other software, such as ”[Microsoft VSCode](https://code.visualstudio.com/updates)“, and the issue is the same.**

### How often did you encounter it so far?

everytime

### Affected program

Just like any software I have listed up there, and so on.

### Download link

Just like the links I have listed up there.

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

It should work as it used to be. I'm sure [1.10.5](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.10.5) does not have this issue.

### What is your Windows edition and version?

Windows 11 Pro 22H2 64-bit

### In which Windows account you have this problem?

A Microsoft account (Standard user).

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.11.3 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

since Sandboxie Plus 1.11.2 64-bit

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Crash dump

No

### Trace log

No

### Sandboxie.ini configuration

```shell
Creating a new configuration still has the same issue.
```

**Comment by offhub** [comment] 2023-09-27 20:08
Can you please share proper steps to reproduce this issue? In the meantime, try the workaround and see if it helps!

```UseNewSymlinkResolver=n```

**Comment by 6Tom** [comment] 2023-09-27 20:30
Thanks a lot! It really works!

I'm sorry, but I did try to describe this complex matter as clearly as possible. It means that if I don't add the settings you mentioned, once I open a software (This software needs to read some file information from a folder. I used the “mklink” command to link this folder to another location.), it will crash.

Anyway, it has been solved now. Thank you very much again. Have a nice day.

**Comment by isaak654** [comment] 2023-09-27 20:34
#3181

**Comment by 6Tom** [comment] 2023-10-01 19:11
Thank you for your continued interest in this issue. The "junction" made by the command ”mklink“ is indeed useful in certain situations. Sometimes it can be used to save space in "C:\" , or to uniformly manage some scattered folders.

**Comment by DavidXanatos** [comment] 2023-10-02 06:19
This should be fixed with the fix for #3334

**Comment by 6Tom** [comment] 2023-10-06 10:01
Um, actually I think the workaround `UseNewSymlinkResolver=n` is still needed. Otherwise, any software that needs to read files from a "junction" folder will still crash.

I also tried deleting the old sandboxie.ini and creating a new one entirely by sandboxie itself, but the result was the same.

This is tested on [1.11.4](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.11.4).

**Comment by DavidXanatos** [comment] 2023-10-15 16:33
makes a link "C:\test" pointing to "%appdata%\NeatDM"
why would NeatDM use c:\test? its a non standard location,
I tried that and the other way around mklink /j "%appdata%\NeatDM" "C:\test"
in booth cases the app started fine without UseNewSymlinkResolver=n
i created the links outside teh sandbox, should i create them inside?

could you write up a step by step guide how to exactly reproduce this on a clean sandboxie.ini ?

**Comment by 6Tom** [comment] 2023-10-15 19:03
Sorry I'm outside right now, I'll test it as soon as I get home.

**Comment by 6Tom** [comment] 2023-10-16 08:04
I finally figure it out! What the hell, it's a backslash! I did a lot of test!

Look at this one, it can work fine with or without `UseNewSymlinkResolver=n`:
```cmd
mklink /j "%appdata%\NeatDM" "C:\test"
```

But this one, it can work with `UseNewSymlinkResolver=n`. Without `UseNewSymlinkResolver=n`, it will crash.
```cmd
mklink /j "%appdata%\NeatDM\" "C:\test\"
```

The reason I didn't find it before is: "the automatic addition of backslash at the end of a folder" was caused by my upstream code😥😥😥. Really sorry about that. Thanks for your patience.

Um, so is it still a kind of bug? Or is this called a compatibility issue? Because backslash can work fine with `UseNewSymlinkResolver=n`😵‍💫.

**Comment by DavidXanatos** [comment] 2023-10-16 09:25
Its definitely a bug behavior in and outside teh sandbox should be same, and UseNewSymlinkResolver=n is only a fallback to temporarily workaround any bugs in the new code, its not intended to be an option the user has to set.

**Comment by 6Tom** [comment] 2023-10-16 09:43
Thanks for the explanation. You may try this backslash issue. I promise it should be reproduced this time😂.

**Comment by DavidXanatos** [comment] 2023-10-16 11:25
yes it worked and i found what was failing fix will be included in the next build

**Comment by 6Tom** [comment] 2023-10-16 11:31
That's good news. Thanks a lot and have a nice day!

**Closed** 2023-10-25 20:22 UTC
Labels: fixed in next build, Workaround, Symlinks, ReOpened
