### ISSUE TITLE
Lots of SBIE 2101 messsage when I running Overture 5 in Sandboxie 

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#1603] opened 2022-02-07 04:04 UTC
### What happened?

I running Overture 5 in Sandboxie, lots of SBIE 2101 messsage when I click the UI object has any changes (e.g when it start， open file). 

### To Reproduce

1. Run Overture in Sandboxie
2. Sandboxie-Plus pops up lots of SBIE 2101 messsage
![1](https://user-images.githubusercontent.com/56181919/152721258-60a0d9b8-8c50-4277-902f-2f5c7f37b6c6.png)

### Expected behavior

It shouldn't pops up lots of SBIE 2101 messsage

### What is your Windows edition and version?

Windows 10 Enterprise LTSC 2021 x64 (21H2)

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

ESET Internet Security 15.0.23.0

### What version of Sandboxie are you running?

Sandboxie 5.55.10 x64 / Sandboxie-Plus v1.0.10 x64

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Yes, it is also installed outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by Dyras** [comment] 2022-02-07 07:59
I get this while running both Firefox and Brave in Sandboxie. I think it's a new bug for 1.0.10.

This is what I get in a brand new hardened sandbox:
![grafik](https://user-images.githubusercontent.com/12563436/152747850-bffeb9cf-ecfb-4f3c-bec4-8f10a708df1a.png)

**Comment by 0x391F** [comment] 2022-02-07 09:22
I rollback to Sandboxie 5.55.9/Sandboxie-Plus 1.0.9, this bug doesn't reproduce.

**Comment by DavidXanatos** [comment] 2022-02-07 09:30
does the issue reproduce with the  Overture 5 demo version from their website?
please do the following 3 tests:
1:
a. stop sandboxie (using the stop all command)
b. repalce the SbieDll.dll in the instalation folder and the 32 subfodler with the apropriate dll's from the previous build
c. start sandboxie service and try the application

2:
a. stop sandboxie (using the stop all command)
b. repalce the sbiedrv.sys with the one from the previous build
c. start sandboxie service and try the application


3:
a. stop sandboxie (using the stop all command)
b. repalce the SbieSvc.exe in the instalation folder and the 32 subfodler with the apropriate files from the previous build
c. start sandboxie service and try the application

please let me know which of the 3 resolves teh issue for you.

**Comment by Dyras** [comment] 2022-02-07 09:39
When I try copying SbieDll.dll into the Sandboxie-Plus folder, I get an error message saying it's used by another program.

How do I prevent this from happening?

**Comment by Dyras** [comment] 2022-02-07 09:47
Ok so I've tried all three tests now

Number 1: Makes no difference at all

Number 2: Gives the above error

Number 3: Gives this error, but otherwise everything seems to work
![grafik](https://user-images.githubusercontent.com/12563436/152764319-f4e1693c-2a53-4c27-9ffd-1f28f7243ba9.png)

**Comment by DavidXanatos** [comment] 2022-02-07 09:54
ah sorry i forgot something

when you replace SbieSvc.exe you also need to replace the SbieSvc.sig file

please re test and confirm that then everythign is back in order

**Comment by Dyras** [comment] 2022-02-07 10:07
Replacing SbieSvc.exe along with SbieSvc.exe.sig seems to still cause the issue
![grafik](https://user-images.githubusercontent.com/12563436/152766714-e9dbc694-2364-4c35-bf36-b20ba80997db.png)
Same issue if I replace Svc, Svc*sig and SbieDll.dll as well.

When I replace SbieDrv.sys after doing the above however, the message doesn't pop up. Instead brave.exe starts and then it disappears again.

**Comment by Dyras** [comment] 2022-02-07 10:19
Ok so this is what I did trying to figure it out:

I replaced SbieSvc as you wrote about, including sig: **Same issue**

*Reinstalls Sandboxie-Plus 10.10*

Then I replaced SbieDll as you wrote above: **Same issue**

*Reinstalls Sandboxie-Plus 10.10*

Then I added Sbiedrv only: **IT WORKS**

No idea why it didn't work the first time. But the issue is definitely in SbieDrv.sys

**Comment by DavidXanatos** [comment] 2022-02-07 10:26
do you have the HideOtherBoxes=y option in out sandboxie.ini?

**Comment by DavidXanatos** [comment] 2022-02-07 10:36
I'm pretty sure its this will be fixed in the next build

**Comment by Dyras** [comment] 2022-02-07 11:01
@DavidXanatos I sure do! And unclicking it seems to have fixed the issue. Fascinating.

**Comment by 0x391F** [comment] 2022-02-14 06:22
Sandboxie 5.55.11 / Sandboxie-Plus 1.0.11, this bug reproduce.

**Comment by DavidXanatos** [comment] 2022-02-14 08:19
yes the fix is scheduled for 1.1.x as it contains some more fundamental changes see the next branch on the sources on github

**Closed** 2022-03-04 09:44 UTC
Labels: fixed in next build, workaround, regression

**Comment by 0x391F** [comment] 2022-03-24 00:52
Not reproduce in Sandboxie 5.55.14/Sandboxie-Plus 1.0.14
