### ISSUE TITLE
Cannot install the latest wechat

### ISSUE THREAD

**Issue by NianzuMa** [sandboxie-plus/Sandboxie#2226] opened 2022-09-12 23:44 UTC
### Describe what you noticed and did

I tried to right-click the installation package "WeChatSetup.exe", and run in Sandboxie to try to install WeChat into Sandbox. It shows two errors:
PID 3312: SBIE2217 Request to run as Administrator was denied due to dropped rights
PID 3312: SBIE2219 Request was issued by program Start.exe [HardenedDataProtection]

I am using a "Hardened Sandbox with Data Protection". 

### How often did you encounter it so far?

Never successful to run

### Affected program

Wechat

### Download link

https://www.wechat.com/

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Expected behavior

Successfully run the program inside sandbox

### What is your Windows edition and version?

Windows 11 Pro 21H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

No

### What version of Sandboxie are you running?

v1.3.2

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a Hardened sandbox (red sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

### Sandboxie.ini configuration

```shell
Default
```

**Comment by okrc** [comment] 2022-09-13 02:11
<img width="784" alt="image" src="https://user-images.githubusercontent.com/29057533/189791729-1f4e32af-3a92-445b-ba95-89fb1addaa1b.png">
这个？你可能需要启用“模拟管理员权限”。

**Comment by NianzuMa** [comment] 2022-09-13 02:38
Yes, I tried this. 
![Screenshot 2022-09-12 213308](https://user-images.githubusercontent.com/3758964/189794744-d7c77af2-1f2e-48f9-aeb3-f1075c0f415b.png)

But it still shows error:
![Screenshot 2022-09-12 213747](https://user-images.githubusercontent.com/3758964/189795268-9914ca5f-a1bb-4403-891b-429eba843e26.png)

Does it work on your machine?

**Comment by NianzuMa** [comment] 2022-09-13 02:39
![Screenshot 2022-09-12 213308](https://user-images.githubusercontent.com/3758964/189795450-479a8468-330a-451c-be6f-55a5c291e7bd.png)
![Screenshot 2022-09-12 213747](https://user-images.githubusercontent.com/3758964/189795453-c054784b-9d8a-49be-a348-72a22e6e8a54.png)

Still does not work.

**Comment by NianzuMa** [comment] 2022-09-13 02:40
I closed the issue by mistake, how to reopen it?

**Comment by NianzuMa** [comment] 2022-09-13 02:41
Does anyone successfully make it work?

**Comment by okrc** [comment] 2022-09-13 02:42
<img width="983" alt="image" src="https://user-images.githubusercontent.com/29057533/189795822-f57ae962-d906-4191-aa5e-d8f10ff1b6c3.png">

**Comment by NianzuMa** [comment] 2022-09-13 02:47
![3](https://user-images.githubusercontent.com/3758964/189796360-53d502e7-d889-47b4-add1-fde1ed41de9a.png)

Still shows this.

**Comment by okrc** [comment] 2022-09-13 02:59
https://user-images.githubusercontent.com/29057533/189797812-2ffc685c-7492-4feb-b740-faa1d8458f2b.mp4

**Comment by okrc** [comment] 2022-09-13 03:07
You can also try to unzip it without running its installer.

https://user-images.githubusercontent.com/29057533/189798728-c4e18025-9abe-48d8-9787-b74990e03097.mp4

**Comment by NianzuMa** [comment] 2022-09-13 03:25
Using the unzip way work for me. Thank you very much for your help.

**Comment by isaak654** [comment] 2022-09-13 09:42
Did you reboot before receiving [these errors](https://user-images.githubusercontent.com/3758964/189795453-c054784b-9d8a-49be-a348-72a22e6e8a54.png)? Another Win11 user solved the problem this way... if confirmed, SandMan should be able to detect when a reboot is needed.

**Comment by isaak654** [comment] 2022-09-13 09:43
Did you reboot before receiving [these errors](https://user-images.githubusercontent.com/3758964/189795453-c054784b-9d8a-49be-a348-72a22e6e8a54.png)? Another Win11 user solved the problem this way... if confirmed, SandMan should be able to detect when a reboot is needed (imho).

**Comment by NianzuMa** [comment] 2022-09-13 15:58
Do you mean reboot Sandboxie or reboot the Win 11?

**Comment by NianzuMa** [comment] 2022-09-13 16:02
@okrc Hi, I am a new Sandboxie plus user. Is there any place I can get a comprehensive tutorial to deeply understand how Sandboxie works?  Your tutorials are very good.  Without deep understanding, I do not even know these tricks. Thanks.

**Comment by okrc** [comment] 2022-09-13 16:13
@NianzuMa I think you can read Sandbox's [documentation](https://sandboxie-plus.com/sandboxie/helptopics/).

**Comment by NianzuMa** [comment] 2022-09-13 16:19
@okrc Thanks for your suggestion and all your help :smiley:

**Comment by isaak654** [comment] 2022-09-13 18:57
> Do you mean reboot Sandboxie or reboot the Win 11?

Reboot Windows.

**Comment by isaak654** [comment] 2022-09-13 18:59
> Do you mean reboot Sandboxie or reboot the Win 11?

I meant rebooting Windows before running Sandboxie.

**Comment by isaak654** [comment] 2022-09-13 19:18
> I think you can read Sandbox's [documentation](https://sandboxie-plus.com/sandboxie/helptopics/).

That's full of broken links (at this time), see https://github.com/sandboxie-plus/Sandboxie/issues/1915#issuecomment-1144305126.

I'm surprised that almost no one cares enough to remind it.

**Comment by okrc** [comment] 2022-09-13 19:48
> That's full of broken links (at this time), see #1915 (comment) and #1756.

抱歉，我一度误认为这个页面是由sandboxie-docs自动生成的，或者是一个反向代理。从来没有考虑到它的时效性。

Sorry, at one point I mistakenly thought this page was generated by a sandboxie-docs auto-build, or a reverse proxy. Never took into account its timeliness.

**Comment by NianzuMa** [comment] 2022-09-13 19:54
Hopefully, sandboxie can make a good document similar to Pytorch: [https://pytorch.org/tutorials/](https://pytorch.org/tutorials/)  which is really good. 
Sandboxie is a good project, we need to make it to have active community support.

**Comment by 15291367** [comment] 2022-09-21 13:30
> 有没有人成功使它工作？
In normal use, I use Windows 10, and there is no problem you described

**Comment by NianzuMa** [comment] 2023-02-09 04:23
Does anyone have a problem with opening WeChat 3.9.0 in Sandboxie?
![image](https://user-images.githubusercontent.com/3758964/217717344-c703ef28-67c5-4c5a-981b-68b813659196.png)

**Comment by okrc** [comment] 2023-02-09 05:25
In fact, I was unable to reproduce the issue of not being able to install, nor did I see a similar issue. Starting with 3.9.0, it crashes when starting the program, so please close this issue and recreate an issue about the 3.9.0 version crash.


________________________________

**Closed** 2023-02-09 09:48 UTC
Labels: Confirmation pending, Workaround
