### ISSUE TITLE
[Plus 1.1.0] Multiple bug reports and suggestions

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#1885] opened 2022-05-25 00:32 UTC
1. Using 'UseRegDeleteV2=y' option :
Start.exe (4192): SBIE2306 Could not locate user directory:  [C0000005 / 11]
Start.exe (4192): SBIE2304 Initialization failed for process Start.exe
Edit: without separate user folders : 
Start.exe (3912): SBIE2204 Cannot start sandboxed service RpcSs (C0000005)
Start.exe (3912): SBIE2204 Cannot start sandboxed service DcomLaunch (-4)

2. View -> Refresh View only works if 'WatchBoxSize=true'
Steps to reproduce:
- WatchBoxSize=false or missing
- Start Run sandboxed dialog and close it so the status shows anything but empty
- Manually delete the sandbox container via explorer
- Refresh view won't update to show the status as empty unless the user reloads the ini

**---Feature suggestion : add F5 keybind support for refresh view**

```
  EDIT: UI lang setting to 'Auto Detection' was causing this issue not the box size info feature

3. "Count and display the disk space occupied by each sandbox" global option
  Will delete all the sandbox groups (BoxDisplayOrder)
  That is unnecessary even reseting the GUI

  Just adding 'WatchBoxSize=true' to Plus ini is enough and without losing customizations

```
4. Application Error related to 'WatchBoxSize=true' after box session ended (all proccesses in a box are termianted) :

> Faulting application name: SandMan.exe, version: 1.1.0.0
> Faulting module name: ntdll.dll, version: 6.1.7601.23915
> Exception code: 0xc0000374
> Fault offset: 0x00000000000bf3e2
> Faulting application path: C:\Program Files\Sandboxie\SandMan.exe
> Faulting module path: C:\Windows\SYSTEM32\ntdll.dll

  Steps to reproduce:
- Start any program or Run sandboxed dialog and close it
- Sandman takes a coffee break
![1](https://user-images.githubusercontent.com/19516333/170396952-e36c1a9f-0e11-442c-bc3a-5015d636d509.jpg)
- Application Error EventID 1000 in event viewer

*Sandman does not create a dmp with this crash , if this may help attached the dll 
[ntdll.zip](https://github.com/sandboxie-plus/Sandboxie/files/8775603/ntdll.zip)

**---Suggestion: Option that controls whenever or not the diskcache entry is updated automatically when a box session ends, would allow others that have the same issue to still make use of the box size column feature**

5. Using 'UseFileDeleteV2=y' option : 
Sanboxed explorer window won't show when first launched , requires to termiante process and relauch to have the window appear.
Will freeze on shift delete action , requires to be terminated, the deleted file by the sandboxed explorer will be listed to the .dat file despite that it will still be visible on a relaunched sandboxed explorer

6. https://github.com/sandboxie-plus/Sandboxie/issues/1840#issuecomment-1122119463

Windows 7 Ultimate SP1 x64
Plus 1.1.0 x64

**Comment by droped** [comment] 2022-05-25 00:41
I have the first issue too. It only happens with Separate User Folders on.

**Comment by DavidXanatos** [comment] 2022-05-25 08:06
I can only confirm the Separate User Folders at this moment, the other issues may be windows 7 releated will have to test it on that platform

Performance with this new in general is yet not fully optimized, so reports of how to reproduce bad performance are much appriciated to test it and fix it.

**Comment by DavidXanatos** [comment] 2022-05-25 09:24
I have tried the latest build on a windows 7 VM and it seams to work fine, except for the separate folder issue.
Also switching that option did not delete any box order informations.
Please try a clean install, or test on a clean VM

**Comment by RandomGOTI** [comment] 2022-05-25 11:20
> Also switching that option did not delete any box order informations. Please try a clean install, or test on a clean VM

happens with a new sandboxie-plus ini , opening the global options and clicking apply or ok will reset any customizations done beforehand
if instead of letting sandman create the ini have it with only this content the issue will not happen at all :
[Options]
UiLanguage=native

And as soon as i change from no translation to auto ,customizations are nuked again  .. I had the wrong culprit

**Comment by isaak654** [comment] 2022-05-29 19:43
For the record, the first post has been updated by the author for further reconsideration.

**Comment by DavidXanatos** [comment] 2022-05-30 07:37
### Added
- Refresh command is now bound to F5 [#1885](https://github.com/sandboxie-plus/Sandboxie/issues/1885)

### Fixed
- fixed issues with the new delete mechanism with "SeparateUserFolders=y" [#1885](https://github.com/sandboxie-plus/Sandboxie/issues/1885)
- refresh now works without WatchBoxSize option [#1885](https://github.com/sandboxie-plus/Sandboxie/issues/1885)


so status:


1. fixed

2. fixed

3. can't reproduce

4. can't reproduce

5. can't reproduce
 
6. will look into it

**Comment by hg421** [comment] 2022-05-30 17:53
Just wanted to mention that I've also encountered issue 4 (the SandMan crash after closing the boxed process, when disk usage reporting is enabled), in Windows 10.

**Comment by isaak654** [comment] 2022-05-30 18:57
> Just wanted to mention that I've also encountered issue 4 (the SandMan crash after closing the boxed process, when disk usage reporting is enabled), in Windows 10.

Confirmed. In order to reproduce the SandMan crash, I had to suddenly press "terminate all programs" while having a sandboxed MS Edge session with 4 tabs or more. The only difference with the error mentioned in OP is the absence of a message error, just a UI crash.

**Comment by DavidXanatos** [comment] 2022-06-04 19:07
1. fixed
2. fixed
3. __fixed__
4. fixed
5. can't reproduce
6. fixed

**Comment by isaak654** [comment] 2022-06-04 20:37
I don't know if it's intended, but the F5 keybind for refresh view doesn't show any visual refresh when it's pressed.

**Comment by isaak654** [comment] 2022-06-04 20:37
I don't know if it's intended, but the F5 keybind for refresh view doesn't show any visual refresh when it's pressed on the latest CI build.

**Comment by DavidXanatos** [comment] 2022-06-05 07:10
on my test system it trigers a refresh, do you have 'WatchBoxSize=true' without that usually you wont see an afect of a refresh

**Comment by isaak654** [comment] 2022-06-05 11:59
> on my test system it trigers a refresh, do you have 'WatchBoxSize=true' without that usually you wont see an afect of a refresh

Yes, it's correctly set in Sandboxie-Plus.ini. I have no clue why it doesn't work for me.

**Closed** 2022-06-07 05:52 UTC
Labels: Bug, fixed in next build, Workaround, suggestions
