### ISSUE TITLE
A problem about hotkey in my installed application

### ISSUE THREAD

**Issue by ENIAC20** [sandboxie-plus/Sandboxie#421] opened 2021-01-20 06:37 UTC
After I had installed Sandboxie-Plus-x64-v0.5.5.exe , then I right-click the installed application icon and selected "Run Sandboxed" , my application run successfully , but I was prompted for a hotkey conflict by my application . So I tried to reset the hotkey many times , but the other hotkey combinations I tried still conflict , including some complex hotkeys like "alt + shift + ctrl + F7" .  So I think all hotkey combinations will conflict . When I exit Sandboxie-Plus , run applications as normal , there is no hotkey conflict , everything as normal .

**Comment by bastik-1001** [comment] 2021-01-23 11:02
This is a duplicate of #192.

Right now the security properties of Sandboxie prevent hotkeys from being registered and used.

**Comment by ENIAC20** [comment] 2021-01-23 11:36
> This is a duplicate of #192.
> 
> Right now the security properties of Sandboxie prevent hotkeys from being registered and used.

Thank you very much for your reply.

**Closed** 2021-01-23 11:59 UTC
