### ISSUE TITLE
Can't access camera

### ISSUE THREAD

**Issue by yijiangchengming** [sandboxie-plus/Sandboxie#2197] opened 2022-08-30 12:01 UTC
### Describe what you noticed and did

**Since I upgraded to Win11, programs inside the sandbox cannot access the camera, but it works fine in Win10. I have tried versions 0.98-1.28, all have this problem.**
I follow this to track, but I don't know what to do with changing values: https://github.com/sandboxie-plus/Sandboxie/issues/1208#issuecomment-1200170825
```
ComClass          COM <00000001> CRE-IN <00000000> CLSID: {366F6FDF-839D-4ED5-BFC6-7301A42A2F20} FSClientFactory; Interface: {A9F69869-9293-49E2-AF4A-B45164B073CC} IUnknown             23     

ComClass          COM <00000001> CRE-IN <00000000> CLSID: {62BE5D10-60EB-11D0-BD3B-00A0C911CE86} System Device Enumerator; Interface: {62BE5D10-60EB-11D0-BD3B-00A0C911CE86} IUnknown    23     

ComClass          COM <00000001> CRE-IN <00000000> CLSID: {860BB310-5D01-11D0-BD3B-00A0C911CE86} VFW Capture Class Manager; Interface: {29840822-5B84-11D0-BD3B-00A0C911CE86} IUnknown   23     

ComClass          COM <00000017> CRE-IN <00000000> CLSID: {62BE5D10-60EB-11D0-BD3B-00A0C911CE86} System Device Enumerator; Interface: {29840822-5B84-11D0-BD3B-00A0C911CE86} IUnknown    23     

ComClass          COM <00000401> CRE-IN <00000000> CLSID: {17CCA71B-ECD7-11D0-B908-00A0C9223196} Generic WDM Filter Proxy; Interface: {00000000-0000-0000-C000-000000000046} IUnknown    23     

ComClass          COM <00000401> CRE-IN <00000000> CLSID: {95FEE196-49F0-4C30-B16C-22C7B75C18EC} Dshow Camera MF Filter; Interface: {00000000-0000-0000-C000-000000000046} IUnknown      23     

ComClass          COM <00000403> CRE-IN <00000000> CLSID: {00000352-0000-0000-C000-000000000046} IUnknown; Interface: {00000003-0000-0000-C000-000000000046} IUnknown                    23     

RtClass           Windows.Internal.CapabilityAccess.CapabilityAccess                                                                                                                     23     

RtClass           Windows.Media.Audio.AudioStateMonitor                                                                                                                                  23     

RtClass           Windows.Security.Authorization.AppCapabilityAccess.AppCapability                                                                                                       23     
```
![image](https://user-images.githubusercontent.com/30022966/187428507-edbb895f-6419-48af-835f-ed1d2d226586.png)

### Affected program

TIM,Wechat

### Download link

https://tim.qq.com/

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

It should be a bug because on Win10 it works fine

### What is your Windows edition and version?

Windows 11 21H2 22000.918 

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

M D

### What version of Sandboxie are you running?

1.28

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment] 2022-08-30 14:57
You could try to set various [OpenClsid](https://sandboxie-plus.github.io/sandboxie-docs/Content/OpenClsid.html) / ClosedClsid rules for the ComClass references you mentioned.
But a list of additional Resource Access settings is also available: [ResourceAccess](https://sandboxie-plus.github.io/sandboxie-docs/Content/ResourceAccess.html)

Any contribution to the documentation would be appreciated.

**Comment by lwcorp** [comment] 2022-09-02 11:09
Isn't it a another duplicate of #1669?

**Comment by DavidXanatos** [comment] 2023-05-21 14:43
please reffer to the original issue: https://github.com/sandboxie-plus/Sandboxie/issues/1669

**Closed** 2023-05-21 14:43 UTC
Labels: Confirmation pending
