### ISSUE TITLE
Access Restrictions Whitelist ignored in Firefox 106.0.1

### ISSUE THREAD

**Issue by rugabunda** [sandboxie-plus/Sandboxie#2391] opened 2022-10-25 00:14 UTC
### Describe what you noticed and did

1. run firefox
2. install [videodownloadhelper](https://addons.mozilla.org/en-CA/firefox/addon/video-downloadhelper/) addon, and [companion co-app](https://www.downloadhelper.net/install-coapp)
3. whitelist net.downloadhelper.coapp-win-64.exe in start restrictions (C:\Program Files\net.downloadhelper.coapp\bin\net.downloadhelper.coapp-win-64.exe)

![image](https://user-images.githubusercontent.com/38260267/197651554-753a2ea8-2bda-45ac-b1dc-9cf6a45a0015.png)

4. load firefox
5. note:

![image](https://user-images.githubusercontent.com/38260267/197651480-e8439377-2900-458a-8c15-3c60068979b5.png)

### How often did you encounter it so far?

After Firefox 106.0

### Affected program

videodownloadhelper co-app

### Download link

Addon: https://addons.mozilla.org/en-CA/firefox/addon/video-downloadhelper/
Co-app: https://www.downloadhelper.net/install-coapp

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Whitelist should not be bypassed

### What is your Windows edition and version?

Win 11 21H2

### In which Windows account you have this problem?

I use the built-in Administrator with Admin Approval Mode turned on.

### Please mention any installed security software

ESET

### What version of Sandboxie are you running?

1.5.0 / 1.5.1 https://github.com/sandboxie-plus/Sandboxie/issues/2391#issuecomment-1292315804

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by rugabunda** [comment] 2022-10-25 00:17
Problem appeared to begin after updating to firefox 1.0.6.0; I believe this was before the sbie release fixing video problems in firefox.

**Comment by bastik-1001** [comment] 2022-10-26 16:38
I see this as well, with Sandboxie 1.5.0 and 1.5.1.

**Comment by isaak654** [comment] 2022-10-28 20:12
Isn't it the same of https://github.com/sandboxie-plus/Sandboxie/issues/724#issuecomment-811137068 ?

**Comment by rugabunda** [comment] 2022-10-30 01:04
> Isn't it the same of [#724 (comment)](https://github.com/sandboxie-plus/Sandboxie/issues/724#issuecomment-811137068) ?

Just started for me in recent releases, never had a problem until the last week or so

**Comment by bastik-1001** [comment] 2022-11-04 17:24
Sandboxie creates a copy of "C:\Program Files\net.downloadhelper.coapp\bin\net.downloadhelper.coapp-win-64.exe", which it seemingly didn't do before. That assumption is based on the fact that the message came up with Sandboxie 1.5.0.

Adding `DontCopy=C:\Program Files\net.downloadhelper.coapp\bin\net.downloadhelper.coapp-win-64.exe` to the .ini section for the box with the start restriction, where this process is whitelisted, does indeed not copy the file and therefore does not show the error. Thank you isaak for pointing to the other issue, which made me check if the reason was that the application was being copied.

**Comment by rugabunda** [comment] 2022-11-05 06:39
Thank you @bastik-1001 , problem solved. How would this be dealt with in the official version? A dedicated template?

**Comment by DavidXanatos** [comment] 2022-11-07 10:21
I have investigated this issue and firefox's xul.dll is requesting GENERIC_WRITE on net.downloadhelper.coapp-win-64.exe and sandboxie as it should then migrates the file into the sandbox, so apparently this issue must be caused by a recent change in forefox and not in sandboxie. 

the DontCopy approach is the right fix for this problem, it should be put into a compatibility template.

**Comment by isaak654** [comment] 2022-11-07 10:38
Well, there is already a template which seems fit for purpose:

https://github.com/sandboxie-plus/Sandboxie/blob/6177d84361bd2c7f84d643218c8ccd7dc600b450/Sandboxie/install/Templates.ini#L3364-L3372

**Closed** 2022-11-08 07:35 UTC
Labels: fixed in next build, Issue reproduced, Firefox-related

**Comment by rugabunda** [comment] 2022-11-09 02:34
> This seam to be a generic firefox issue, it tryes to open any plugin for writing looks like a ff bug to me, same issue with roboform. So I'm looking towards a generic fix for booth as well as other unknown plugins...

Thank you David

**Comment by bastik-1001** [comment] 2022-11-09 18:04
Can anyone see a reason why Firefox changed its behavior? Thank you for working around that issue.
