### ISSUE TITLE
SBIE2101 Sandboxie crashes when trying to run EAC games like Gears 5 or Star Wars Squadrons 

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#946] opened 2021-06-28 17:50 UTC
**Summary**
The game [Gears 5](https://www.pcgamingwiki.com/wiki/Gears_5) doesn't work in Sandboxie. When trying to launch, Sandboxie throws the 2101 error.
![gears5test](https://user-images.githubusercontent.com/12411527/123681041-9c371580-d849-11eb-8250-73b934ca034d.png)
This surprised me, because many Unreal Engine games do run fine sandboxed.

**Setup**
SB Classic 5.50.2
Windows10 20H2 64bit

I used a fresh new sandbox without any additional settings:
```
[GlobalSettings]

Template=RpcPortBindings
Template=7zipShellEx
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
FileRootPath=D:\Sandbox\%SANDBOX%
TemplateReject=AdobeAcrobatReader

[UserSettings_0C980217]

SbieCtrl_UserName=XXX
SbieCtrl_NextUpdateCheck=-1
SbieCtrl_EnableLogonStart=n
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=527,-605,1237,703
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_ReloadConfNotify=n
SbieCtrl_ExplorerWarn=n
SbieCtrl_ShouldDeleteNotify=n
SbieCtrl_TerminateWarn=n
SbieCtrl_UpdateCheckNotify=y
SbieCtrl_AutoApplySettings=y
SbieCtrl_SettingChangeNotify=n
BoxDisplayOrder=Gears5Test
SbieCtrl_ShortcutNotify=n
SbieCtrl_EditConfNotify=n
SbieCtrl_BoxExpandedView=Gears5Test

[Gears5Test]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl,6
```

Does anyone else have this game and could give it a try?

**Comment by sebadamus** [comment] 2021-07-27 21:02
It gives me the same error but trying to run Microsoft Flight Simulator (new version)
![imagen](https://user-images.githubusercontent.com/1787753/127226999-0bf39dfe-b142-447f-9d95-5b32a0e9e59f.png)

**Comment by NewKidOnTheBlock** [comment] 2022-11-29 13:11
Gears 5 requires EasyAntiCheat (EAC).
I've encountered the same problem when trying to run Star Wars Squadrons - which also uses EAC - in Sandboxie.

**Comment by isaak654** [comment] 2022-11-29 14:36
Duplicate of #1192

**Closed** 2022-11-29 14:37 UTC
Labels: duplicate, game issue
