### ISSUE TITLE
Sandboxie can't run the 'UWP' application on windows

### ISSUE THREAD

**Issue by sandyz987** [sandboxie-plus/Sandboxie#2105] opened 2022-08-09 03:45 UTC
### Is your feature request related to a problem or use case?

Sandboxie can't run the 'UWP' application on windows. When i try to open one, it show me that 'it isn't a valid win32 program'

### Describe the solution you'd like

will you support this feature?

**Comment by isaak654** [comment] 2022-08-09 06:31
Duplicate of #19

**Comment by DavidXanatos** [comment] 2022-09-01 20:18
since this duplicate does not add anything I'll close it now

**Closed by DavidXanatos** 2022-09-01 20:18 UTC
Labels: duplicate, Feature request, UWP
