### ISSUE TITLE
Prevent sandboxed programs from accessing screenshots of a window outside the sandbox

### ISSUE THREAD

**Issue by czoins** [sandboxie-plus/Sandboxie#1985] opened 2022-06-24 01:40 UTC
### Is your feature request related to a problem or use case?

Any process running inside the sandbox can take screenshots/record your screen, increasing risk when you cannot disable internet access for the process (for usability)

### Describe the solution you'd like

Is it possible to prevent processes running inside the box from having access to the screen/other windows? Other products like Kaspersky implement this feature, and return a black screen instead of the actual content when taking a screenshot/screen recording. Just like the clipboard access, I don't think (from my limited knowledge) that the processes need this access to function.

**Comment by isaak654** [comment] 2022-06-25 21:09
Duplicate of #624

**Comment by DavidXanatos** [comment] 2024-03-05 07:50
Please elaborate which otehr products except kaspersky,a nd how do thay do it in which usecases etc.

**Comment by DavidXanatos** [comment] 2024-03-25 19:32
This feature has been added in 1.13.4 however please consider that it is user mode protection only hence malware targeting sandboxie explicitly can bypass it, also the implementation may not yet cover all means available to capture the screen.

**Closed** 2024-07-25 06:18 UTC
Labels: Feature request, Confirmation pending, added in next build
