### ISSUE TITLE
Program tries to load resource files from wrong folder when starting in Windows Explorer after being moved into a Forced Folder

### ISSUE THREAD

**Issue by RadarNyan** [sandboxie-plus/Sandboxie#1507] opened 2022-01-03 13:32 UTC
**Describe the problem**
When you start a program by double-clicking it in Windows Explorer, the program would launch, but it's unable to load resource files due to trying to access it from original location.

**To Reproduce**
1. Create the following folder structure:
```
C:\Test\Download
C:\Test\Forced
```
2. Create a new Sandbox, add `C:\Test\Forced` to Forced Folders.
3. Download SAMPLE_GAME.zip from another issue #1445 I created. You can use any program that loads external resource files.
4. Extract `SAMPLE_GAME.zip` to a folder, now you have `C:\Test\Download\SAMPLE_GAME`.
5. Move the `SAMPLE_GAME` folder to `C:\Test\Forced`.
6. Open `C:\Test\Forced\SAMPLE_GAME` in Windows Explorer and double-click on `Game.exe`.
7. The program runs but fail to load resource files with error message: `Cannot locate basic info data C:\Test/Download/SAMPLE_GAME/Data/BasicData/Game.dat`, note that it tries to load the file from `Download` instead of `Forced`.
8. Terminate Programs, try to start the game using `Run Sandboxed - Run Any Program` dialog, or right-click on `Game.exe` in Windows Explorer and select `Run Sandboxed` command, the program runs and loads the files without error.
9. You can try to repeat step 6, and it still won't work.

**Workaround**
This is a workaround I discovered by accident, just right-click on `Game.exe` and select `Properties`, from now on it will run just fine.

Also, this is an old bug presents in original Sandboxie.

**Comment by mysteriously** [comment] 2022-01-03 18:48
This looks similar to other issue (which most likely got fixed already as I was not able to reproduce it anymore)
https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopiceb8eeb8e.html?p=132071#p132071

**Comment by RadarNyan** [comment] 2022-01-04 01:50
> This looks similar to other issue (which most likely got fixed already as I was not able to reproduce it anymore) https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopiceb8eeb8e.html?p=132071#p132071

If you read that thread you'll notice that I mentioned the same workaround back then under the same screen name.

And no, this is not fixed and I can reproduce this on both my Windows 7 installation and a fresh Windows 10 LTSC 2021 VM:
![SnapCrab_NoName_2022-1-4_10-46-35_No-00](https://user-images.githubusercontent.com/2091529/147999130-034e6af8-ad41-4923-b990-87b3cc50b93b.png)

**Comment by DavidXanatos** [comment] 2022-01-07 21:31
for me this procedure worked just fine,
am i missing a step or something.

Am I suposed to move the file form download to forces with a sandboxed explorer or something?

I don't see how the game could be in any way aware of the C:\Test\Download location

can you make a video or something please

**Comment by RadarNyan** [comment] 2022-01-08 11:47
https://user-images.githubusercontent.com/2091529/148642899-5939f357-3e24-4ec7-8274-c56dee62d168.mp4

I believe this is more like a problem of Windows Explorer, not the game.

**Comment by RadarNyan** [comment] 2022-01-08 11:58
[Quote from the old sandboxie forum](https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopicdd4add4a.html?f=11&t=21319&start=15#p110264):
>For some reason, when Windows sends us the notification of a process starting, it is giving us the old file path. I will research this to find out why.

Maybe check if the Windows provided path exist, if not use the executable location instead?

**Comment by DavidXanatos** [comment] 2022-01-08 19:31
are there debug symbols available for this game engine?
or some much simpler sample that would demonstrate this issue?

**Comment by DavidXanatos** [comment] 2022-01-08 21:04
the issue was with Ldr_FixImagePath_2, fil will be included in the next build

**Comment by mysteriously** [comment] 2022-01-08 22:52
> And no, this is not fixed and I can reproduce this on both my Windows 7 installation and a fresh Windows 10 LTSC 2021 VM:

By fixed I meant the issue I liked in previous post.

I wonder if your game would run sandboxed or not when you move it to folder3 (which is not forced) at the end of the movie .

**Comment by DavidXanatos** [comment] 2022-01-09 08:34
> > And no, this is not fixed and I can reproduce this on both my Windows 7 installation and a fresh Windows 10 LTSC 2021 VM:
> 
> By fixed I meant the issue I liked in previous post.
> 
> I wonder if your game would run sandboxed or not when you move it to folder3 (which is not forced) at the end of the movie .

Please link to the issue you are referring to.

**Closed** 2022-01-18 09:40 UTC
Labels: fixed in next build
