### ISSUE TITLE
OpenFilePath no longer works on file level

### ISSUE THREAD

**Issue by otto1984** [sandboxie-plus/Sandboxie#174] opened 2020-10-28 15:22 UTC
Hi,

I used the OpenFilePath parameter to allow access to the bookmarks file and block other changes in the profile.

`OpenFilePath=%UserProfile%\AppData\Local\Microsoft\Edge\User Data\Default\Bookmarks`

When I add a new bookmark, it is not saved in the Bookmars file and is removed after closing the sandbox.
If I set the OpenFilePath to 

`OpenFilePath=%UserProfile%\AppData\Local\Microsoft\Edge\User Data\Default\`

The Browser can save the new bookmarks
The setting works for years with the original sandboxie software.
I have the same behavior with the Brave Browser.

Can you check this please? (System: Win10 Prof Vers. 2004)

Thx

**Comment by Deadite333** [comment] 2020-10-28 16:50
It's a known Chromium browser based bug and to be fixed with the next Sandboxie update. There was a thread dealing with it, but the guy who opened the thread closed it, so unfortunately it's no longer openly around. 

DavidXanatos wrote:
"I found the issue it was a bug introduced with one of the driver verifier fixes and affects file renaming.

Chrome and derivatives create a temporary bookmark file and than rename it to its target name which is white listed in the ini, this renaming operation failed.

The issue is resolved in builds 0.4.4 / 5.43.7 and later (which are to be released soon), until than a workaround could be to allow chrome access to the entire chrome profile folder i.e. using
OpenFilePath=chrome.exe,%Local AppData%\Google\Chrome\User Data\Default*)"

Until the update you could allow Read-only access to the Default folder's relevant files and folders in the Sandboxie options.

**Closed** 2020-11-03 16:53 UTC
Labels: fixed in next build, known issue
