### ISSUE TITLE
SandboxieInstall64-v5.45.1 file is detected as a virus.

### ISSUE THREAD

**Issue by gomdoll22** [sandboxie-plus/Sandboxie#279] opened 2020-12-24 16:36 UTC
![2020-12-25 01 33 17](https://user-images.githubusercontent.com/76566089/103099294-45aa0e00-4651-11eb-9850-ca406a13d268.jpg)

https://www.virustotal.com/gui/file/9e43ab6eb17263335c3cab37c1044b795ebc68fb1b71768098d72c48d7e966b7/detection

When I try to install this file, avast antivirus detects a virus.

Please fix it! thanks!

**Comment by DavidXanatos** [comment] 2020-12-25 09:35
Fixing it means complaining with avast about them screwing up and producing false positives, as their customer you can do that just as good.
I'm really fed up with all that stupid anti malware fools...

The extent of my affords in this regard are limited to: If windows defender does not complain that's good enough.

Its a free time project and I wont waste my own free time to solve problems other idiots caused by being lazy and producing software that fails at its most basic function.

Can't you set an exception in Avast to tolerate the file? As yo see on VT the file is clean or else you would have > 50% AV's complaining about it. Avast being stupid should not hinder you on exerting your rights as the administrator of your PC to install whatever you want to install.
Its your hardware, you are the admin, its ultimately your decision, and IMHO you should get rid of any software that tries to take your decision away.

Or just throw money on the problem, if you become a patron at the "More Support" tier or higher I'll complain with avast for you, but no guaranty they will listen.

**Comment by Stitch626** [comment] 2020-12-28 19:39
You can create a C program with 5 lines of code to trigger avast. At least that happened to me when I tried some simple tasks in a small program. I would agree with the statement that it's avast's fault and not the program's. Just ignore that false positive and continue.  Or - if you don't trust the the installation routine - run it in a VM. But be careful, meltdown, spectre and other things may still be a problem and could allow your clean sandboxie install to bypass every security your cpu has built in. 
Well, that was kind of a joke if you didn't get it til now. I'd ignore up to 3 or 4 false positives at Virustotal. And if you don't feel comfy with that, go ahead and search for the virus definitions given by VT. And if you don't trust it afterwards, well, just don't use it.  

To be short:
As a (non-paid) developer, it's not worth the effort to fight for your software to be undetected. Either people report it as a false 
 positive (on their side), or use it anyways.  The time (and energy) wasted with AV solutions (user or non-av developer side) could be used for something more useful. 
I'd like to write even more but it's also waste of time/energy and my language knowledge isn't the best either.

**Comment by DavidXanatos** [comment] 2020-12-29 17:43
so we agree avast suxxxx so I'll close this one.

**Closed by DavidXanatos** 2020-12-29 17:43 UTC
