### ISSUE TITLE
Delete Content while programs are running behavior is unclear

### ISSUE THREAD

**Issue by hippalectryon-0** [sandboxie-plus/Sandboxie#1692] opened 2022-03-15 12:47 UTC
### What happened?

Context: _see "to reproduce" below_

*Problem*: One would expect that upon clicking _OK_, we have to stop the processes and restart the _Delete content_ operation. However upon clicking _OK_, sandboxie automatically kills the running processes and does not delete the box's content

*Proposed solutions*:
*Option 1* Do nothing when _OK_ is pressed
*Option 2* Add another button so that the user can choose between 1) not doing anything 2) stopping all processes **and** deleting the box's content
*Additional remark*: The initial _Delete content_ popup could check whether there are running processes and display a warning if this is the case

### To Reproduce

* start a web browser in the default sandbox
* save a file from the browser to the sandbox
* launch _Delete content_ on the default sandbox and click _Yes_ while the browser is still running
What happens: sandboxie shows the following: 
![image](https://user-images.githubusercontent.com/6502864/158379275-a87379ce-a3b9-47e5-a1a9-ea529507e2d4.png)

### Expected behavior

One would not expect clicking _OK_ to stop all running processes. Moreover, upon seeing that the processes got stopped, one does not know right away whether the contents have been deleted or not.

### What is your Windows edition and version?

Not relevant

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

SB-Plus 1.0.13

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment] 2022-04-16 12:21
the intended behavioure is to hill all processes and empty the box, the error emssage was an error and was already fixed in 1.0.18

**Closed by DavidXanatos** 2022-04-16 12:21 UTC
Labels: User interface
