### ISSUE TITLE
Add sbiedll detection bypass

### ISSUE THREAD

**Issue by Aholicknight** [sandboxie-plus/Sandboxie#2310] opened 2022-10-07 04:27 UTC
### Is your feature request related to a problem or use case?

![msedge_2010862948](https://user-images.githubusercontent.com/7843719/194467372-0d0bbcfb-54c6-47f8-8a9d-970dd299ea97.png)
![image](https://user-images.githubusercontent.com/7843719/194467626-8350591e-8ee9-4443-b5f0-bbeec2cb9d1e.png)

Some programs that I want to run in a sandbox can detect that the program is being ran in a sandbox via module names. As seen in the screenshot, the detection method used is the DLL name.  Most of these programs that have this are also protected with VMProtect or a different protector and cannot be modified.

### Describe the solution you'd like

An option to rename the sbiedll to something else to improve less sandbox detections.  

### Describe alternatives you've considered

- Renaming sbiedll manually makes sandboxie no longer work because the program cannot find sbiedll.

**Comment by bastik-1001** [comment] 2022-10-08 07:29
This is possibly a duplicate of #234 and #2178.

If a custom dll name it all it takes to evade detection, then it might be worth it. Once they apply more sophisticated approaches, it may fail, and I see why David does not want to get into an arms race, playing cat and mice.

**Comment by mysteriously** [comment] 2022-10-08 10:52
Besides blocking access to the file you may fake it's path

**Comment by Aholicknight** [comment] 2022-10-08 20:49
> Besides blocking access to the file you may fake it's path

@mysteriously how would I block access to the file or the path? does this require sandboxie plus?

**Comment by paradoxicallist** [comment] 2022-10-09 14:12
> Besides blocking access to the file you may fake it's path

Could you show us an example please?

**Comment by mysteriously** [comment] 2022-10-10 19:18
You can block using ini or create symlink to fake path?

You didnt mention the name of the software

**Comment by Aholicknight** [comment] 2022-10-11 17:30
> You can block using ini or create symlink to fake path
> 
> You didnt mention the name of the software

Ill try this

**Comment by i486** [comment] 2022-11-06 04:45
@DavidXanatos 

Are there any documents on how to build it?

**Comment by Aholicknight** [comment] 2022-11-17 19:06
@DavidXanatos do you know how i can symlink sbiedll? thank you

**Comment by Aholicknight** [comment] 2022-11-17 19:07
@mysteriously can you please show what the ini file should look like when blocking sbiedll? thank you

**Comment by mysteriously** [comment] 2022-11-18 20:29
Ok, let's summarize that.

You are trying to run some shady software which detect SBIE for a reason. You don't even bother to post the name of the software thought.
So, you know it is doing its job but at the same time you literally went to official support forum to ask for help anyway. Even if you find a solution and shady software developer will detect you are somehow bypassing the protection mechanism, this forum will be first place for the shady software developer to look for an answer why his protection does not work anymore.

What's more, you expect to post the solution on public instead of keeping it for yourself once you find it.

Seriously dude?

**Comment by VeroFess** [comment] 2022-11-23 04:45
try this https://github.com/VeroFess/SbieHide

**Comment by DavidXanatos** [comment] 2023-01-28 17:38
@VeroFess oh this is very nice, so this issue can be closed, great :D
I have added a new readme section listing SbieHide: https://github.com/sandboxie-plus/Sandboxie/blob/master/README.md#-usefull-tools-for-sandboxie I hope that's all right?

**Closed by DavidXanatos** 2023-01-28 17:38 UTC
Labels: Feature request

**Comment by krudge137** [comment] 2023-05-02 14:41
> This is possibly a duplicate of #234 and #2178.
> 
> If a custom dll name it all it takes to evade detection, then it might be worth it. Once they apply more sophisticated approaches, it may fail, and I see why David does not want to get into an arms race, playing cat and mice.

can you help me with that please? all I need is to rename the dll I'm fine with it being detected as long as it doesn't have Sbiedll.dll

**Comment by isaak654** [comment] 2023-05-03 17:50
> can you help me with that please? all I need is to rename the dll I'm fine with it being detected as long as it doesn't have Sbiedll.dll. I have tried renaming the dll through `my_version.h` I don't know if I did something wrong but it didn't work as intended.

He's waiting your reply in another issue: https://github.com/sandboxie-plus/Sandboxie/issues/2880#issuecomment-1532087581

Stop crossposting please.

**Comment by isaak654** [comment] 2023-05-03 18:24
> all I need is to rename the dll 

👉 https://github.com/sandboxie-plus/Sandboxie/issues/2880#issuecomment-1532087581
