### ISSUE TITLE
Remember between executions

### ISSUE THREAD

**Issue by cyberience** [sandboxie-plus/Sandboxie#2320] opened 2022-10-08 05:46 UTC
### Describe what you noticed and did

I noticed that it seems, without Sandboxie, the login credentials for Steam are remembered, but when relaunching the app after a reboot in Sandbox, it is not, is there a way to remember the meta data between runs?
To reproduce:
1) Run steam in Dedicated Sandbox 
2) Login and tick remember me
3) Close steam and reboot Computer. (Right click steam in SB and terminate does the same thing)
4) Repat 1)
5) Login not remembered.
Am I missing something, such as Keep app data persistent option or something?

### How often did you encounter it so far?

Every time

### Affected program

Steam

### Download link

https://store.steampowered.com/

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

1) Run steam in Dedicated Sandbox 
2) Login and tick remember me
3) Close steam and reboot Computer. (Right click steam in SB and terminate does the same thing)
4) Repat 1)
5) Login remembered.

### What is your Windows edition and version?

Windows 10

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Disabled

### What version of Sandboxie are you running?

Sandbox Plus 1.3.5

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by RandomGOTI** [comment] 2022-10-08 20:54
I have no issues with my steam box , i have auto login for the box and can log with a different account unsanboxed, try with a clean new standard isolation box probably you have over-configured yours

**Comment by DavidXanatos** [comment] 2022-10-09 12:42
try
```
OpenProtectedStorage=y
```

**Comment by cyberience** [comment] 2022-10-10 02:59
Thanks, though good solutions, doesn't seem to help with the EAC problem, so  won't be able to use sandbox for Gaming if the games are protected.

**Comment by DavidXanatos** [comment] 2022-12-23 19:14
so the issue is fixed by using OpenProtectedStorage then I'll close this now

**Closed by DavidXanatos** 2022-12-23 19:14 UTC
Labels: Confirmation pending
