### ISSUE TITLE
Running Chrome in Sandboxie makes "bits" try to run over and again

### ISSUE THREAD

**Issue by Dyras** [sandboxie-plus/Sandboxie#1081] opened 2021-08-07 18:13 UTC
**Describe the bug**

**To Reproduce**
0. Drop rights in the sandbox on an admin account
1. Make a desktop shortcut for Chrome
2. Run it
3. Look at the picture

**Expected behavior**
The service "bits" tries to run over and over again, but can't due to dropped rights

**Screenshots**
![grafik](https://user-images.githubusercontent.com/12563436/128610092-6ea17b93-93b6-42fb-a723-060109b51b1b.png)

**System details and installed software (please provide the following information):**
Windows 10 64-bit Edu
Sandboxie-Plus 0.9.2
Latest Chrome

**Additional context**
Has been happening for months now, so it's not a new problem with 0.9.2

**Sandboxie configuration**
Should happen with any config that has dropped rights + Chrome running in it. If not, ping me and I will add my config.

**Comment by isaak654** [comment] 2021-08-08 03:40
Only Chrome, not Edge? In my setup I use Chrome portable from PortableApps and I can't reproduce it.

**Comment by DavidXanatos** [comment] 2021-08-08 06:56
the thing is that BITS seams to be broken since a few w10 releases as its using some parts of WMI which is blocked in sandboxie, it may be best to just disable bits for now.

**Comment by isaak654** [comment] 2021-10-03 20:36
For the time being, I would suggest the following workaround.

Assuming you're on the main Sandboxie Plus window and you've closed any running program in the sandbox:
1) Go to Options menu -> Edit ini file -> confirm yes
2) Add `ClosedClsid={4991D34B-80A1-4291-83B6-3328366B9097}` below `[DefaultBox]`
3) Save the ini file and close it

**Closed** 2021-12-07 09:25 UTC
Labels: Known Issue, Status: Fixed in Next Build, Workaround, COM Interface

**Comment by isaak654** [comment] 2022-12-16 20:08
#1580
