### ISSUE TITLE
Classic Sandboxie v5.46.1

### ISSUE THREAD

**Issue by BilleBarrett** [sandboxie-plus/Sandboxie#347] opened 2021-01-08 18:35 UTC
I am gettting these errors when I 1st start Chrome by click on a link in my outlook email
SBIE2101 Object name not found: \Device\QWAVEdrv, error CreateFile (C0000022) access=0012019F initialized=1
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
SBIE2314 Canceling process chrome.exe [12448 / 7]
Can some one guide me as to why I'm getting them

**Comment by mm36** [comment] 2021-01-09 05:09
Similar problem here.

When Chrome starts the errors occur, but it still works normally.

SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1
SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1
SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1

System: Windows 10 x64 20H2 19042.685 traditional Chinese
Version: Sandboxie 5.46.1 x64

**Comment by NewKidOnTheBlock** [comment] 2021-01-09 10:59
I'm using SB classic 5.46.1 and Chrome Portable (https://portableapps.com/apps/internet/google_chrome_portable) exlusively in a sandbox whenever I need a second browser.
Works alright.

**Comment by DavidXanatos** [comment] 2021-01-09 13:31
> 
> 
> Similar problem here.
> 
> When Chrome starts the errors occur, but it still works normally.
> 
> SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1
> SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1
> SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1
> 
> System: Windows 10 x64 20H2 19042.685 traditional Chinese
> Version: Sandboxie 5.46.1 x64

did you change any settings from the default? I cant reproduce this issue

**Comment by mm36** [comment] 2021-01-09 22:50
Yes.

Resource Access/File Access/Full Access: Add D:\Download\

**Comment by typpos** [comment] 2021-01-10 01:04
v5.46.1

I get exactly the same errors when I start Chrome via Sandboxie > (sandbox) > Context Menu > Run Sandboxed > Web Browser:

> SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1
> SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1
> SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1

I think they might relate to Chrome Extensions and/or if the user is logged in with Chrome.

Side note: I am also getting an in-Chrome notification "Restore Pages? Chrome didn't shut down correctly" when Chrome is already open outside the sandbox.

**Comment by isaak654** [comment] 2021-01-10 15:41
> Side note: I am also getting an in-Chrome notification "Restore Pages? Chrome didn't shut down correctly" when Chrome is already open outside the sandbox.

This happens only when you terminate all programs from Sandboxie, not when you close Chrome from its window.
If you are in the first case, Chrome is right when it says that it didn't close correctly.

**Comment by typpos** [comment] 2021-01-10 19:14
> Normally this happens when you terminate all programs from your sandbox, not when you close Chrome from its window.
> If you are in the first case, Chrome is right when it says that it didn't close correctly.

Unfortunately, no.

Reproduce:
1. Outside sandbox start Chrome
2. Create new (empty) sandbox X
3. Sandoxie > X > (context menu) > Start Web Browser
4. Chrome inside sandbox starts and shows error message "Restore Pages..."

I guess Chrome writes out open tabs while running (outside sandbox) and normally wipes that "I am running" record on normal close. When the sandboxed version starts, it sees that record.

**Comment by DavidXanatos** [comment] 2021-01-12 08:49
SBIE2101  should be fixed in 0.5.4c

**Closed by DavidXanatos** 2021-01-12 08:49 UTC
