### ISSUE TITLE
'Show Templates' button in Sandboxie Plus should not refresh the list when there is no template to show

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#621] opened 2021-02-28 02:58 UTC
Sandboxie Plus 0.7.1
'Show Templates' button in Sandbox options ->Forced Programs doesn't show anything when I press it.
And if you try to add any folder in the Forced Programs list, that button will simply empty the list (as it was a 'clear list' button, but it's not).

**Comment by DavidXanatos** [comment] 2021-02-28 07:31
Template not showing anythign is probably caused by there nothign to be shown, i.e. you have no templates configured that would have any forces entries
If you configure one fo the templates that have forced entries on my system thay are then shown fine.

Also i couldn't reproduce teh add folder issue, i can add folders just fine and no existing entries get removed

**Comment by isaak654** [comment] 2021-02-28 08:37
> And if you try to add any folder in the Forced Programs list, that button will simply empty the list (as it was a 'clear list' button, but > it's not).

> i couldn't reproduce teh add folder issue, i can add folders just fine and no existing entries get removed

Steps:
1) Add a forced folder or a forced program without pressing the apply button after that
2) Press 'Show Templates' button 
3) List of temporary added programs or folders is cleared for good

Not that bad, but it still feels wrong to me because the 'Show Templates' button shouldn't try to reload the list when there is no template to show.

**Comment by DavidXanatos** [comment] 2021-06-12 12:59
will be fixed in the next build

**Closed** 2021-06-14 06:57 UTC
Labels: fixed in next build, known issue
