### ISSUE TITLE
Windows 7 x64:  --> no longer administrable !

### ISSUE THREAD

**Issue by Mike-0815** [sandboxie-plus/Sandboxie#4068] opened 2024-07-09 16:14 UTC
### Describe what you noticed and did

Updated actually to the latest Sandboxie v5.69.3 on Windows 7 x64 and I got the following problem:

It's not posible anymore to administrate Sansboxie ! For example I am not able anymore to create a new Sandbox or change the settings of Program Start / Forced Programs. When I try to change settings, I'll always get an error-message from Sandboxie witch says "Sie sind nicht berechtigt, die Konfiguration im Bereich DefaultBox zu ändern", witch means in english "You are not authorized to change the configuration in the DefaultBox area". As I said, also setting up a new Sandbox or deleting one isn't posible anymore and surely more funcionalities witch I did not test, too.
 
When I switch back to the former v5.68.7 of Sandboxie, everthing works fine again.

### Expected behavior

see description of the problem

### Affected program

Not relevant to my request.

### Download link

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

v5.69.3

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 7 x64

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Kaspersky Antivirus

**Comment by bastik-1001** [comment] 2024-07-09 17:57
This could be a duplicate of #4057, which is a regression, that prevents even users with admin rights to make changes, if the setting is enabled to restrict the users who can make changes to administrators. At least it might be a part of it.

**Comment by Mike-0815** [comment] 2024-07-09 18:19
Yes, it could be a duplicate. Hope David will repair this soon, because it's a major problem, keeping people away from using the latest version of Sandboxie.

**Closed** 2024-07-13 12:47 UTC
Labels: duplicate
