### ISSUE TITLE
RpcSs, DcomLaunch and driver problem

### ISSUE THREAD

**Issue by guilhermeagirardi** [sandboxie-plus/Sandboxie#528] opened 2021-02-04 13:24 UTC
Hello guys!

I have a problem that I don't know how to solve, I already looked for solutions in forums and through the articles on the site, but I was not successful.

See all the errors as shown in the image below:
![image](https://user-images.githubusercontent.com/2306117/106897986-66df2f00-66d2-11eb-9e32-e3edea55cb45.png)

My .ini file:
```
Enabled=y
ConfigLevel=8
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=SkipHook
Template=FileCppy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
BlockDrivers=n
OpenKeyPath=HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services
OpenFilePath=C:\Program Files\Eltima Software\Serial Port Monitor\SPSniff.sys
```

The software is not working in sandboxie.

Can someone help me?

**Comment by hg421** [comment] 2021-02-04 18:50
I don't know about the Rpc errors, but if the software requires loading a kernel mode driver, then it will not work under Sandboxie anyway. Sandboxie does not allow loading drivers because that would be effectively impossible to sandbox

**Comment by DavidXanatos** [comment] 2021-02-08 13:22
> 
> 
> I don't know about the Rpc errors, but if the software requires loading a kernel mode driver, then it will not work under Sandboxie anyway. Sandboxie does not allow loading drivers because that would be effectively impossible to sandbox

yes that's how it is.

so I think I can close this issue as its intended behavior.

**Closed by DavidXanatos** 2021-02-08 13:22 UTC
