### ISSUE TITLE
Outdated download links using Check for Updates option.

### ISSUE THREAD

**Issue by nightkall** [sandboxie-plus/Sandboxie#1705] opened 2022-03-18 12:24 UTC
### What happened?

If you use Check for Updates it says there is a new version 1.0.13, but in the [downloads page](https://sandboxie-plus.com/downloads/) the version is 1.0.10. In [Github releases](https://github.com/sandboxie-plus/Sandboxie/releases) is okay.

Outdated download links:
https://sandboxie-plus.com/downloads/

### To Reproduce

1. Check for Updates.
2. Yes
3. No

### Expected behavior

Download last version.

### What is your Windows edition and version?

Windows 10 21H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

1.0.10

### In which sandbox type you have this problem?

Not relevant to my request.

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by isaak654** [comment] 2022-03-18 15:45
Duplicate of #1682

**Closed** 2022-03-26 15:38 UTC
Labels: duplicate
