### ISSUE TITLE
issue: can't finish installing Libreoffice 7.2.7 in Sandboxie plus 1.2.8b.  

### ISSUE THREAD

**Issue by giovicario** [sandboxie-plus/Sandboxie#2119] opened 2022-08-11 05:41 UTC
### Describe what you noticed and did

issue: can't finish installing Libreoffice 7.2.7 in Sandboxie plus 1.2.8b.  installation interrupted. 
direct installation outside sandboxie fine.

### How often did you encounter it so far?

everytime

### Affected program

Libreoffice 7.2.7

### Download link

https://www.libreoffice.org/

### Where is the program located?

I tried to install it only inside a sandbox, but I wasn't able to achieve it.

### Expected behavior

fix it

### What is your Windows edition and version?

win10 x64

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

microsoft defender

### What version of Sandboxie are you running?

1.2.8b

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by offhub** [comment] 2022-08-11 09:16
I cannot reproduce the issue.



https://user-images.githubusercontent.com/6871698/184101919-f32e060b-4eb5-4521-9f81-b028f6ccbe24.mp4

**Comment by giovicario** [comment] 2022-08-11 15:11
thanks for your reply. it reports "Error 1719". I get to know It is the MSI server interface issue.

**Comment by DavidXanatos** [comment] 2022-08-11 15:46
try enabling extra permsisions for the msi installer in the box options -> general -> security

**Comment by DavidXanatos** [comment] 2022-09-01 20:17
since this seams to work for otehrs me included I'll close this now

**Closed by DavidXanatos** 2022-09-01 20:17 UTC
Labels: more info needed
