### ISSUE TITLE
Bug: not works Emulate Admin Rights in v0.7.1

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [sandboxie-plus/Sandboxie#625] opened 2021-02-28 14:48 UTC
```
SBIE2217 Request to run as Administrator was denied due to dropped rights
SBIE2219 Request was issued by program explorer.exe
```
```
[Test]

Enabled=y
ConfigLevel=8
AutoRecover=n
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#0000ff,ttl,6
BorderColor=#00FFFF,ttl
Template=SkipHook
Template=FileCppy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
DropAdminRights=y
ClosePrintSpooler=y
OpenSmartCard=n
BoxNameTitle=-
BlockNetParam=y
OpenPrintSpooler=n
AllowSpoolerPrintToFile=n
CopyLimitKb=81920
CopyLimitSilent=n
NeverDelete=y
AutoDelete=n
FakeAdminRights=y
AllowRawDiskRead=n
NotifyDirectDiskAccess=n
```
![emulaterights](https://user-images.githubusercontent.com/4449851/109422469-b3c1d700-79ec-11eb-912c-9c86ecf507c3.png)

**Comment by DavidXanatos** [comment] 2021-02-28 15:31
why would explorer want to run as admin?

**Comment by 0x4E69676874466F78** [comment] 2021-02-28 18:18
@DavidXanatos This is not an explorer, it is setup.exe that runs through the explorer (I originally run via cmd with the same errors)

**Comment by 0x4E69676874466F78** [comment] 2021-02-28 19:25
Also, exe stored in sandbox data path (Sandbox\name\\drive\C\setup.exe)

**Comment by DavidXanatos** [comment] 2021-02-28 19:25
hmm... for me that worked, but i may haven't covered all possible calls that needs faking, can you post a link to that setup exe

**Comment by 0x4E69676874466F78** [comment] 2021-02-28 19:29
@DavidXanatos I posted a comment above, have you tried run inside the sandbox? 
I tried other exe the result is the same. 
Ok, I will look for something publicly available.

**Comment by 0x4E69676874466F78** [comment] 2021-02-28 19:38
@DavidXanatos https://www.r-undelete.com/downloads/RUndelete6.exe
Place in Sandbox\name\drive\C\
Run explorer in SandMan context menu and run RUndelete6.exe in explorer window.
Extrainfo: I run SandMan in portable mode from other limited user.

**Comment by DavidXanatos** [comment] 2021-03-01 11:08
I can not reproduce the issue in my system with that preset it does not ask for uac elevation and starts the installers from the sandboxed explorer just fine.
May be try the upcomming version it has a few more improvements in that regard

**Comment by DavidXanatos** [comment] 2021-06-07 18:00
since thre is no more feadback I'll close this for now

**Closed by DavidXanatos** 2021-06-07 18:00 UTC
