### ISSUE TITLE
Fallout 76 Microsoft version cannot use Sandboxie

### ISSUE THREAD

**Issue by cashmankey** [sandboxie-plus/Sandboxie#2473] opened 2022-11-18 15:55 UTC
### Describe what you noticed and did

I bought two Microsoft versions of Fallout 76 , Fallout 76 have Two opening methods , Fallout 76.lnk(UWP application?) or Project76_GamePass.exe 

Running Fallout 76.lnk will show that it is not a valid win32 application
Running Project76_GamePass.exe  will show you don't have permission to open this file  (Perhaps it is because it has been troublesome to obtain permissions for UWP applications?)
![Sandboxie](https://user-images.githubusercontent.com/58972178/202744079-ce8cef38-2dcf-4e85-b907-aa61907839ec.png)

### Affected program

Sandboxie-plus

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Use Sandboxie to open two Microsoft versions of Fallout 76

### What is your Windows edition and version?

Windows 10 Pro 22H2

### In which Windows account you have this problem?

I use the built-in Administrator with Admin Approval Mode turned on.

### Please mention any installed security software

No antivirus software installed , Windows Defender closure.

### What version of Sandboxie are you running?

Sandboxie-Plus v1.4.2

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression?

no

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment] 2022-11-18 16:02
Duplicate of #19 and #2318

**Closed** 2022-11-22 13:30 UTC
Labels: duplicate, UWP, incompatibility
