### ISSUE TITLE
Wechat won't start

### ISSUE THREAD

**Issue by mio-19** [sandboxie-plus/Sandboxie#2716] opened 2023-02-24 12:04 UTC
### Describe what you noticed and did

1. Install wechat 3.9.0 in a sandbox
2. Open it

### Affected program

Wechat

### Download link

https://pc.weixin.qq.com/?lang=en_US

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

.

### What is your Windows edition and version?

Windows 11 25300

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Huorong

### What version of Sandboxie are you running?

1.7.2 64 bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by isaak654** [comment] 2023-02-24 12:39
Duplicate of #2674

**Closed by isaak654** 2023-02-24 12:39 UTC
Labels: Confirmation pending
