### ISSUE TITLE
Explorer.exe still not working with emulate admin sandbox

### ISSUE THREAD

**Issue by NRicode** [sandboxie-plus/Sandboxie#3549] opened 2024-01-06 07:52 UTC
### Describe what you noticed and did

1. Create yellow sandbox
2. set preset to "emulate admin rights"
3. right click on it, open explorer
4. explorer crashes instantly

I don't think crash dump is needed here as I'm pretty sure this is reproducible for all users with the current 12.6 version. But let me know if it's really needed

### How often did you encounter it so far?

-

### Affected program

-

### Download link

-

### Where is the program located?

Not relevant to my request.

### Expected behavior

-

### What is your Windows edition and version?

windows 11 pro

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

-

### What version of Sandboxie are you running?

12.6 latest version

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

yes, on the previous version, "drop admin rights" and "emulate admin rights" will both crash, in this 12.6 version, only "emulate admin rights" make explorer.exe crash

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

-

### Crash dump

-

### Trace log

-

### Sandboxie.ini configuration

```shell
Enabled=y
BorderColor=#02f6f6,on,6
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoDelete=y
BlockNetworkFiles=y
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
DropAdminRights=y
FakeAdminRights=y
```

**Comment by offhub** [comment] 2024-01-06 08:10
Duplicate of #3516

**Closed** 2024-01-06 08:11 UTC
Labels: duplicate, Win 11, explorer.exe
