### ISSUE TITLE
WindowsApps open failed in the Sandboxie-Plus-x64-v1.6.2.exe

### ISSUE THREAD

**Issue by GitHubAmos** [sandboxie-plus/Sandboxie#2578] opened 2022-12-30 01:33 UTC
### Describe what you noticed and did
1. Install Sandboxie Plus
2. Open Sandboxie Plus
3. Try to run anything

* error info
![image](https://user-images.githubusercontent.com/40637045/210027395-5d98624c-4766-4d10-8e70-f87b6c06cac6.png)

* On the Win10 case:
run failed both inside and outside the sandbox
* On the Win11 
run failed inside the sandbox，run success outside the sandbox

### How often did you encounter it so far?

every time

### Affected program

Sandboxie-Plus-x64-v1.6.2.exe

### Download link

C:\Program Files\WindowsApps\Microsoft.Windows.Photos_2019.18114.19418.0_x64__8wekyb3d8bbwe\Microsoft.Photos.exe
C:\Program Files\WindowsApps\Microsoft.Paint_11.2208.6.0_x64__8wekyb3d8bbwe\PaintApp\mspaint.exe

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Expected it normal running in the Sandboxie-Plus

### What is your Windows edition and version?

Win10 Enterprise 1909 64-bit
Win11 Enterprise 21H2 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus-x64-v1.6.2.exe

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

Sandboxie-Plus-x64-v1.0.9.exe

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by offhub** [comment] 2022-12-30 09:16
It is a known issue. Duplicate of #19

**Closed** 2023-01-24 23:38 UTC
Labels: duplicate, Known issue, UWP, incompatibility

**Comment by isaak654** [comment] 2023-01-24 23:43
At the moment there is no timeline for when this is going to be fixed.
