### ISSUE TITLE
"Could not hook" and "DLL initialization failed"

### ISSUE THREAD

**Issue by jedimasterspaz** [sandboxie-plus/Sandboxie#166] opened 2020-10-24 22:47 UTC
I got the following errors while opening Google Calendar in Sanboxie while running Procmon.
I've included Procmon output filtered by removing successful events and anything but Chrome, Sandboxie, Explorer and the basic Windows system files. 

[Logfile.xlsx](https://github.com/sandboxie-plus/Sandboxie/files/5433885/Logfile.xlsx)

Here's the errors:
SBIE2303 Could not hook CoGetObject (33, 1655)
SBIE2303 Could not hook RegisterDragDrop (33, 1655)
SBIE2318 DLL initialization failed for 'ole32.dll'
SBIE2303 Could not hook CM_Add_Driver_PackageW (33, 1655)
SBIE2318 DLL initialization failed for 'cfgmgr32.dll'
SBIE2303 Could not hook SetCurrentProcessExplicitAppUserModelID (33, 1655)

**Comment by DavidXanatos** [comment] 2020-10-25 12:49
Are you running some other security software that may interfear with sandboxie?

**Comment by jedimasterspaz** [comment] 2020-10-25 16:38
Just Windows Defender.

**Comment by DavidXanatos** [comment] 2020-10-25 18:17
Ah that may be chrome related its know that chrome sometimes causes a few error messages, if aside of the messages everything works than i would say just hide them

**Comment by jedimasterspaz** [comment] 2020-10-25 19:13
There's no other running anti-malware.  I disabled Defender and excluded the Sandboxie directory.
I hid the errors.

**Comment by isaak654** [comment] 2020-10-25 22:46
Perhaps it would be better to remove those errors by default without user intervention.

**Comment by DavidXanatos** [comment] 2021-01-02 13:02
@isaak654 The issue was caused by a mitigation policy chrome has set which has interfered with the hooking mechanism, this issue will be fixed in the nextbuild

**Closed** 2021-01-07 19:25 UTC
Labels: fixed in next build
