### ISSUE TITLE
Drag and drop works from ClosedFilePath

### ISSUE THREAD

**Issue by mysteriously** [sandboxie-plus/Sandboxie#2039] opened 2022-07-19 08:24 UTC
### Describe what you noticed and did

Drag and drop works from ClosedFilePath (unsandboxed explorer). In my case:
`ClosedFilePath=%SystemDrive%\Users\*\Desktop\`

When I try to manually select a file to upload from sandboxed explorer and browse to Desktop path, it gives me permission denied as expected

![test](https://user-images.githubusercontent.com/17072890/179703439-39fee351-ca9d-4d74-ae50-c25c596b2818.png)
.

### How often did you encounter it so far?

Always

### Affected program

Firefox 91.11.0esr x64

### Download link

https://www.mozilla.org/en-US/firefox/all/#product-desktop-esr

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

Access denied error

### What is your Windows edition and version?

Windows 11 (version 21H2)

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Eset Endpoint Security 9.0.2046.0

### What version of Sandboxie are you running?

1.1.3

### Is it a new installation of Sandboxie?

I have been in the same version for a while now.

### In which sandbox type you have this problem?

In a Hardened sandbox (red sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

Forwarding desktop path to other path in main sandbox. Irrelevant, as with clean sandbox without forwarding the issue is still present.

### Sandboxie.ini configuration

```shell
[GlobalSettings]
ClosedFilePath=%SystemDrive%\Users\*\Desktop\
```

**Comment by RandomGOTI** [comment] 2022-07-19 10:01
### Just some testing
`ClosedFilePath=%SystemDrive%\Users\*\Desktop\`
With a editor and text file , the sandboxed editor was able to load the document , if i try to change and save , it will create an empty file, if the document was in recent files list and opened that way. ( Trying to open it via open dialog works as intended , location not available)
Drag n drop from unsanboxed explorer to sandboxed editor not doing anything

`ClosedFilePath=%Desktop%\`
If i try to load from recent files it gave an error that the file does not exist, same with the above drag and droping did nothing ✔

`WriteFilePath=%SystemDrive%\Users\*\Desktop\`
( ͡° ͜◯ ͡°) ... same as closed, it can load the txt from file -> recent
drag and drop did nothing

`WriteFilePath=%Desktop%\`
Can't load the file from recent menu and also does nothing on drag drop ✔

Windows 7 Ultimate SP1 x64
Plus 1.2.3 x64

**Comment by DavidXanatos** [comment] 2022-07-22 21:00
You have to use
ClosedFilePath=%SystemDrive%\Users\*\Desktop\*
this way it works, i need to check though if that was always the behavioure or if the * should be auto appended

**Comment by DavidXanatos** [comment] 2022-07-22 21:05
Ok it seams to me that sandboxie only autp appends an * to a provided path if the path does not contain any * to begin with, therefor the behavioure is expected and was always like this.

Now the behavior does not seam to be intuitive to me, hence we may look into changing the behavioure?

**Comment by DavidXanatos** [comment] 2022-07-23 08:03
The next build of sandboxie will display the * when apropriate to illustrate in the UI what behavioure the driver will apply

**Comment by isaak654** [comment] 2022-07-26 12:39
#2061

**Comment by DavidXanatos** [comment] 2022-07-26 17:38
correction change will be in 1.3.0

**Closed** 2022-07-31 17:50 UTC
Labels: Feature request, Confirmation pending, fixed in next build
