### ISSUE TITLE
 Sandboxie-Plus-x64-v1.15.1.exe  does not install

### ISSUE THREAD

**Issue by CaliSunUSA** [sandboxie-plus/Sandboxie#4343] opened 2024-10-30 03:19 UTC
### Describe what you noticed and did

When trying to install Sandboxie-Plus-x64-v1.15.1.exe 
I see these two screens
<img width="288" alt="1 15 1 issue 1" src="https://github.com/user-attachments/assets/5f89bde1-76de-4b28-9310-558002e2a8b1">
<img width="448" alt="1 15 1 issue 2" src="https://github.com/user-attachments/assets/e7787761-7e93-4c8f-a66c-52f5b7b64403">

### How often did you encounter it so far?

today

### Expected behavior

installs new version

### Affected program

windows 10 Pro

### Download link

NA

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

 Sandboxie-Plus-x64-v1.15.0

### Is it a new installation of Sandboxie?

I recently upgraded it from an older version than 1.5.3 / 5.60.3.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Pro 64bit

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Avast

**Comment by ccchan234** [comment] 2024-10-30 03:39
same here, i can confirm.

recently my 1.14.10 crashed with chromes.

wanna upgrade to try but cant upgrade to this.

With traditional yellow sandboxes, any app can steal all your data,
i prefer using DataProtection blue boxes now.

wish the problems can be solved. thx

**Comment by isaak654** [comment] 2024-10-30 08:12
Duplicate of #2643

**Comment by cisko99za** [comment] 2024-10-30 09:14
where did you find 1.15.1 version if from Releases page there is only a link to latest 1.14.10 version ?

**Comment by offhub** [comment] 2024-10-30 09:24
@cisko99za You can view the pre-release versions by entering the releases page: [Sandboxie Releases](https://github.com/sandboxie-plus/Sandboxie/releases).

**Comment by CaliSunUSA** [comment] 2024-11-08 22:48
I don't think it is related to [#2643](https://github.com/sandboxie-plus/Sandboxie/issues/2643)
If the file is unsigned, Avast message only says that "Suspicious file detected" and proceeds to scan it. Afterwards it says that file is determined to be safe and lets you proceed.
This time it actually identified Malware by name and prevented me from proceeding. It could be False Positive, but I believe unrelated to "unsigned" file.

Below screenshots are from previously reported issue with Unsigned file, which are different from 1st screenshot in this incident.

![2024-05-17 11_42_31-Window](https://github.com/user-attachments/assets/11203fc0-9730-43e6-83f6-3312ccc130b7)
![2024-05-17 11_42_52-Window](https://github.com/user-attachments/assets/b94a02c0-59b0-4dd9-b050-0170699a72cb)

**Comment by offhub** [comment] 2024-11-09 08:52
One of the reasons for this warning is the update of the installer version #4020,  which is why the temporary file's contents differ significantly from previous versions. I believe that after some time, antivirus software will adapt to this change and stop triggering the warning. If the installer's temporary file had been signed, would antivirus softwares still trigger the same warning? We're not sure, but with the release of Sandboxie Plus v1.15.2, we'll have the answer.

**Comment by offhub** [comment] 2024-11-09 08:56
One of the reasons for this warning is the update of the installer version #4020,  which is why the temporary file's contents differ significantly from previous versions. I believe that after some time, antivirus software will adapt to this change and stop triggering the warning. If the installer's temporary file had been signed, would antivirus software still trigger the same warning? We're not sure, but with the release of Sandboxie Plus v1.15.2, we'll have the answer.

**Closed** 2024-11-18 21:14 UTC
Labels: Duplicate, False Positive

**Comment by CaliSunUSA** [comment] 2024-11-18 22:01
Just installed Sandboxie Plus v1.15.2, everything went smooth, no complains from Avast :)
