### ISSUE TITLE
5.45.0 Immediate recovery showing only one recoverable item & slow opening of save file.

### ISSUE THREAD

**Issue by Komnenoi** [sandboxie-plus/Sandboxie#224] opened 2020-12-11 10:52 UTC
Greetings,

I upgraded from the last official Sandboxie version 4-533-3 to 4-v5.45.0 as it received signed drivers (Windows detected it as malware previously and removed it automaticly) and noticed now that for some reason Immediate Recovery does not seem to function correctly.

When downloading files, it seems to only show the first downloaded item as recoverable. Anything else that is downloaded afterwards is not added to the Immediate recovery pop-up window regarding nor comes up afterwards in a new Immediate recovery window if the item in the first window is recovered prior to later ones finishing their download.

The issue is present on both of the latest versions of Chrome and Firefox. I have uninstalled and then reinstalled 4-v5,45,0 if that might have helped in resolving the issue which it has not unfortunately.

Secondary issue which is semi-related to downloading items is that whenever I right click and item to save it the computer (image for example) it can take several seconds to actually open the windows window to said folder where I can choose to save the item. This issue has been present for several sandboxie versions.

Included as attachments. Picture of Immediate recovery window while having several items downloaded and a second picture of everything that can actually be recovered at the same time from Quick recovery

![Quick recovery](https://user-images.githubusercontent.com/35752784/101894949-903a7d80-3baf-11eb-9510-d5a25280bf62.png)

![Quick recovery 2](https://user-images.githubusercontent.com/35752784/101894955-929cd780-3baf-11eb-802e-a93c6fd704f4.png)

Edit: Just something to hopefully help in figuring out the problem. Once I have used Immediate recovery to recover for example File 1 (While Files 2 & 3 have been downloaded but haven't shown up in the Immediate recovery window) and afterwards download a new file, the new file pops up fine in its own Immediate recovery window yet files which have been downloaded prior to that won't show up in the new Immediate recovery window even though they have not been recovered. So Sandboxie does not seem to have issues detecting files which have been downloaded at least while an Immediate recovery window is not present. So perhaps something to do with new files not being detected while its up or issues updating the Immediate recovery window itself with new files.

**Comment by bjm234** [comment] 2020-12-11 20:38
FWIW ~ I think that's how Immediate Recovery works vs Quick Recovery. 
Meaning Immediate Recovery offers the first download available for recovery.
And Quick Recovery offers all downloads available for recovery.  
That's how Immediate Recovery vs Quick Recovery works for me.

**Comment by Komnenoi** [comment] 2020-12-12 00:32
> FWIW ~ I think that's how Immediate Recovery works vs Quick Recovery.
> Meaning Immediate Recovery offers the download available for immediate recovery.
> And Quick Recovery offers downloads available for recovery.
> That's how Immediate Recovery vs Quick Recovery works for me.
> My preference is Quick Recovery.
> Q: Did Immediate Recovery used to offer all downloads available for immediate recovery?

Thanks for the reply. Immediate and Quick recovery are two different things so thank you for mentioning that, fixed the description and title.

If I had Picture 1.png downloaded and say downloaded Picture 2.png & Picture 3.png afterwards, then #2 and 3 would be added automatically to the Immediate recovery window if it still was open (with Picture 1.png in this example).

So the issues is Immediate recovery not showing up all files that can be recovered at any time if said files are downloaded to the regular Immediate/Quick recovery folders (Desktop, Downloads etc)

**Comment by bjm234** [comment] 2020-12-12 01:26
Okay, so Immediate Recovery used to offer all downloads eligible for immediate recovery? 
Not just to use your example: Picture 1.png.  
So, Immediate Recovery used to offer for example: Pic1.png, Pic2.png & Pic3.png.  
-
Yes, in my just now test.  Immediate Recovery only offered for example: Pic1.png.
While Quick Recovery offered all downloads for example: Pic1.png, Pic2.png & Pic3.png. 
Thanks

**Comment by Komnenoi** [comment] 2020-12-15 01:08
I noticed some pretty weird behavior also regarding Sandboxie's recovery.

The issue described above still exists, but also noticed that files which were **not** asked to be recovered (Hidden for some reason still in Quick recovery) were recovered with Immediate Recovery.

This might let rogue files out from the sandbox at worst which does in a way defeat the purpose of the software. Note: I have not been able to duplicate the issue. But thought its worth mentioning.

Another issue that I noticed that Sandboxie sandbox seems to balloon for some strange reason. Just from opening a sandboxed browser, savings 2 files while in the download window while during it moving from my downloads folder (which has files) to my desktop (which also has files) the Sandboxie went up to above 1 Gb in size. Previously this has not happened while browsing around in a sandboxed version of the file explorer.

**Comment by Komnenoi** [comment] 2020-12-19 14:10
I Installed SandboxieInstall64-v5.44.1 and did the same test with 2 pictures and the bug was not present.

This would indicate that something that was changed between SandboxieInstall64-v5.44.1& SandboxieInstall64-v5.45.0 has caused the bug to appear.

**Comment by DavidXanatos** [comment] 2020-12-19 19:55
I can confirm the failed to recover subsequent files issue, I'm investigating it right now.

**Comment by DavidXanatos** [comment] 2020-12-19 20:02
I have found the issue and fixed it in the next build quick recovery in the classical ui should work fine again

**Comment by grnassar** [comment] 2020-12-22 22:30
OP mentions not just the quick recovery but also the slow load times for Save As (aka system dialog) windows.  That part seems likely to be a duplicate of #69, #109, #193

**Closed** 2020-12-23 12:36 UTC
Labels: fixed in next build, known issue, under investigation
