### ISSUE TITLE
Run Outside Sandboxie stopped working

### ISSUE THREAD

**Issue by HikariWS** [sandboxie-plus/Sandboxie#614] opened 2021-02-24 20:36 UTC
IDK how long it stopped. I have some shortcuts that execute Start.exe to make some app run inside some sandbox. I use that so that these apps' profiles aren't changed and are restored to host's version every time the sandbox content is deleted.

When I need to change anything on host's version, I right click on the shortcut and choose to run it outside Sandboxie, then the app does that. I make the editions I need and close it ASAP, then I delete the sandbox content and execute it back inside it.

I just tried to do that and it failed. There's no error message, the app just executes inside the sandbox even though I had selected to run it outside any.

**Comment by isaak654** [comment] 2021-02-26 22:26
>  I right click on the shortcut and choose to run it outside Sandboxie. There's no error message, the app just executes inside the sandbox even though I had selected to run it outside any.

I have the same problem with Sandboxie Classic 5.48.5 x64 and Windows 10 2004 x64.
I can reproduce it with this shortcut:
`"C:\Program Files\Sandboxie\Start.exe" /box:DefaultBox "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"`

**Comment by DavidXanatos** [comment] 2021-06-07 18:16
Did that ever worked for em itdoes not even work with the last sophos version

**Comment by isaak654** [comment] 2021-06-07 19:01
> 
> Did that ever worked for em itdoes not even work with the last sophos version

Probably it doesn't work since 2017, but I can't be sure.

According to this old post from tzuk, Run Outside Sandbox was surely working in version 4.01.02:
https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopicfbce-3fbce.html

Lucky for you, you might download it from here and test it accordingly:
https://www.afterdawn.com/software/security/misc_security_tools/sandboxie_64-bit.cfm/4_01_02_beta

**Comment by isaak654** [comment] 2021-07-04 03:11
@DavidXanatos 
I just wanted to add that I tried to reproduce this issue with Sophos build 5.33.6 and latest Classic build 5.50.2 on a Windows 8.1 system, but I couldn't. So it looks like a Windows 10 issue.

**Comment by isaak654** [comment] 2021-07-04 03:54
@DavidXanatos
After a lot of attempts, I can reproduce it even with Sandboxie (64-bit) v4.05.12... basically it happens only with specific sandboxed shortcuts like the one in the second post. I couldn't try the 4.01.02 beta which is incompatible with my Windows 8.1 system.

**Comment by DavidXanatos** [comment] 2021-08-07 19:39
that should be fixed in the 0.9.2 build can you please test and confirm

**Comment by isaak654** [comment] 2021-08-07 19:50
> 
> 
> that should be fixed in the 0.9.2 build can you please test and confirm

Nope, I think it's another issue with 0.9.2 (here I tried two different shortcuts):
![immagine](https://user-images.githubusercontent.com/12372772/128612241-7c88f6f1-74e7-4374-ba70-6434d7ec612a.png)
![immagine](https://user-images.githubusercontent.com/12372772/128612329-fc88c4e0-58df-4434-965d-56488e0ef6cb.png)

**Comment by isaak654** [comment] 2021-08-07 19:56
Those shortcuts are fine if I run them with a double click... so the problem is related to the right-click -> Run Sandboxed feature on 0.9.2.

**Comment by DavidXanatos** [comment] 2021-08-07 21:19
ok so the status, the thing fixed was an otehr dfp bug...
version 0.9.3 will have a feature to make this behavioure work but it wil not work with classic.
Basically the new UI checks if the provided link is to a start.exe and if so drops the start exe part selects teh preset box and uses the normal run sandboxed code path as if the user woudl have clicked on a link to the target and not to a start.exe + target

**Comment by isaak654** [comment] 2021-08-07 21:50
David just added a simple fix for Classic after writing the previous post, so the Run unsandboxed should also work in the next Classic build.

**Closed** 2021-08-08 22:30 UTC
Labels: to investigate, Known issue, added in next build, Issue reproduced
