### ISSUE TITLE
Can't Screenshot Copy-protected Video (Google Chrome)

### ISSUE THREAD

**Issue by Peekofwar** [sandboxie-plus/Sandboxie#2179] opened 2022-08-23 22:39 UTC
### Describe what you noticed and did

Previously, I was able to screenshot/capture copy-protected video playing inside of Sandboxie from the YouTube video player, however for some reason, it no longer does this.

I get this error on both Sandboxie Classic and Plus:
```
chrome.exe (1504): SBIE2203 Failed to communicate with Sandboxie Service:  connect C0000022
chrome.exe (1504): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_0000000C; MsgId: 14 - chrome.exe [C0000080]
chrome.exe (1504): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_0000000C; MsgId: 14 - chrome.exe [C0000080]
chrome.exe (1504): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_0000000C; MsgId: 14 - chrome.exe [C0000080]
chrome.exe (1504): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_0000000C; MsgId: 14 - chrome.exe [C0000080]
chrome.exe (1504): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_0000000C; MsgId: 14 - chrome.exe [C0000080]
```

https://user-images.githubusercontent.com/10189526/186278944-7ba64c9b-dea4-473c-8170-a0944072e3d7.mp4

I got the same issue in Microsoft Edge:
```
msedge.exe (18032): SBIE2203 Failed to communicate with Sandboxie Service:  connect C0000022
msedge.exe (18032): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_0000000C; MsgId: 14 - msedge.exe [C0000080]
msedge.exe (18032): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_0000000C; MsgId: 14 - msedge.exe [C0000080]
msedge.exe (18032): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_0000000C; MsgId: 14 - msedge.exe [C0000080]
msedge.exe (18032): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_0000000C; MsgId: 14 - msedge.exe [C0000080]
msedge.exe (18032): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_0000000C; MsgId: 14 - msedge.exe [C0000080]
```

### How often did you encounter it so far?

Every time the video starts playing

### Affected program

Google Chrome Version 104.0.5112.102 (Official Build) (64-bit)

### Download link

Not relevant.

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

I expected Sandboxie to allow me to bypass the copy-protection measures that YouTube employs that prevent me from taking screenshots when I for example, see a funny freeze-frame when I pause.

### What is your Windows edition and version?

Microsoft Windows 10 Version 21H1 (OS Build 19043.1889)

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

5.57.7 (64-Bit)

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

No changes.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

TemplateReject=Edge_Win11Fix
TemplateReject=RpcPortBindings
TemplateReject=7zipShellEx
TemplateReject=WindowsRasMan
TemplateReject=WindowsLive
TemplateReject=WacomTablet
TemplateReject=OfficeLicensing

[DefaultBox]

ConfigLevel=9
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#02f6f6,ttl,6
Enabled=y
CopyLimitKb=159756
BoxNameTitle=n

[UserSettings_258403C5]

SbieCtrl_UserName=peekofwar
SbieCtrl_NextUpdateCheck=1661896740
SbieCtrl_WindowCoords=357,425,1650,843
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_HideWindowNotify=n
SbieCtrl_BoxExpandedView=,
SbieCtrl_AutoStartAgent=SandMan.exe


```
```

**Comment by isaak654** [comment] 2022-08-25 22:07
Duplicate of #1611

**Closed** 2023-07-22 09:28 UTC
Labels: duplicate, Confirmation pending

**Comment by Peekofwar** [comment] 2024-08-02 23:07
This is still a problem in Sandboxie Plus... Just updated to the latest x64 release.
