### ISSUE TITLE
Cannot run explorer.exe on emulate admin sandbox

### ISSUE THREAD

**Issue by NRicode** [sandboxie-plus/Sandboxie#3516] opened 2023-12-21 15:15 UTC
### Describe what you noticed and did

I cannot start explorer.exe on my current sandbox, not sure what caused it.
exploerer.exe runs fine on a brand new sandbox

### How often did you encounter it so far?

all the time

### Affected program

explorer.exe

### Download link

-

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

not crash

### What is your Windows edition and version?

windows 11 home

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

ms defender

### What version of Sandboxie are you running?

1.12.5 5.67.4

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

-

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

My sandbox contains existing programs or data.

### Did you previously enable some security policy settings outside Sandboxie?

no

### Crash dump

https://file.io/3tPW7FGVs6LA

### Trace log

no trace log

### Sandboxie.ini configuration

```shell
#
# Sandboxie configuration file
#

[GlobalSettings]
DefaultBox=DefaultBox
FileRootPath=C:\Program Files\Sandboxie-Plus\Sandboxes\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=7zipShellEx
Template=Edge_Fix
Template=OfficeClickToRun
Template=OfficeLicensing
Template=WindowsLive
Template=WindowsRasMan

[UserSettings_087C01BD]
SbieCtrl_AutoStartAgent=SandMan.exe -autorun
BoxGrouping=:DefaultBox

[DefaultBox]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,on,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
SeparateUserFolders=n
DropAdminRights=y
FakeAdminRights=y
BreakoutProcess=msedge.exe
EnableMiniDump=y
```

**Comment by NRicode** [comment] 2023-12-21 15:23
![image](https://github.com/sandboxie-plus/Sandboxie/assets/106366188/4dbb1d65-ab91-4fbe-9f34-ff8cd531e9e3)
Here is the Werfault.exe thing pops up, after it pops up, the explorer.exe just close itself.

**Comment by offhub** [comment] 2023-12-21 20:08
Yes, on Windows 11, Windows Explorer does not work properly or does not open at all.

Can you try `FakeAdminRights=n`

According to my tests, the following two settings cause the crash.

`FakeAdminRights=y`

`SysCallLockDown=y`

**Comment by DavidXanatos** [comment] 2023-12-22 09:42
fix in next build, workaround:
ApproveWinNtSysCall=LoadKeyEx

@NRicode
if other boxes/new boxes work then its had to sday whats broken, you could move parts of teh box content out of the way to find out which file causes your issue

**Comment by offhub** [comment] 2023-12-22 14:40
[Only on Windows 11] Sometimes Windows Explorer crashes when it is closed.

`UsePrivacyMode=n`
1. Run sandboxed Windows Explorer
2. Navigate to `C:\Program Files (x86)\Microsoft\Edge\Application`
3. Run msedge.exe by double clicking
4. Close msedge.exe
5. Close sandboxed Windows Explorer
6. It crashes when closing
```
explorer.exe: SBIE2224 Sandboxed program has crashed: explorer.exe
WerFault.exe: SBIE2112 Object is not accessible: Unnamed object, call ConnectPort (C0000022) access=001F0000 initialized=1
```

**Comment by isaak654** [comment] 2023-12-22 15:04
The video says Sandboxie Plus v1.10.5, which is old, so you probably tried the wrong build.

**Comment by isaak654** [comment] 2023-12-22 15:04
The video says Sandboxie Plus v1.10.5, which is old, so you probably tried a wrong build.

**Comment by isaak654** [comment] 2023-12-22 15:05
The video says Sandboxie Plus v1.10.5, which is old, so you probably tried a wrong version.

**Comment by isaak654** [comment] 2023-12-22 15:08
@offhub The video says Sandboxie Plus v1.10.5, which is old, so you probably tried a wrong version.

**Comment by offhub** [comment] 2023-12-22 15:12
@isaak654 No, I tried older versions to see if there was a regression. The latest CI build has the same problem. (1.10.5, 1.11.4 etc.)

**Comment by DavidXanatos** [comment] 2023-12-22 16:46
hmm... any particular setting to set for me it does not crash in a default yellow box

**Comment by offhub** [comment] 2023-12-22 17:11
@DavidXanatos This may be due to the Windows 11 version difference. It does not crash on closing in Windows 11 version 2428 (october), but it crashes in version 2861 (december).

**Comment by DavidXanatos** [comment] 2023-12-22 18:33
hmm mv vm is insider 23606

**Comment by DavidXanatos** [comment] 2023-12-22 18:35
mmh if this bug is so specific and only appears on close lets wait what the next windows 11 will do before investing more work into it

**Comment by e-t-l** [comment] 2023-12-23 19:52
Not sure if this is the same bug, but I can't get Explorer to launch. It will appear briefly and then close. 
Running Sandboxie-Plus v1.12.3 on Windows 11 Enterprise 23H2 (build 22631)

ini config for sandbox where this occurs:
```
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=10
OpenPipePath=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\*
ApproveWinNtSysCall=LoadKeyEx
```

**Comment by offhub** [comment] 2023-12-23 20:52
Move the ApproveWinntSyscall setting to [GlobalSettings] and then try after reloading the config.

**Comment by NRicode** [comment] 2024-01-03 09:18
@DavidXanatos After the 12.6 release, this issue still persist

**Comment by offhub** [comment] 2024-01-03 09:23
Can you try one of these:

`WriteFilePath=explorer.exe,%ProgramData%\Microsoft\Windows\AppRepository\Packages\Microsoft.UI.Xaml.CBS_*__8wekyb3d8bbwe\machine.pckgdep`

or

`FakeAdminRights=explorer.exe,n`

**Comment by offhub** [comment] 2024-01-05 11:20
> [Only on Windows 11] Sometimes Windows Explorer crashes when it is closed.
> 
> `UsePrivacyMode=n`
> 
>     1. Run sandboxed Windows Explorer
> 
>     2. Navigate to `C:\Program Files (x86)\Microsoft\Edge\Application`
> 
>     3. Run msedge.exe by double clicking
> 
>     4. Close msedge.exe
> 
>     5. Close sandboxed Windows Explorer
> 
>     6. It crashes when closing
> 
> 
> ```
> explorer.exe: SBIE2224 Sandboxed program has crashed: explorer.exe
> WerFault.exe: SBIE2112 Object is not accessible: Unnamed object, call ConnectPort (C0000022) access=001F0000 initialized=1
> ```
> 
> sbie3516wecrsh.mp4

[explorer.exe.6052.dmp.zip](https://github.com/sandboxie-plus/Sandboxie/files/13841362/explorer.exe.6052.dmp.zip)

**Comment by offhub** [comment] 2024-01-06 09:38
As of version 1.12.6,
- [x] SysCallLockDown=y (fixed)
- [ ] FakeAdminRights=y (not fixed)

**Comment by DavidXanatos** [comment] 2024-01-06 17:48
1.12.6 with fix for https://github.com/sandboxie-plus/Sandboxie/issues/3517 seams to also work with FakeAdminRights=y

**Comment by offhub** [comment] 2024-01-08 11:08
I tried with version 1.12.7 (on Windows 11 23H2 HyperV) and it still crashes. It would be better if someone who is not using Windows 11 in a virtual machine could try the following settings and report back.

1. crash?
```
FakeAdminRights=y
```

2. crash?
```
FakeAdminRights=y
NormalFilePath=%ProgramData%\Microsoft\*
UsePrivacyMode=y
```

3. This was the only configuration that didn't crash or cause navigation problems for me on VM.
```
FakeAdminRights=y
FakeAdminRights=explorer.exe,n
NormalFilePath=%ProgramData%\Microsoft\*
UsePrivacyMode=y
```

**Comment by NRicode** [comment] 2024-01-14 05:31
> I tried with version 1.12.7 (on Windows 11 23H2 HyperV) and it still crashes. It would be better if someone who is not using Windows 11 in a virtual machine could try the following settings and report back.
> 
> 1. crash?
> 
> ```
> FakeAdminRights=y
> ```
> 
> 2. crash?
> 
> ```
> FakeAdminRights=y
> NormalFilePath=%ProgramData%\Microsoft\*
> UsePrivacyMode=y
> ```
> 
> 3. This was the only configuration that didn't crash or cause navigation problems for me on VM.
> 
> ```
> FakeAdminRights=y
> FakeAdminRights=explorer.exe,n
> NormalFilePath=%ProgramData%\Microsoft\*
> UsePrivacyMode=y
> ```

I don't understand what you are trying to do here and I am not sure why this issue is closed as complete, the bug still persist.
VM or not VM it doesn't matter as sandboxie in the end is just a file system filter driver. sandboxie behaviour inside / outside VM should be the same.

1 and 2 crash, ofc the third one won't crash because you turned off fakeadminrights for explorer.exe duh.

**Comment by isaak654** [comment] 2024-01-14 15:38
> I am not sure why this issue is closed as complete

No offense, but it would be correct to ask the person in question instead of involving someone else's quote.

**Comment by isaak654** [comment] 2024-01-14 15:59
> I am not sure why this issue is closed as complete

No offense, it would be correct to ask the person in question instead of involving someone else's quote.

**Comment by isaak654** [comment] 2024-01-16 17:50
> I am not sure why this issue is closed as complete

Despite good will, we are not a structured team, so it would be correct to ask the person in question instead of involving someone else's quote.

**Comment by isaak654** [comment] 2024-01-16 17:53
> I am not sure why this issue is closed as complete

We are not a structured team, so it would be correct to ask the person in question instead of involving someone else's quote.

**Comment by isaak654** [comment] 2024-01-16 17:57
> I am not sure why this issue is closed as complete

Despite having collaborative roles, there is no structured team, so it would be correct to ask the person in question instead of involving someone else's comment.

**Comment by isaak654** [comment] 2024-01-27 20:46
The workaround suggested by @offhub has just been introduced with commit 5e321d4

It will be applied immediately after installing version 1.12.8 / 5.67.8 without any user intervention.

**Closed** 2024-01-31 07:28 UTC
Labels: Confirmation pending, fixed in next build, Workaround, Win 11, crash dump, explorer.exe
