### ISSUE TITLE
Site is not safe (google warning)

### ISSUE THREAD

**Issue by sebadamus** [sandboxie-plus/Sandboxie#854] opened 2021-05-27 07:07 UTC
Hi,

Recently I got this strange message in firefox when opening for the first time in the browser.  Also if you test it with this:
https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fgithub.com%2Fsandboxie-plus%2FSandboxie%2Freleases

Maybe it can be cleared by requesting google?

**Comment by Coverlin** [comment] 2021-05-27 09:41
#847 

Why though? Its a waste of time for a browser built in worthless feature

Check each release separetly to determine how reliable "Google’s Safe Browsing technology " really is.
Even for the releases with the driver that gives false positives #95  , they come back as "No unsafe content found"

example per release check : https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fgithub.com%2Fsandboxie-plus%2FSandboxie%2Freleases%2Ftag%2F0.7.4

Let's see what VT has to say
https://www.virustotal.com/gui/url/0198d25daa5841c0d608e9034fe20a51a08d53337165c5735f8ca053baeecadc/detection
1 security vendor flagged this URL as malicious . I wonder who could that be ... drunk ol' google with bipolar results

VT for 0 7 4 https://www.virustotal.com/gui/url/31d927300a863c6b170b5d04555003a9a46485416afdf9a20f275fbf35c38c21/detection

```
Enhanced protection
Faster, proactive protection against dangerous websites, downloads, and extensions. 
Warns you about password breaches. Requires browsing data to be sent to Google.
```
^ That's a joke except for the last part...

**Comment by Ignas2526** [comment] 2021-05-29 05:57
I just had the same issue in Chrome. A big red warning that this site contains harmful programs. Also, when I downloaded latest installer Sandboxie-Plus-x64-v0.7.4.exe, chrome blocked it. "Sandboxie-Plus-x64-v0.7.4.exe is dangerous, so Chrome had blocked it."

**Comment by sebadamus** [comment] 2021-05-30 05:31
So, there is no way to clean damn google... closing, thanks for your response.

**Comment by SirFireNewt** [comment] 2021-06-07 21:32
Just to bump this with something interesting, it seems to be only `/Sandboxie/releases` that's flagged going to `/Sandboxie/releases/latest` seems to work fine.
perhaps the update prompt in the UI could be changed to the latest tag to get around this

**Comment by DavidXanatos** [comment] 2021-06-08 08:21
good idea I have changed the target url in the update data to https://sandboxie-plus.com/downloads/

**Comment by DavidXanatos** [comment] 2021-06-08 08:26
can please everyone report the detection as false to google

**Comment by DavidXanatos** [comment] 2021-06-12 13:49
seams fixed: https://www.virustotal.com/gui/url/0198d25daa5841c0d608e9034fe20a51a08d53337165c5735f8ca053baeecadc/detection

**Comment by isaak654** [comment] 2021-06-12 14:02
It can still reproduce the warning, despite Virustotal whitelisted the URL.

**Comment by isaak654** [comment] 2021-06-12 14:02
I can still reproduce the warning, despite Virustotal whitelisted the URL.

**Comment by isaak654** [comment] 2021-06-17 11:28
No news yet.. please keep reporting the URL as false positive to Google and Virustotal:
https://github.com/sandboxie-plus/Sandboxie/issues/847#issuecomment-845918141

I'm going to close this duplicate, please go there for updated news about this.

**Closed by isaak654** 2021-06-17 11:28 UTC
Labels: Known issue, duplicate, workaround
