### ISSUE TITLE
Auto close File Recovery dialog when empty

### ISSUE THREAD

**Issue by btbs-github** [sandboxie-plus/Sandboxie#1624] opened 2022-02-13 21:55 UTC
### Is your feature request related to a problem or use case?

When using immediate recovery when a file is downloaded the "File Recovery" dialog box appears. When the file(s) have been recovered the list box in the dialog empties but the box stays open and the 'close' button has to be clicked to close the box.

### Describe the solution you'd like

The preferred solution is to automatically close the "File Recovery" dialog box after the recovery process if the list of files to be recovered is empty.

Pseudo code:
[Existing] User downloads a file > "File Recovery" dialog box appears > user selects tree or file entry then clicks "Recover"
[Existing] Sandboxie recovers file(s) and leaves dialog open with empty list of files.
[New] After recovery action, test if file list is empty and if true, close dialog.

If desired an option could be added to 'Automatically close "File Recovery" dialog box after all files have been recovered'

**Comment by DavidXanatos** [comment] 2022-06-08 16:00
duplicate of https://github.com/sandboxie-plus/Sandboxie/issues/1498

**Closed by DavidXanatos** 2022-06-08 16:00 UTC
Labels: Feature request, file recovery
