### ISSUE TITLE
Questions and suggestions about snapshot management

### ISSUE THREAD

**Issue by jkc123456789** [sandboxie-plus/Sandboxie#2589] opened 2023-01-06 15:40 UTC
### Is your feature request related to a problem or use case?

Issue: After saving the snapshot, the shortcuts in the desktop menu and start menu are not displayed correctly when running the box, and this problem also exists when importing the 7z package of the box. Please fix this, thanks!

Feature suggestion: Snapshot management is a nice feature, but still not perfect. It is recommended that when taking snapshots, package the snapshots into a compressed package, so that you can save a lot of disk space after more snapshots. When you select Enter Snapshot, restore the contents of the snapshot archive to the current working directory.

### Describe the solution you'd like

1.fix the bugs
2.Snapshot management is a nice feature, but still not perfect. It is recommended that when taking snapshots, package the snapshots into a compressed package, so that you can save a lot of disk space after more snapshots. When you select Enter Snapshot, restore the contents of the snapshot archive to the current working directory.

**Comment by offhub** [comment] 2023-01-06 20:45
It seems like it's not possible to store snapshots as 7z archives as it's some kind of incremental snapshot. Maybe a setting could be added to enable NTFS compression on snapshot folders. Or you can do this manually.

`Windows Explorer` > `Right click on the file/folder` > Select `Properties` > From `General Tab`: Click on `Advanced` > Check the option `Compress contents to save disk space` > `OK`  [_Do not check the encryption setting or you will not be able to access encrypted files (EFS) with Sandboxie except compartment type box._ [***](https://github.com/sandboxie-plus/Sandboxie/issues/1980#issuecomment-1166233068)]

> ... and this problem also exists when importing the 7z package of the box
#2585

**Comment by jkc123456789** [comment] 2023-01-07 13:47
> It seems like it's not possible to store snapshots as 7z archives as it's some kind of incremental snapshot. Maybe a setting could be added to enable NTFS compression on snapshot folders. Or you can do this manually.
> 
> `Windows Explorer` > `Right click on the file/folder` > Select `Properties` > From `General Tab`: Click on `Advanced` > Check the option `Compress contents to save disk space` > `OK` [_Do not check the encryption setting or you will not be able to access encrypted files (EFS) with Sandboxie except compartment type box._ [***](https://github.com/sandboxie-plus/Sandboxie/issues/1980#issuecomment-1166233068)]
> 
> > ... and this problem also exists when importing the 7z package of the box
> > #2585

Thanks, enabling NTFS compression might be a way to do it! However, please investigate and fix the problem that shortcuts caused by snapshots and imports cannot be used

**Comment by okrc** [comment] 2023-01-11 19:29
@jkc123456789 Please try this build https://github.com/sandboxie-plus/Sandboxie/actions/runs/3896013562
It should solve the problem of shortcuts not working when exporting to the sandbox.

**Comment by DavidXanatos** [comment] 2023-01-28 17:01
the issue with desktop menu and start menu should be fixe din 1.6.7

**Comment by okrc** [comment] 2023-01-28 17:20
@DavidXanatos There are still bugs, such as the shortcut icon being lost after creating a snapshot. Shortcuts are not removed even after uninstalling the software.

**Comment by DavidXanatos** [comment] 2023-01-29 17:03
> @DavidXanatos There are still bugs, such as the shortcut icon being lost after creating a snapshot. Shortcuts are not removed even after uninstalling the software.

fixed and fixed

**Comment by okrc** [comment] 2023-01-29 18:06
> Shortcuts are not removed even after uninstalling the software.

https://github.com/sandboxie-plus/Sandboxie/blob/1d8d0b4a85eba8303efbd631f716e0a35b407568/SandboxiePlus/SandMan/SbiePlusAPI.cpp#L413-L414

The shortcuts are obtained from the snapshot, not from inside the sandbox. This means that some deleted or broken shortcuts will be created as well.

**Comment by DavidXanatos** [comment] 2023-01-29 20:48
yea you are right if we delete a link in a later snapshot the code as is will still import it...
but fixing that would be a huge pain, we would need to implement delete v1 and v2 support.
I don think  running a process Sandboxed to report on the links is viable.

1. Since I intent to make delete v2 default starting in 1.7.x i would if at all implement only delete v2 support to the link import code.

**Comment by DavidXanatos** [comment] 2023-01-29 22:51
next fix: https://github.com/sandboxie-plus/Sandboxie/commit/3c0651a23629c399f7e06d77c472c115cd45e8cd

**Comment by okrc** [comment] 2023-01-30 02:02
> next fix: [3c0651a](https://github.com/sandboxie-plus/Sandboxie/commit/3c0651a23629c399f7e06d77c472c115cd45e8cd)

There are still bugs.
https://github.com/sandboxie-plus/Sandboxie/blob/3c0651a23629c399f7e06d77c472c115cd45e8cd/SandboxiePlus/SandMan/SbiePlusAPI.cpp#L457
The `GetRealPath()` function will only return QString() for snapshots.

Adding the following code to the function does the trick, but I'm not sure what the function does because I didn't read the code carefully.
```QString CSbieAPI::GetRealPath(CSandBox* pBox, const QString& Path)```
```c++
	if (RealPath.left(10) == "\\snapshot-")
		RealPath.remove(QRegExp("^\\\\snapshot-[^\\\\]+"));
```

**Comment by DavidXanatos** [comment] 2023-01-30 07:43
ach darn i forgot to commit SbieAPI.h also just committed an other fix

**Comment by okrc** [comment] 2023-01-30 08:19
I confirmed that the latest commit fixes it

**Closed** 2023-01-31 07:49 UTC
Labels: Feature request, fixed in next build, Snapshot

**Comment by jkc123456789** [comment] 2024-04-23 15:08
> 我确认最新的提交修复了它

你好，请问您是中国人吗？如果您是中国人的话，请问是否可以联系您咨询沙盒的使用问题
