### ISSUE TITLE
SBIE2321 Cannot manage device map:  [C0000034 / 11]

### ISSUE THREAD

**Issue by ask2018** [sandboxie-plus/Sandboxie#2996] opened 2023-05-30 16:35 UTC
### Describe what you noticed and did

I'm getting this error each time when I want to start some sandboxed program.  Reverting back to Sandboxie-Classic-x64-v5.62.2 solves the issue. 

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

The error should not be there as before.

### What is your Windows edition and version?

Windows 7 x64 SP1 ESU updates included

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Eset Endpoint AV, Agnitum Outpost FW

### What version of Sandboxie are you running?

Sandboxie-Classic-x64-v5.64.6 64bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### Is it a regression?

since 5.63.0 64bit

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

My sandbox contains existing programs or data.

**Comment by offhub** [comment] 2023-05-30 17:15
Try adding the following setting to your configuration.
> You may need to restart your system.


`NtNamespaceIsolation=n`

**Comment by ask2018** [comment] 2023-05-30 17:38
Thank you, but unfortunately it has no effect. I've tried that included system restart and the error msg is still there with Sandboxie-Classic-x64-v5.64.6. Reverting back to Sandboxie-Classic-x64-v5.62.2  fixed the issue again. No system restart needed for that.

**Comment by DavidXanatos** [comment] 2023-05-31 06:38
Ok so v5.63.0 introduced this error,
have you tried an empty sandboxie ini do is the error related you a particular config?

**Comment by ask2018** [comment] 2023-05-31 09:57
@DavidXanatos good point and I have found what it is causing. I have for all my sandboxes DropAdminRights=y in the config.
If I remove that line or change to DropAdminRights=n, then the error is gone with latest version. With Sandboxie-Classic-x64-v5.62.2 DropAdminRights=y doesn't cause that device map error.

**Comment by isaak654** [comment] 2023-05-31 11:29
If this issue was introduced in v1.8.0 / 5.63.0, then I would suggest to check all `drop_rights` references in https://github.com/sandboxie-plus/Sandboxie/commit/c97c90c3ea737278be87a2cfe3f383983174ef88

**Comment by wilders-soccerfan** [comment] 2023-05-31 12:26
I am on Win7, 64-bit, SP1 (NO third party av installed) and have not encountered this error in plus versions.
I cannot reproduce this on a new yellow box in v1.9.6 (same backbone as 5.64.6?) after adding DropAdminRights=y.

**Comment by ask2018** [comment] 2023-05-31 12:41
My system got really lot of specific settings and software running there. Because this is somehow related to drive letters, I guess I should also mention I have here multiple drives without drive letter set (they are encrypted ones mounting only when needed with veracrypt)

**Comment by offhub** [comment] 2023-07-20 20:14
You're probably getting this error because you're running the agent (SbieCtrl/SandMan) as administrator.

`Agent (as admin)` + `DropAdminRights=y` = `SBIE2321 Cannot manage device map: [C0000034 / 11]`

**Comment by ask2018** [comment] 2023-07-20 20:22
Yes that is correct. I'm running it as admin, but that was always like that even before. Something must changed since the version 5.63.0 related to this.

**Comment by isaak654** [comment] 2023-10-13 13:25
According to a comment by @BilleBarrett, this regression is still reproducible in version 1.11.4 / 5.66.4: https://github.com/sandboxie-plus/Sandboxie/discussions/3365#discussioncomment-7264566

**Comment by DavidXanatos** [comment] 2024-01-27 18:26
the issue was introduced with 1.8.0 and will be fixed in the next build

**Closed** 2024-01-31 07:28 UTC
Labels: Confirmation pending, fixed in next build, Regression
