### ISSUE TITLE
Ping not working in app compartment mode

### ISSUE THREAD

**Issue by hg421** [sandboxie-plus/Sandboxie#1608] opened 2022-02-08 18:09 UTC
### What happened?

`ping` does not work in an App Compartment box.
Instead it fails and produces the message
```PING.EXE (30532): SBIE1314 Blocked request to alter network/firewall settings by process 'PING.EXE'```.

If the option "Prevent change to network and firewall parameters" is turned off, the message no longer appears, but it still gets stuck.

If the box type is changed to Standard Isolation, the problem disappears and ping works normally.

### To Reproduce

1. create new "App Compartment" box
2. in the box, open command prompt and run `ping 127.0.0.1` 

### Expected behavior

ping works normally in AppComp box (like it does in a normal box)

### What is your Windows edition and version?

Windows 10 20H2 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.10

### In which sandbox type you have this problem?

In an Application Compartment sandbox with no isolation (green sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment] 2022-02-14 01:54
I can confirm this issue on Plus 1.0.11 as well.

**Comment by DavidXanatos** [comment] 2022-02-14 08:50
I can reproduce the initial issue but un checking "Prevent change to network and firewall parameters"  solves it for me.

**Comment by isaak654** [comment] 2022-02-14 12:21
SBIE1314 error related to ping.exe appears only in a sandbox with App Compartment, not in the standard sandbox.
Is it expected?

**Comment by DavidXanatos** [comment] 2022-02-14 13:18
no thats a bug and will be fixed, but after you uncheck "Prevent change to network and firewall parameters" ping should work as normal

**Comment by isaak654** [comment] 2022-02-14 14:29
> no thats a bug and will be fixed, but after you uncheck "Prevent change to network and firewall parameters" ping should work as normal

Not here, if you need remote support  just ask.

**Comment by DavidXanatos** [comment] 2022-02-14 15:01
the difference is the template: RpcPortBindingsExt when its added then ping works

**Comment by isaak654** [comment] 2022-02-14 15:15
So, to sum up, we have two bugs in the same issue:
- missing RpcPortBindingsExt template for the compartment mode
- BlockNetParam that is exclusively required in the sandbox with compartment mode

**Comment by Simba98** [comment] 2022-09-16 13:39
Still repeat in SBIE v1.3.2
![image](https://user-images.githubusercontent.com/7941967/190652359-8de3cd56-e58f-4b6b-83fb-646451699247.png)

**Comment by RandomGOTI** [comment] 2022-09-16 22:29
> Still repeat in SBIE v1.3.2 ![image](https://user-images.githubusercontent.com/7941967/190652359-8de3cd56-e58f-4b6b-83fb-646451699247.png)

Can confirm on 1 3 3 with a new created no isolation box BlockNetParam=n is not set but from the look of it it was not intended to be added to begin with , only the template was said to be added and that is there ,so diasble BlockNetParam and you're good to go.

**Comment by isaak654** [comment] 2023-04-02 10:56
A fix was committed in https://github.com/sandboxie-plus/Sandboxie/commit/3d64f4f71e8e17c3dc3b769be1f1c4deef169def

**Comment by isaak654** [comment] 2023-04-02 11:07
@DavidXanatos 

> So, to sum up, we have two bugs in the same issue:
> 
>     missing RpcPortBindingsExt template not applied for the compartment mode
>     BlockNetParam warning that is exclusively triggered in the sandbox with compartment mode

They both still occur, even after https://github.com/sandboxie-plus/Sandboxie/commit/3d64f4f71e8e17c3dc3b769be1f1c4deef169def

**Comment by isaak654** [comment] 2023-04-02 11:11
@DavidXanatos 

> So, to sum up, we have two bugs in the same issue:
> 
>    - missing RpcPortBindingsExt template not applied for the compartment mode
>    - BlockNetParam warning that is exclusively triggered in the sandbox with compartment mode

They both still occur, even after https://github.com/sandboxie-plus/Sandboxie/commit/3d64f4f71e8e17c3dc3b769be1f1c4deef169def

**Comment by DavidXanatos** [comment] 2023-04-02 11:48
please provide feadback if the build 1.8.2a solves the issue for you or not

**Closed** 2023-04-02 12:08 UTC
Labels: more info needed, fixed in next build, Issue reproduced, ToDo ASAP, Win 10

**Comment by isaak654** [comment] 2023-04-02 12:28
I can confirm the fix after updating to 1.8.2a:

![Support_settings_1.8.2a](https://user-images.githubusercontent.com/12372772/229352763-588c0943-e191-4ca5-acb3-16bc48b2f2e6.png)
