### ISSUE TITLE
Default Box comes always back

### ISSUE THREAD

**Issue by Nietod** [sandboxie-plus/Sandboxie#3928] opened 2024-05-22 18:48 UTC
### Describe what you noticed and did

After deleting the Default Box it comes always back after a restart of Sandboxie. There is no box in the file explorer but the Sandboxie UI shows a default box, which can't be removed because it comes always back,

### How often did you encounter it so far?

Whenever Sandboxie is closed completly and restarted

### Expected behavior

That the Default Box won't come back in the UI after I deleted it.

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus 1.13.7

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### What is your Windows edition and version?

Windows 10 Pro 64 Bit

### In which Windows account you have this problem?

A local account (Standard user)., A local account (Administrator).

### Please mention any installed security software

Kaspersky Antivirus

**Comment by offhub** [comment] 2024-05-22 19:45
Duplicate of #2445

**Closed** 2024-05-23 22:36 UTC
Labels: duplicate, Confirmation pending
