### ISSUE TITLE
Client-server game is unable to run as of SB+ 0.94. Tested under 0.94 & 0.95

### ISSUE THREAD

**Issue by alasalto** [sandboxie-plus/Sandboxie#1154] opened 2021-08-31 11:25 UTC
**Describe the bug**
Factorio game (https://factorio.com/) is unable to finish loading. 

**To Reproduce**
Install the program under either SB+ 0.94 or 0.95 (tested on both versions and on 0.89). Launch the program.
The program starts displaying its loading state. When reaching 95%, the program stops suddenly showing a handled-error dialog. I have just copied the dialog-error text  for the purpose of populating this issue:
<<<>>>
Error
Unexpected error occurred. If you're running the latest version of the game you can help us solve the problem by posting the contents of the log file on the Factorio forums.
Please also include the save file(s), any mods you may be using, and any steps you know of to reproduce the crash.

Log file location: C:\Users\{username}\AppData\Roaming\Factorio\factorio-current.log

Would you like to open the folder containing the log file?

Yes   No   
<<<>>>

It is worth mentioning the latest SB+ version the game run flawlessly was 0.89.

OS Windows 10 version 21H1.-

**Additional context**
WFP SB+ 0.94+ option is set to 'not activated'.-

**Sandboxie configuration**

[GlobalSettings]

Template=RpcPortBindings
Template=RBTray
Template=AdobeDistiller
Template=Kaspersky
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
FileRootPath=E:\EMUs\Sandbox\%USER%\%SANDBOX%
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
ForceDisableSeconds=10

.....

[UserSettings_xxxxxxxxx]

SbieCtrl_UserName={username}
SbieCtrl_ShowWelcome=n
SbieCtrl_EnableLogonStart=n
SbieCtrl_EnableAutoStart=n
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=n
SbieCtrl_WindowCoords=185,169,1237,710
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_AutoApplySettings=n
BoxDisplayOrder=text omitted.-

[ggFactorio11]

Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
RecoverFolder=C:\Users\{username}\AppData\Roaming
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=n
CopyLimitKb=81920

---.---

**Comment by isaak654** [comment] 2021-09-09 00:32
I was able to reproduce the bug, but you were partially wrong because the last working version was 0.9.0.

The same fix applied for https://github.com/sandboxie-plus/Sandboxie/issues/1161 resolves your issue, so the fix will be included in the next build.

**Closed** 2021-09-12 10:01 UTC
Labels: fixed in next build, compatibility regression, Last working version: 0.9.0
