### ISSUE TITLE
Sandboxie not installing on windows parallel on mac m1 (request to add ARM64 support)

### ISSUE THREAD

**Issue by jay-sync** [sandboxie-plus/Sandboxie#1321] opened 2021-10-20 16:52 UTC
**Is your feature request related to a problem? Please describe.**
Sandboxie won't install on mac m1 on windows 10 via parallel (ARM architecture) trowing the error: "This program can only be installed on versions of Windows designed for the following processor architectures: (x84/x64)

**Describe the solution you'd like**
Sandboxie for windows ARM

**Describe alternatives you've considered**
some apps work even if not natively supported on ARM, unfortunately, Sandboxie won't proceed with the install 

![image](https://user-images.githubusercontent.com/63868998/138136443-b8b9e565-ca45-4324-bd99-cbb3e5df5c7a.png)

![image](https://user-images.githubusercontent.com/63868998/138136535-2dbde422-3218-4bac-ab33-7d777ccaeb2f.png)

![image](https://user-images.githubusercontent.com/63868998/138136817-863cdcfb-56eb-4b31-8833-19dba79263c7.png)

**Comment by DavidXanatos** [comment] 2021-10-21 17:36
Is there any platform I could use to test windows on arm that is not a MAC?
I know it runs a bit on Raspberry PI but rather bad and slow.
Or is there someone willing to donate a mac LOL?

**Comment by isaak654** [comment] 2021-12-22 19:01
#645

**Comment by TGSAN** [comment] 2022-05-06 06:40
> Is there any platform I could use to test windows on arm that is not a MAC? I know it runs a bit on Raspberry PI but rather bad and slow. Or is there someone willing to donate a mac LOL?

Hi, the Surface Pro X is a good choice, it runs Windows ARM64 natively on a Qualcomm processor, plus it's Certified Refurbished version is very inexpensive (compared to a mac)

**Comment by DavidXanatos** [comment] 2022-05-06 14:06
but its from MSFT so the important question can you disable secure boot on it?
Because on the old windows 8 arm surfaces you could not making it pretty useless...

**Comment by DavidXanatos** [comment] 2022-05-06 14:35
Here a cpu comparison: https://www.cpubenchmark.net/compare/BCM2711-vs-Snapdragon-7c-vs-Microsoft-ARM-SQ1-vs-Apple-M1-8-Core-3200-MHz/4297vs4194vs4113vs4104
For the Surface pro X I see prices around 700€
The Snapdragon 7c is almost a better option as it can be got in a 300$ mini pc, the surface is 37% faster but costs at least twice as much.
The first one is a raspberry pi 4 without overclocking.

**Comment by TGSAN** [comment] 2022-05-06 20:03
It does look like it, but I haven't known about Snapdragon 7c based Windows devices. There are some Snapdragon 845/835/8cx based OEM laptops which are slightly weaker with SQ1/SQ2, but have a nice price. But not sure if these devices have long-term technical support, such as driver updates and system updates, etc. In fact, it is possible to brush some Android or Lumia phones to Windows, which is substantially faster than the Raspberry Pi 4, but very unfriendly for debugging.

**Comment by DavidXanatos** [comment] 2022-05-06 20:07
a Snapdragon 7c is to be found here https://www.apcsilmic.com/products/dot-mini-pc?variant=42483059163385

**Comment by isaak654** [comment] 2022-07-14 09:18
I don't see much point in keeping duplicate issues, for further updates please refer to #645

**Comment by isaak654** [comment] 2022-07-14 09:18
Duplicate of #645

**Closed** 2022-07-14 09:19 UTC
Labels: duplicate, Feature request, ARM64
