### ISSUE TITLE
Sandboxed Brave Browser open tabs get whipped out with Brave version update 

### ISSUE THREAD

**Issue by CaliSunUSA** [sandboxie-plus/Sandboxie#4305] opened 2024-10-18 23:00 UTC
### Describe what you noticed and did

After experiencing numerous problems with Firefox, I have finally uninstalled it and installed Brave Browser.
Brave works great, no more connection issues and no slowdown issues.
**Except for one issue:**
My browser is set to remember open Tabs. That works ok for couple of days, but when there is Brave update, sandboxed browser tabs get reset back to default and I loose all open tabs.

### How often did you encounter it so far?

two times this week

### Expected behavior

sandboxed browser should remember open tabs after browser update.

### Affected program

Brave  Version 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)

### Download link

https://brave.com/download/

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Plus v1.14.10 (64 Bit)

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### Is it a regression from previous versions?

Sandboxie Plus v1.14.9 (64 Bit)

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Pro 22H2 (64-bit)

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Avast

**Comment by offhub** [comment] 2024-10-19 07:21
Could you please share your Sandboxie configuration?

**Comment by CaliSunUSA** [comment] 2024-10-21 01:13
Is that what you need?

![image](https://github.com/user-attachments/assets/8e4d1cf4-b893-4bc0-bd74-1b0e7eed3d64)

**Comment by CaliSunUSA** [comment] 2024-10-21 01:56
Correction, 
Sandboxed Brave Browser open tabs getting whipped is unrelated to Brave version update.
That was my original thought because I lost open tabs around same time as last update. But now I see, I lost my tabs last night, but there was no brave browser update since Oct 17th.
Brave that is Not sandboxed keeps its tabs without issues, only Sandboxed Brave keeps loosing tabs. Also History list does not have any info of previously open tabs. (It does pull in open tabs and history from Not sandboxed Brave)

**Comment by offhub** [comment] 2024-10-21 07:50
Duplicate of #558 

See https://github.com/sandboxie-plus/Sandboxie/issues/558#issuecomment-1336250083

```
WriteFilePath=brave.exe,%LocalAppData%\BraveSoftware\Brave-Browser\User Data\Default\Sessions\*
```

**Comment by offhub** [comment] 2024-10-21 07:53
Duplicate of #558

**Comment by CaliSunUSA** [comment] 2024-10-21 22:36
That worked, thanks.
I do have another issue, for which I will create separate ticket.

**Closed** 2024-10-22 08:41 UTC
Labels: Duplicate, Workaround, Not a bug, Browser: Chromium
