### ISSUE TITLE
plugins_nms.exe cannot be closed (Kaspersky process)

### ISSUE THREAD

**Issue by tianyi725** [sandboxie-plus/Sandboxie#1989] opened 2022-06-26 03:48 UTC
### What happened?

Originally used 5.33, after updating to sandboxie5.56.3
There is always a process plugins_nms.exe in the sandbox and cannot be shut down. I don't know what is the reason?
thanks

### Download link (Kaspersky Internet Security)

https://www.kaspersky.com/downloads/internet-security-free-trial#download

### Expected behavior

plugins_nms.exe cannot be closed

### What is your Windows edition and version?

windows 10 pro 21H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

kis2021

### What version of Sandboxie are you running?

sandboxie 5.56.3

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment] 2022-06-26 06:28
what software does it belong to?

**Comment by isaak654** [comment] 2022-06-26 07:29
Duplicate of #647

**Comment by isaak654** [comment] 2022-06-26 08:13
> what software does it belong to?

https://www.kaspersky.com/free-antivirus

**Comment by isaak654** [comment] 2022-06-26 09:18
> what software does it belong to?

[Kaspersky Security Cloud Free](https://www.kaspersky.com/free-antivirus) / [Kaspersky Internet Security](https://www.kaspersky.com/downloads/internet-security-free-trial#download):

> Please mention any installed security software
> 
> kis2021

**Closed** 2023-02-24 13:07 UTC
Labels: duplicate, Known issue, Kaspersky

**Comment by isaak654** [comment] 2023-02-24 13:33
Duplicate of #647
