### ISSUE TITLE
Cannot install MeshCommander 

### ISSUE THREAD

**Issue by stdedos** [sandboxie-plus/Sandboxie#1738] opened 2022-03-29 20:22 UTC
### What happened?

Is it just me, or others cannot install MeshCommander too?

![image](https://user-images.githubusercontent.com/133706/160699230-b3e5af0a-a087-4f5c-b0ea-98b95abc9948.png)

### Download link

https://www.meshcommander.com/meshcommander

### Expected behavior

_Installation finishes_

### What is your Windows edition and version?

18363.836

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Version 1.0.15

### Is it a regression?

< v1? 😕 I don't remember

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by isaak654** [comment] 2022-04-03 20:54
Confirmed on Plus v1.0.15 x64 and Windows 10 21H1 x64.

* Workaround: `MsiInstallerExemptions=y`
* Side effect: the following notification that seems harmless:
`msiexec.exe (4784): SBIE2303 Could not hook win32k, wow64win.dll read failed`
And yes, it's related to the `EnableWin32kHooks=y` setting in `[GlobalSettings]`.
If I set it to `n`, it doesn't appear anymore after closing/reopening Plus UI.

![win32k](https://user-images.githubusercontent.com/12372772/161447924-df138f99-43b6-4d86-9448-c05742ee3a7b.png)

**Comment by stdedos** [comment] 2022-04-03 21:08
"Would it be easy" to detect failure of `msiexec` and offer this setting to be changed?
If so, that could be a handy feature.

Otherwise, thank you for the hints 🙂

**Comment by isaak654** [comment] 2022-04-04 14:25
> "Would it be easy" to detect failure of `msiexec` and offer this setting to be changed?
> If so, that could be a handy feature.

That would be great.

**Comment by DavidXanatos** [comment] 2023-02-16 07:06
Since we have a dedicated feature request https://github.com/sandboxie-plus/Sandboxie/issues/2699 now I'll close this one

**Closed by DavidXanatos** 2023-02-16 07:06 UTC
Labels: Feature request, Workaround, MSI Installer
