### ISSUE TITLE
SBIE2203 errors with newest Chrome when playing videos and screen captures are black again.

### ISSUE THREAD

**Issue by Sqrlly** [sandboxie-plus/Sandboxie#1611] opened 2022-02-09 15:03 UTC
### What happened?

Yesterday the Chrome web browser updated for me to Version 98.0.4758.82 64-bit.  Since then when I play videos on services like Hulu, Netflix, or Youtube TV I get the following errors:

```
chrome.exe (8596): SBIE2203 Failed to communicate with Sandboxie Service:  connect C0000022                                        
chrome.exe (8596): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 14 - chrome.exe [C0000080]   
chrome.exe (8596): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 14 - chrome.exe [C0000080]   
chrome.exe (8596): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 14 - chrome.exe [C0000080]   
chrome.exe (8596): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 14 - chrome.exe [C0000080]   
chrome.exe (8596): SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 14 - chrome.exe [C0000080]   
```

This is with:
- Sandboxie-Plus v1.0.8
- Windows 10
- NVIDIA GeForce GTX 1660 Super

The video still plays correctly, but the errors come up each time a video is played.  And it now once again blackens the video area when doing a screen capture (Win-Shift-S or PrintScrn, etc.) which the sandbox had prevented prior to the Chrome update.

Regular Youtube does not appear to be generating the error so far.

### To Reproduce

1. Open Sandboxie-Plus
2. Run latest Chrome (98.0.4758.82)
3. Open video service (such as Hulu)
4. Play a video.

### Expected behavior

To not get the errors and for Sandboxie to prevent chrome from interferring with my screen capture.

### What is your Windows edition and version?

Windows 10 Home 21H2 19044.1466

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender provided with Windows.

### What version of Sandboxie are you running?

Sandboxie-Plus v1.0.8 

### List of affected browsers

Chrome version 98.0.4758.82 64-bit

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by Sqrlly** [comment] 2022-02-09 15:23
Update.  I had downloaded from the https://sandboxie-plus.com/downloads/ site which showed 1.0.8 as the newest.  I have now gotten 1.0.10 direct from github and can confirm the issues are exactly the same.  This did also occur in 0.9.8d, which promoted me to update (to 1.0.8).  So not a regression but something that changed in Chrome that bypasses the Sandboxie protection.

**Comment by DavidXanatos** [comment] 2022-02-10 19:23
i don't have hulu, do thay offer free videos?
or is teh issue present with netflix?
or with that else?

Try disabling Win32 hooks and rebooting

**Comment by Sqrlly** [comment] 2022-02-10 20:42
Yes I had this happen with all of Hulu, Netflix, or Youtube TV (not regular Youtube though).

As for the hooks do you mean to set 'EnableWin32kHooks=y' to 'n' instead?  If so, I did that and still get the messages, but screen capture works again.

**Comment by linax3-genuine** [comment] 2022-05-05 15:19
im getting SBIE2203, Msgid: 12 [C0000024] while running a screen capture software, spamming constantly on "touch"(task switch, window focus switch?). and if i start the capture, a bunch of messages.
updated the other day to sbie+ v1.0.20. 
i did not had that in the previous version. cant remember which one it was, but it was beyond v1.0.10. maybe .17.
i dont have problem with the sc program. it seem to be working normally.
i have the experimental win32k hook enabled. tried to disable it, still the same. restarted sbie service. did not reboot. will update, if it changes on next reboot.

**Comment by DavidXanatos** [comment] 2023-07-22 09:30
As far as I can tell this is intended behavior of the chromium web browser, also (correct me if I'm wrong) the change happened with a chromium update not with a new sandboxie build.
So we did not break anything, thay broke it on purpose, the behaviorue is the same when running unsandboxed, hence I'll Close this issue without a fix as explained else ware sandboxie is not an Anti DRM tool.

Also it seams that with firefox OBS studio can still capture netflix just fine so I would recommend to use to a more free browser then chrome to resolve this issue.

**Closed by DavidXanatos** 2023-07-22 09:30 UTC
Labels: ToDo ASAP
