### ISSUE TITLE
Installer Suggestions

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#414] opened 2021-01-19 22:49 UTC
### 1. Signed installer

Sign the installer to help overcome download/run warnings by browsers and OS. For example, the desktop installer for "Telegram" is signed and it's a single-click-to-run experience. Admittedly, sandboxie does not yet have 500M users, but I like to live in hope...

### 2. Signed components

Sign installed components (exe, dll, etc) where possible.

### 3. Single installer

I'm not sure why there need to be 5 different installer downloads (Plus, Classic) x (x86, x64) x (Win7driver)? Is this a constraint on the installer? This is exactly the kind of decision I'd expect machines to make, not humans. Is there any use case for installing x86 on an x64 machine? Can it run on Win 7 without the provisional driver? Suggestions:
a) Single installer to contain all filesets
b) If Win7 identified, warn user, then deploy provisional driver if accepted.
c) Install x86/x64 according to platform
d) Always deploy both, Classic and Plus
e) Ask user if they want to auto-start Plus (recommended default), nothing, or classic

### 4. Uniform versioning

Why maintain separate versions for Plus and Classic? I assume most users will simply install the latest and greatest and be done with it. Knowledge of these separate version numbers seems an entirely technical matter for devs, and Plus has come a long way and I think it's ok to not belittle it any longer with a zero-dot version. Suggestions:
a) Make all applications in a release have the same version number.
b) Inject this version number to all built components so each installer has only one version number across all built components.

### 5. Simpler versioning

Simplify version numbers. There are now 4 components in the version number, like "0.5.4c". Hard to remember and read. Is this necessary for ordinary users? Suggestion: Use a simple incrementing release number, and if desired for style, include a major version number prefix, eg, "v5.1025". Differentiate beta/internal releases from official releases by saying so on the release page.

**Comment by ImSpecial** [comment] 2021-01-20 02:06
3. No, specifically points "a)" and "d)".
4. No, you assume wrong that everyone wants "the latest and greatest", many still want just the "Classic" standalone. 

And because of issues people may have with a new release it's useful to be able to go back to a previous working version, are you suggesting to get rid? Sandman might change and get a bump in version, but the core "Classic" stuff does not always change along with Sandman, so separate versioning is a must between the two.

**Comment by typpos** [comment] 2021-01-20 02:35
> suggesting to get rid? 

I'm not suggesting to actually get rid of Classic. I'm suggesting a combined installer.

> No...

Interesting to know and fair enough. I'd find it just easier to have one installer and version to download and then select what to install when running it, but it's no big deal.

**Comment by ImSpecial** [comment] 2021-01-20 03:12
Then there's the size of one installer vs. many, 3MB vs. 60MB. Might not be a huge thing, but still a point to consider.

**Comment by typpos** [comment] 2021-01-20 03:39
> Then there's the size of one installer vs. many, 3MB vs. 60MB.

Umm, I take your other points but can't agree on this one. I installed several 50GB+ applications in the last few weeks and one of those had two full-download updates. This very github issue page downloads several megabytes.

A more relevant issue:
* Install Plus
* Install Classic
* Windows Start > Remove Program > Uninstall Classic
* Start Plus
* Message: "Runs in portable mode" 
* Say ok
* Error Message "Failed to connect to driver"

My point: The applications overlap already because of the common driver innards. Having separate installers is flawed.

Maybe to address your concerns, the installer can provide an option for people who only want to install either Plus XOR Classic. To me that's not much different to installing both and letting the user choose which one to run on startup. Easier for support if deployments are the same. Easier for users not to have to think or understand "x86 vs x64" and juggle multiple files.


Anyway, I don't want David to get a heart attack when he gets up in the morning. It's great software as it is and I can live with it happily either way...

**Comment by Coverlin** [comment] 2021-01-20 12:14
1 & 2 Signed X Signed Y Signed Siggy: See #238 #270 


3 Single installer : 
Download what you want/need  `"d) Always deploy both, Classic and Plus"` HINT: install plus and you get both UI's ... It's already there if YOU want it
Even Invincea was providing separate installers per architecture beside the "single installer" of theirs

`"Then there's the size of one installer vs. many, 3MB vs. 60MB."
"Umm, I take your other points but can't agree on this one. I downloaded & installed several 50GB+ applications in the last few weeks and one of those had two full-download updates"` 
Congratulations , how is this relevant  for "single installer" again ?

```
"A more relevant issue:

Install Plus
Install Classic
..."
```

Read my "HINT" , and consider issues that are not based on user "inexperience".. you're not supposed to **install** both to have both `"Having separate installers is flawed"` This statement aged like milk...and quite fast

4 & 5  Uniform & "Simpler" versioning : 
`"Knowledge of these separate version numbers seems an entirely technical matter for devs, and Plus has come a long way and I think it's ok to not belittle it any longer with a zero-dot version"`
"Classic" continues it's versoning it has been using even before open source, for plus it's self explanatory... 

`"Simplify version numbers. There are now 4 components in the version number, like "0.5.4c". Hard to remember and read. Is this necessary for ordinary users? Suggestion: Use a simple incrementing release number, and if desired for style, include a major version number prefix, eg, "v5.1025". Differentiate beta/internal releases from official releases by saying so on the release page."`
Well it's funny that you find 0.5.4c confusing,hard to XYZ but give v5.1025 as example but also the necesity to announce it's release stage to be able to "differentiate". Did you just jump from a spacious pool to a small bathtub with this one ?
major.minor.patch

**Comment by typpos** [comment] 2021-01-20 20:58
@Coverlin 
Thanks for your hint. That's really useful. I disagree with your other items. Get yourself an upgrade of your personal "User Interface". This is github not Twitter. If you feel elevated because of a difference of opinion then have a cold shower and avoid using feeble attempts at sacrasm.

**Comment by Coverlin** [comment] 2021-01-21 04:58
> @Coverlin
> Thanks for your hint. That's really useful. I disagree with your other items. Get yourself an upgrade of your personal "User Interface". This is github not Twitter. If you feel elevated because of a difference of opinion then have a cold shower and avoid using feeble attempts at sacrasm.

Right it's not. But I could swear it was by the way you've argumented your dissagrement purely on `"I download & install several 50GB+ ..."` on a valid counter argument pointed out by another user...  `"...to address your concerns..." ` while you're missing the point , yeah the problem is me i can see it clearly. /s
Suggestions 3-5 are based on assumptions not on an informed basis  :
-3b) already warns the user if w7 that the prov driver is required , the warning gives the option to open the download page if you don't have it , abort installation , or continue if you have it. The warning is not needed if the installer includes the w7 driver aswell and it isn't included anymore for reasons you can find on topics your duplicate starting suggestions share , point 1 & 2 , other indicators 3d) `"Deploy both..."` , 4 
5 is just your personal preference, that wasn't any more effective than semantic for your argument

`"Having separate installers is flawed"` but not "my" revolutionary single installer suggestion, this thread in a nutshell so far.
`"need to have 5 different downloads"` basically want only 1 bundle download link REEEE ...difference of opinion... sure... let's create annoyances for intermediate and advanced users because of newbies that refuse or are lazy to learn ? `"This is exactly the kind of decision I'd expect machines to make, not humans."` Yea no. i can decide for myself.. if a newbie wants to download everything on the release page for whatever reason they can, i won't do the same and i expect to not be forced (even bundled) to just to be able to install 1 thing `"it's no big deal."` sickle Mario , but hey take the initiative and create your own single installer without forcing it down other's throats
 
P.S. I don't use twitter but here have a trigger warning along this ⬇️
01010011 01101111 00100000 01101111 01100010 01101100 01101001 01110110 01101001 01101111 01110101 01110011 00100000 01101111 01100110 00100000 01110011 01100101 01101100 01100110 00101100 00100000 01101000 01111001 01110000 01101111 01100011 01110010 01101001 01110100 01100101

**Comment by bastik-1001** [comment] 2021-01-23 11:52
The installer being signed along with all its components is a good idea, as those will not raise as many flags as unsigned component and it seems harder to have something tamper with the software. The provisional driver is supposed to be going away, once that is possible and it is distributed separately on purpose as many security software complains about it.

I am not sure if there are any statistics about how many users of Sandboxie are on 32bit OSes, but installing 32bit software on 64bit OSes, when there is a 64bit version of the same software might happen out of error. So it might be a good idea to merge the 32bit and 64bit version of the installers to have:

- Sandboxie Classic Installer.exe
- Sandboxie Plus Installer.exe

and then the installer deploys the 64bit version when the system is a 64bit system. There might be valid reasons to stick with the classic version and be it a poor connection or the users habits, but at least users will not install a 32bit version out of error.

To 4) Well, both have a history and users could be confused when 5.4.xxx gets superseded by 0.6.x, It might be possible to have both be version 6.x.x. so that the classic users will know it is a newer version and the plus users only need to get used the version number jumping ahead. The only problem one might have with that is that the plus version would be seen as mature as the classic version, which is not true from historical points of view, but something I would not mind at all as users may want to stick with the classic version as that was around much longer without knowing that the plus version is close to replicate everything the classic version can do. Right now the different version numbers also help with reports of issues as someone may try something with the classic version, that only the plus version could do.

To 5) That can be difficult as well. Is 0.5.5.10 newer than 0.5.5.2? Assuming the patch being increased by 1 (to have 0.5.5.1to9) yes it is. Assuming a different version system it could be different. I agree with less symbols being easier to remember or to check against, Browsers have a version system that starts with a number and then some patches separated by dots. Due to it changing often I can't say which browser version would be the current one, on the top of my head, but it is easier to check if my version is 32 or not. I am not sure if a, b, c, are something people can remember well, but as Sandboxie can check for updates the user should not have to deal with it. I prefer if Sandboxie has a consistent version scheme, whatever it may be.

**Comment by Spitt** [comment] 2021-01-29 20:09
Although I would love to install this software, I am not advanced enough to install the software without it being signed, nor do I want to completely turn off UAC. For me to install either Sandboxie classic or the Plus version, it needs to be signed.

Also, I agree, a 60mb installer is nothing. Many people expect programs to be that size these days. Group them all together, with the WIN 7 update package if need be.

**Comment by NewKidOnTheBlock** [comment] 2021-01-29 20:17
> I am not sure if there are any statistics about how many users of Sandboxie are on 32bit OSes, but installing 32bit software on 64bit OSes, when there is a 64bit version of the same software might happen out of error.

I think NObody who can't tell the difference between 32 and 64bit (and which version to download) is gonna use Sandboxie.

**Comment by bastik-1001** [comment] 2021-01-31 17:23
> I think NObody who can't tell the difference between 32 and 64bit (and which version to download) is gonna use Sandboxie.

This is probably true.

> At the moment, there are only 4 downloads, which requires you to make 2 decisions

For me that can stay way, although I would understand if 32/64 bit would be merged to reduce it to one. I don't mind it being either way.

> Want to experience real decision overload? Check out Brave's Github:
https://github.com/brave/brave-browser/releases/tag/v1.19.88 - 32 (sic!) different downloads to choose from...

Besides it supporting more platforms there are options I would have no idea what to select or why they re even there.

**Comment by DavidXanatos** [comment] 2021-06-07 18:28
the installer is signed the provisional driver is gone I'll close this now

**Closed by DavidXanatos** 2021-06-07 18:28 UTC
