### ISSUE TITLE
Could not load service DLL - rpcepmap.dll

### ISSUE THREAD

**Issue by RisingYoung-Learn** [sandboxie-plus/Sandboxie#2463] opened 2022-11-15 12:21 UTC
### Describe what you noticed and did

1. Start a Windows Remote Desktop;
2. Start SandMan in Windows Remote Desktop,
3. Start the application (eg: notepad.exe) into SandMan;
![image](https://user-images.githubusercontent.com/54743518/201918436-072d1deb-066b-4efd-8179-e7447b03cbb3.png)

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

The application was successfully launched in the sandboxie.

### What is your Windows edition and version?

Windows Server 2016 Standard [Version 1607 (OS Build 14393.5006)]

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie plus 1.5.0 64

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In an Application Compartment sandbox with no isolation (green sandbox icon).

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Sandboxie.ini configuration

```shell
[GlobalSettings]
FileRootPath=\??\C:\Program Files\PackBox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=7zipShellEx
EnableObjectFiltering=n
OpenPipePath=C:\Program Files\JHPackApp
OpenPipePath=H:\
OpenPipePath=S:\
OpenPipePath=P:\
OpenPipePath=M:\

[DefaultBox]
Enabled=y
Template=RpcPortBindingsExt
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=-
BorderColor=#000000,off,6
CopyLimitKb=-1
PromptForFileMigration=n
NoSecurityIsolation=y
NoSecurityFiltering=y
MsiInstallerExemptions=y
AllowSpoolerPrintToFile=y
OpenProtectedStorage=y
OpenIpcPath=$:*
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
OpenPipePath=*\NamedPipe\*
UseSbieWndStation=n
UnrestrictedSCM=y
RunServicesAsSystem=y
ExposeBoxedSystem=y
StripSystemPrivileges=n
RpcMgmtSetComTimeout=n
UnrestrictedToken=y
UnfilteredToken=y
KeepTokenIntegrity=y
OpenWinClass=*
OpenCredentials=y
DisableComProxy=y
EnableMiniDump=y
EnableWin32kHooks=n
ExternalManifestHack=y
Installer=Administrator
UsePrivacyMode=n
BlockNetParam=n
BlockNetworkFiles=n
```

**Comment by DavidXanatos** [comment] 2022-11-29 15:53
I cant reproduce this right now, anyone else with this issue?

**Comment by DavidXanatos** [comment] 2023-08-04 14:27
as there is no more feadback and we cant reproduce it I'll close this

**Closed by DavidXanatos** 2023-08-04 14:27 UTC
Labels: Can't reproduce, RDP

**Comment by ddeeproton2** [comment] 2024-05-26 07:02
Just a feedback, not an issue for me :

I have installed it on a Intel Atom CPU (64 bit), windows 10.
First I can't start RpcSS, 
And right after "Could not load service DLL - rpcepmap.dll".
I try SandboxiePlus - "v1.14.0" and Classic "v5.69.0".

I think, it happen because my windows is not updated ;-)

**Comment by ddeeproton2** [comment] 2024-05-26 07:30
I installed older version, v0.4.0 now it works ;)

**Comment by ddeeproton2** [comment] 2024-05-26 07:50
I disabled Windows Defender to try.
Now it works with the last version ;)
