### ISSUE TITLE
Sandboxie-Plus 1.2.6 will not load any webpage on any browser

### ISSUE THREAD

**Issue by NotepadPlusUser** [sandboxie-plus/Sandboxie#2084] opened 2022-07-31 10:57 UTC
### Describe what you noticed and did

I can't locate my post a week ago on V1.2.5 in either the Open or the Closed Issues, so I will have to start again.  The problem now is a little different.

I checked that V1.2.6 is now marked as the official release in the coloured boxes at https://github.com/sandboxie-plus/Sandboxie ,
so I dared to download and install it.  There was a certificate permission required for certification when I first launched Vivaldi in a sandbox, but otherwise Vivaldi opened properly in a sandbox. 

PROBLEM: No webpage even begins to load.

I closed down the VPN, and tried in succession Vivaldi, Firefox, Edge, Brave and IE in various sandboxes.  No further permissions were required, and again no webpage ever even began to load.

But everything opened OK outside the sandboxes using the switch  /dfp  in the command line.

I will go back to V1.1.3 once again, but I have no idea what the problem is.  I should mention again that the problems that I reported in 
https://github.com/sandboxie-plus/Sandboxie/issues/1835
persist in V1.1.3 .

### How often did you encounter it so far?

As above

### Affected program

All five browsers are up to date

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

As above

### What is your Windows edition and version?

64-bit Windows 10 Pro 21H2 V10.0.19044.1865 (updated today)

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

ESET internet Security V15.2.11.0

### What version of Sandboxie are you running?

Sandboxie-Plus V 1,2,6

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### Is it a regression?

I previously installed 1.2.0, 1,2,1, 1,2,5, all of which had problems, and each time I reverted to V1.1.3.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

No

**Comment by isaak654** [comment] 2022-07-31 11:04
There is a known limitation about `SandboxieLogon=y`, which is applied by default in v1.2.6 / 5.57.6: https://github.com/sandboxie-plus/Sandboxie/issues/2025

**Comment by isaak654** [comment] 2022-07-31 11:06
There is a known limitation about `SandboxieLogon=y`, which is applied by default in v1.2.6 / 5.57.6: https://github.com/sandboxie-plus/Sandboxie/issues/2025

See also https://github.com/sandboxie-plus/Sandboxie/discussions/2064 for further explanation about the feature.

**Comment by isaak654** [comment] 2022-07-31 11:45
Duplicate of #2025

**Comment by DavidXanatos** [comment] 2022-08-01 18:37
in 1.2.7 this option is off by default so i'll close this topic

**Closed by DavidXanatos** 2022-08-01 18:37 UTC
Labels: duplicate, ESET
