### ISSUE TITLE
Failed to initialize "Rockstar Games Launcher"

### ISSUE THREAD

**Issue by Taeyeonzpx** [sandboxie-plus/Sandboxie#2707] opened 2023-02-18 11:22 UTC
### Describe what you noticed and did

The "Rockstar Games Launcher" does not run in the sand table.  Before, the "Rockstar Games Launcher" can run when installed inside the sand table, but now it does not run when installed inside the sand table.  I do not know whether it is a platform problem or a sand table compatibility problem

### How often did you encounter it so far?

everytime

### Affected program

Rockstar Games Launcher

### Download link

https://socialclub.rockstargames.com/rockstar-games-launcher

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Expected behavior

Capable of normal operation

### What is your Windows edition and version?

windows11 home 22H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Huorong

### What version of Sandboxie are you running?

Sandboxie-Plus 1.7.2 64 bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=AutoRecoverIgnore
ConfigLevel=9
```

**Comment by isaak654** [comment] 2023-02-19 00:25
Could you retry [this](https://github.com/sandboxie-plus/Sandboxie/issues/2236#issuecomment-1255901875) workaround again? I wonder if this is a duplicate of that issue.

**Comment by Taeyeonzpx** [comment] 2023-02-19 01:51
> Could you retry [this](https://github.com/sandboxie-plus/Sandboxie/issues/2236#issuecomment-1255901875) workaround again? I wonder if this is a duplicate of that issue.
> 
No, this method doesn't work now. Now "WerFault.exe" appears

**Comment by isaak654** [comment] 2023-02-26 12:07
I think it's the same of #2720, if not please provide more details.

**Comment by Taeyeonzpx** [comment] 2023-02-28 09:59
> I think it's the same of #2720, if not please provide more details.

Right! This is the same problem, "unable to initialize."

**Comment by isaak654** [comment] 2023-04-14 16:26
Duplicate of #2720

**Comment by isaak654** [comment] 2023-04-14 16:29
Since #2720 provides more details, I'm going to close this issue as duplicate.

**Closed by isaak654** 2023-04-14 16:29 UTC
Labels: duplicate, Confirmation pending, launcher issue
