### ISSUE TITLE
Firefox keeps showing SBIE2203 error and keeps crashing

### ISSUE THREAD

**Issue by CaliSunUSA** [sandboxie-plus/Sandboxie#2288] opened 2022-09-29 06:51 UTC
### Describe what you noticed and did

Start Firefox inside Sandboxie
Error message pop-up and Firefox crashing usually happens while in Facebook or youtube while video starts playing automatically.

(I have already reported this issue here: https://forum.xanasoft.com/viewtopic.php?f=16&t=446 )

### How often did you encounter it so far?

daily

### Affected program

Firefox

### Download link

N/A

### Where is the program located?

Not relevant to my request.

### Expected behavior

expected is no error messages and not crashing

### What is your Windows edition and version?

Windows 10 Pro 21H2

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

Avast

### What version of Sandboxie are you running?

1.3.5 64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a Standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by Luro223** [comment] 2022-09-29 12:03
@CaliSunUSA what version of firefox?
Also the Avast may be conflicting, try disabling avast completely (temporarily), then test sandboxie if you still have issues, try to reinstall sandboxie with avast disabled and your configuration saved, also show your sandboxie configuration

**Comment by isaak654** [comment] 2022-09-29 13:24
It should also be necessary to exclude any incompatible Firefox extensions that could not run well when sandboxed. 
To check this, you can run the sandboxed browser, disable each extension one by one and report the incompatible extension here (if present).

**Comment by CaliSunUSA** [comment] 2022-09-29 16:45
Worth mentioning that I have not installed any new Firefox plugins. Whatever I have, I had it for a while, and everything worked fine for a while. Error messages and crashing is a recent issue which started to happen after upgrade of Sandboxie Version: 1.3.2. But around that time there were several Firefox updates as well, so not sure which program to blame.

Current software:
Sandboxie: 1.3.5
Firefox: 106.0b5

**Comment by isaak654** [comment] 2022-09-29 17:04
1. Can you reproduce this problem on a new empty sandbox? 
2. Try unchecking the latest two checkboxes (marked as experimental) in 'Options' menu -> 'Global Settings' ->'Advanced config'.
3. You may also want to share your Sandboxie.ini configuration file in order to receive further suggestions.

**Comment by CaliSunUSA** [comment] 2022-09-29 17:09
1) I will report back later when done testing
2) "Use Sandboxie login..." was already unchecked. I have unchecked "Hook selected Win32k..." Will report back with results.
3) Sandboxie.ini: 
Template=Edge_Win11Fix
Template=7zipShellEx
Template=WindowsRasMan
Template=Avast_Antivirus
Template=WindowsLive
Template=OfficeLicensing
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
EnableObjectFiltering=y
EnableWin32kHooks=y

**Comment by CaliSunUSA** [comment] 2022-09-29 21:46
Reporting back on item #1
I have created new box and started Firefox inside.
It crashed again when starting to play youtube video.
What makes me think it might be an audio issue is because I had Facebook open in a different tab and I was reading static page on another domain/tab. I received message on Facebook Messenger, as soon as Facebook gave audio "Ping" that message came through, an error message appeared again.

![Sandboxie error 5](https://user-images.githubusercontent.com/67880003/193147784-73b5bbb5-1d36-4a3d-ad9a-83d3518ea38d.png)

**Comment by Luro223** [comment] 2022-09-30 01:37
@CaliSunUSA disable antivirus, uninstall the sandboxie and (save sandboxie.ini and sandboxie-plus.ini just in case) reboot pc, install sandboxie and try to launch firefox V106.0b5.
Also I can't reproduce issues, firefox 106.0b5 works flawlessly.

**Comment by CaliSunUSA** [comment] 2022-10-07 01:26
OK, after extensive testing; uninstalling Sandboxie with leaving configuration files and later uninstalling Sandboxie with removing configuration files, I kept getting error pop-up and crashes.
So later I focused on Firefox, I uninstalled all my plugins, but I kept getting crashes. So eventually I uninstalled and re-installed Firefox, and that fixed it. Even now with re-installing all my plugins, everything seems stable. So something happened with Firefox base.
Thanks for all the help.

**Comment by CaliSunUSA** [comment] 2022-10-07 01:31
OK, after extensive testing; uninstalling Sandboxie with leaving configuration files and later uninstalling Sandboxie with removing configuration files, I kept getting error pop-up and crashes.
So later I focused on Firefox, I uninstalled all my plugins, but I kept getting crashes. So eventually I uninstalled and re-installed Firefox, and that fixed it. Even now with re-installing all my plugins, everything seems stable. So something happened with Firefox base.
But the strange thing is, Firefox only crashed inside Sandboxie, outside of Sandboxie Firefox seemed to work fine.
Thanks for all the help.

**Closed** 2022-10-07 17:16 UTC
Labels: Confirmation pending, Workaround

**Comment by mjokkk** [comment] 2022-10-20 01:45
Hello, as far as I could notice, it happens AT LEAST when there is some audio embedded inside the page. For example here:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

**Comment by DavidXanatos** [comment] 2022-10-20 06:53
Please try build 1.5.0 it fixed a firefox issue

**Comment by CaliSunUSA** [comment] 2022-10-23 01:22
Confirming that Issue returned in Sandboxie 1.4.2 as soon as Firefox upgraded to 106.0
As suggested by DavidXanatos above, I have upgraded to build 1.5.0 from https://github.com/sandboxie-plus/Sandboxie/releases/ (Sandboxie was telling me that 1.4.2 was up-to-date).
After up-versioning Sandboxie, everything seems stable now. Will report back if this issue returns.

**Comment by CaliSunUSA** [comment] 2022-10-31 23:36
Firefox updated to 100.0.3 and error messages returned.
So I looked at: https://github.com/sandboxie-plus/Sandboxie/releases/  and I see that new version is available (1.5.2)
When I try to install downloaded program, I get a message I have never seen:

![Sandboxie install error](https://user-images.githubusercontent.com/67880003/199129077-8737b2bd-7475-4000-96a2-508133f8d02b.png)

**Comment by isaak654** [comment] 2022-10-31 23:46
1.5.2 installers were released unsigned to provide some fixes as quickly as possible... as a side effect, they can also cause false detections like this one.

**Comment by isaak654** [comment] 2022-10-31 23:47
1.5.2 installers were released unsigned to provide some fixes as quickly as possible... as a side effect, they can also cause false detections like that one.
