### ISSUE TITLE
After removing sandbox from Plus UI, it not removes from Sandboxie.ini -> BoxDisplayOrder

### ISSUE THREAD

**Issue by lufog** [sandboxie-plus/Sandboxie#900] opened 2021-06-14 10:26 UTC
**Describe the bug**
After removing sandbox from Plus UI, it not removes from Sandboxie.ini -> BoxDisplayOrder. So, after removing and creating a sandbox a couple of times, we get:
![image](https://user-images.githubusercontent.com/10379487/121876785-94885480-cd12-11eb-9cb5-b7c374a072e7.png)

**To Reproduce**
1. Remove sandbox
2. Create sandbox with same name
3. Repeat  a couple of times

**Expected behavior**
Expect the same number of sandboxes in the Run list as in the Plus UI, without duplicates.

**System details and installed software:**
- Windows 10 Pro 21H1
- Sandboxie Plus 0.8.1

**Comment by DavidXanatos** [comment] 2021-06-14 15:01
i could not reproduce the issue removing a box from the plus UI removed it also from the sbie ini also you should not be able to have multiple boxed with the same name.
try cleaning up the sansboxie.ini and test if the issue rpeats

**Comment by lufog** [comment] 2021-06-15 10:36
@DavidXanatos, I made a video of reproducing of this bug: https://youtu.be/2BSe5fxqNAU

**Comment by isaak654** [comment] 2021-06-15 15:49
Personally I can see a number of duplicates in the BoxDisplayOrder line, but not in the Run list.

**Comment by lufog** [comment] 2021-06-15 16:04
@isaak654 on the last iteration, do not remove the sandbox. If the sandbox is deleted, then no entry with its name will be shown in the Run list.

**Comment by isaak654** [comment] 2021-06-15 16:33
> 
> 
> on the last iteration, do not remove the sandbox. If the sandbox is deleted, then no entry with its name will be shown in the Run list.

Thank you, now I'm able to reproduce your issue. I hope the dev will fix it soon.

![duplicated_sandboxes_in_run_list](https://user-images.githubusercontent.com/12372772/122090307-ec54b780-ce07-11eb-91a5-7a04afa9951d.png)

**Comment by DavidXanatos** [comment] 2021-06-15 16:45
will be fixed in the enxt build

**Closed** 2021-06-16 07:26 UTC
Labels: fixed in next build
