### ISSUE TITLE
Sandboxie Classic x64 v5.69.5 not installable/upgradeable on Windows 7 Pro x64

### ISSUE THREAD

**Issue by Mike-0815** [sandboxie-plus/Sandboxie#4134] opened 2024-07-30 22:16 UTC
### Describe what you noticed and did

Hello David, just tried several times to update Sandboxie Classic x64 v5.69.4 to Sandboxie Classic x64 v5.69.5 on Windows 7 Pro x64 but without success. The installer "hangs" always at the same point (see attached screenshot). Also I tried with disenabled Kaspersky Anti-Virus, no luck. 
![Zwischenablage01](https://github.com/user-attachments/assets/67dfb92d-8018-441d-8bc4-db7037c03411)
Also I tried to de-install Sandboxie first and made a new, clean installation, but no luck. ANY other version of Sandboxie will install without any problems (even with Kaspersky activated). Using Sandboxie for many years. 

### Expected behavior

Sandboxie should install/upgrade without problems.

### Affected program

Not relevant to my request.

### Download link

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Not relevant to my request.

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### What is your Windows edition and version?

Windows 7 x64 Pro

### In which Windows account you have this problem?

A local account (Standard user).

### Please mention any installed security software

Kaspersky Antivirus

**Comment by offhub** [comment] 2024-07-30 22:21
#### To Install Version 1.14.6 or 5.69.6:

1. **Download and Extract Sandboxie-Plus:**
    - Download the Sandboxie-Plus 1.14.6. (https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.14.6)
    - Extract the contents to a folder of your choice using portable installation mode.

2. **Locate Necessary Files:**
    - Navigate to the extracted Sandboxie-Plus folder.

3. **Copy Files to Installation Folder:**
    - Inside the extracted folder, locate the following:
        - The "32" folder (for 64-bit only)
        - The "SbieDll.dll" file
    - Copy these items.

4. **Paste Files into Installation Directory:**
    - Navigate to the installation folder of Sandboxie-Plus (where version 1.14.5 is installed).
    - Paste the "32" folder (for 64-bit only) and the "SbieDll.dll" file into this directory, replacing any existing files if prompted.

5. **Install Version 1.14.6 or 5.69.6:**
    - Follow the standard installation process for that version.

**Comment by EatDesk** [comment] 2024-07-30 22:22
That issue is resolved with v5.69.6 https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.14.6

**Comment by Mike-0815** [comment] 2024-07-30 22:28
Thank you EatDesk ! I will try it now ...

**Comment by Mike-0815** [comment] 2024-07-30 22:39
Yes, it installs now. Thank you.

**Comment by offhub** [comment] 2024-07-31 06:46
Duplicate of #4117

**Closed** 2024-08-15 20:38 UTC
Labels: duplicate, Win 7, Win 8.1, already fixed
