### ISSUE TITLE
Couldn't start explorer.exe from sandboxed cmd.exe

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#1771] opened 2022-04-06 06:13 UTC
### What happened?

Couldn't start explorer.exe from sandboxed cmd.exe. 

![](https://user-images.githubusercontent.com/56181919/161905995-9037d34e-edcd-422e-b2b0-c16490b83a12.png)

### Download link

Not relevant

### To Reproduce

1. Run cmd.exe in sandboxie
2. Execute "explorer"
3. Wait a moment
![](https://user-images.githubusercontent.com/56181919/161906411-d18ae6ef-71bc-4ac8-96d5-b3b1979e66e2.png)

### Expected behavior

This bug shouldn't appear

### What is your Windows edition and version?

Windows 10 Enterprise LTSC 2021 x64 (21H2)

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

ESET Internet Security 15.1.12.0

### What version of Sandboxie are you running?

Sandboxie 5.5.17 /  Sandboxie-Plus 1.0.17

### In which sandbox type you have this problem?

Not relevant to my request.

### Where is the program located?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

**Comment by 0x391F** [comment] 2022-04-06 06:15
Other programs semms work well, such as calc, winver.

**Comment by isaak654** [comment] 2022-04-06 12:20
Duplicate of https://github.com/sandboxie-plus/Sandboxie/issues/362

**Comment by DavidXanatos** [comment] 2022-05-01 08:48
start it using  ```explorer.exe /e,::{20D04FE0-3AEA-1069-A2D8-08002B30309D}```

**Closed by DavidXanatos** 2022-05-01 08:48 UTC
Labels: duplicate
