### ISSUE TITLE
DefaultBox keeps resurrecting itself (unlike Classic)

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#2445] opened 2022-11-09 12:35 UTC
### Describe what you noticed and did

The DefaultBox keeps coming back - even if you've got other boxes and deleted DefaultBox on purpose.

### Reproduction steps:
- Start with fresh Sandboxie Plus
- Create a couple of sandboxes
- Remove DefaultBox

![zombie box from hell1](https://user-images.githubusercontent.com/12411527/200829685-93a3a610-93ef-4629-a88e-22d663d0f7c3.png)

- Shut down Sandboxie from tray menu

![zombie box from hell2](https://user-images.githubusercontent.com/12411527/200829803-28dcc673-bfb8-4f89-95de-a81560ed9c38.png)

- Restart Sandboxie
-> DefaultBox resurrects itself!

![zombie box from hell3](https://user-images.githubusercontent.com/12411527/200829968-9aa23252-ba4c-4534-854f-56b73e09ea66.png)

### How often did you encounter it so far?

Always, if following reproduction steps

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Having a DefaultBox is a good thing for beginners, who just installed Sandboxie so that they may get going straight away.
But if you already have a couple of sandboxes and deleted the DefaultBox on purpose, it should not be created anew each time you open the main Sandboxie window.

Possible solution: Check if at least 1 sandbox exists. If true, do **not** create a new DefaultBox.

PS: Classic handles this correctly and doesn't resurrect DefaultBox if you got other sandboxes.

### What is your Windows edition and version?

Windows 10 Pro 21H2 64-bit

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Microsoft Defender

### What version of Sandboxie are you running?

Sandboxie Plus 1.5.2

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by offhub** [comment] 2022-11-09 12:43
Atm there is no way to delete DefaultBox, but you can disable it.
[DefaultBox]
Enabled=n

**Comment by NewKidOnTheBlock** [comment] 2022-11-09 13:00
Ah, I'm gonna add those lines.
Somehow Classic manages to handle this as expected.
When I deleted DefaultBox in Classic, it didn't come back.

**Comment by APMichael** [comment] 2022-11-09 13:47
This is an intended behavior:
> - when DefaultBox is not found by the SandMan UI, it will be recreated
https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.6.5

You just have to **edit** the **ini** and change the line `Enabled=y` to `Enabled=n`. (As **offhub** had already written.)

**Comment by mysteriously** [comment] 2022-11-09 13:51
It could make some sense if sbie config file didnt exist when user installed it for the first time. Otherwise I dont see any point

**Comment by NewKidOnTheBlock** [comment] 2022-11-09 16:07
Yes, it's useful for starters or people who have 0 sandboxes.
But it shouldn't be coming back again and again if you have a couple boxes and want it gone.

**Comment by paradoxicallist** [comment] 2022-11-09 17:06
> Yes, it's useful for starters or people who have 0 sandboxes. But it shouldn't be coming back again and again if you have set up a couple custom boxes and want it gone.

Fwiw, I'd like to say I concur with this idea. I hate when Default Box resurrects itself.

**Comment by bastik-1001** [comment] 2022-11-09 18:11
There is a function that seems to reply on the DefaultBox being present.

![Always DefaultBox](https://user-images.githubusercontent.com/1449429/200906562-6b645f36-437a-4905-944f-2c05f41cdc7d.png)

The good thing is, one can change the settings of `DefaultBox`, without those being altered, as far as I encountered. One may just not use it, if custom boxes fulfill the needs instead.

**Comment by NewKidOnTheBlock** [comment] 2022-11-09 20:28
Good catch. I was gonna write about that next.
IMHO there should be a way to select a box and make it the standard go-to box that gets selected first.

E.g. I got 2 default boxes. One without internet access (which I always try to use first) and one with internet access (if the sandboxed program is acting up or will not work without internet by design).

**Comment by typpos** [comment] 2022-11-16 09:01
Duplicate of #487 ? Also discussed in #359 item 12.

The DefaultBox is required because some features depend on it. For example:

```` 
"C:\Program Files\Sandboxie-Plus\Start.exe"  notepad.exe
````

References in code:
* https://github.com/sandboxie-plus/Sandboxie/search?l=C%2B%2B&q=defaultbox&type=code
* https://github.com/sandboxie-plus/Sandboxie/search?q=m_DefaultBox&type=code

**Comment by mysteriously** [comment] 2022-11-18 20:22
Ok, so maybe we should have custom variable DefaultBoxName=YourCustomDefaultBox

**Comment by NewKidOnTheBlock** [comment] 2022-11-24 12:58
Yeah, or some setting where you can declare one box to be your #1 that always gets selected first.

**Comment by DavidXanatos** [comment] 2022-12-07 10:34
in next build it will be possible to set a custom sandbox as the default box

**Comment by gettysburg** [comment] 2022-12-08 03:42
> it will be possible to set a custom sandbox as the default box

Great solution, thank you for your time and work.

**Comment by paradoxicallist** [comment] 2022-12-08 16:10
> in next build it will be possible to set a custom sandbox as the default box

How is this done cause I tried yesterday renaming DefaultBox to a different name next I copy ini lines from another box to this new one, next restarted the computer and DefaultBox resurrected.

**Comment by DavidXanatos** [comment] 2022-12-08 16:27
there will be a setting in the globa section holding the name of the designated DefaultBox

**Comment by offhub** [comment] 2022-12-08 16:33
After Sandboxie-Plus 1.6.1

**From UI**:
```
Options > Global Settings > Advanced Config > Sandbox Config > Default sandbox: <Select from the dropdown menu>
```

**From INI**:
```
[GlobalSettings]
.
.
.
DefaultBox=SelectedDefaultBox
```

**Comment by NewKidOnTheBlock** [comment] 2022-12-08 16:41
@offhub @paradoxicallist I don't think it's in yet. At least it isn't mentioned in the changelog

**Comment by DavidXanatos** [comment] 2022-12-08 19:22
you need to wait for 1.6.1**b** or later

**Closed** 2022-12-19 12:21 UTC
Labels: Feature request, added in next build, User interface
