### ISSUE TITLE
In shell integration, "Open Sandboxed" is displayed without translation.

### ISSUE THREAD

**Issue by VenusGirl** [sandboxie-plus/Sandboxie#2258] opened 2022-09-20 16:05 UTC
### Describe what you noticed and did

![SandShell](https://user-images.githubusercontent.com/53147200/191306286-7873988a-d2ac-440b-8c76-b5dd5b28bec7.png)
In shell integration, "Open Sandboxed" is displayed without translation.

### How often did you encounter it so far?

Not relevant

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Not relevant

### What is your Windows edition and version?

Not relevant

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

Not relevant

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression?

Not relevant

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Did you previously enable some security policy settings outside Sandboxie?

Not relevant

### Sandboxie.ini configuration

```shell
Not relevant
```

**Comment by isaak654** [comment] 2022-09-20 16:35
Duplicate of #2229

**Comment by Luro223** [comment] 2022-09-20 16:36
@VenusGirl try to restart explorer but I think it's localization issue (one of Update Text-Korean-1042.txt)

**Comment by isaak654** [comment] 2022-09-20 17:39
That's due to the missing translation support for this line: https://github.com/sandboxie-plus/Sandboxie/blob/102d13da15fcc3b0ce48019441df22722cb07937/SandboxiePlus/SbieShell/SbieShellExt/dllmain.cpp#L164

**Comment by VenusGirl** [comment] 2022-09-20 19:27
Does it work well in Win10 but not yet implemented in Win11?

**Comment by isaak654** [comment] 2022-09-20 19:43
The file above was written specifically for the Windows 11 context menu, but the localization support has yet to be completed.

**Comment by DavidXanatos** [comment] 2022-09-22 08:42
windows 10 does not use the SbieShellExt.dll as on 10 you can add context menu entries using the registry.
as this is a duplicate i'll close this

**Closed by DavidXanatos** 2022-09-22 08:42 UTC
Labels: duplicate, Win 11, Localization
