### ISSUE TITLE
Edge/Chrome/Brave/Vivaldi v90 hang with 5.49.7 and hardware acceleration on

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#795] opened 2021-04-17 13:43 UTC
In the first report, one user tested clean installs of 5.49.5 and 5.49 , but they fail too.
For further details:

<details>
 
<summary>Report n. 1</summary>

> Since updating to Edge 90.0.818.39, Brave 90.1.23.71, Chrome 90.0.4430.72 I can no longer open these browsers with Sandboxie 5.49.7 x64bit on one of my laptops. Sandboxie 5.49.7x64 worked fine with the previous versions of all three browsers. All browsers were updated outside of Sandboxie, and the contents of the sandboxes were emptied prior to updating (I have auto empty enabled, but always double check).
>  
> When I launch these browsers I get an error window pop up, which I cannot progress from. Closing the error windows just closes the error, but no browser opens. Leaving the error to see if it rights itself doesn't work - I have left it 1 hour but the error remains and no browser opens.
>  
> This is the error, which is the same on all three browsers:
>  
>  https://www.wilderssecurity.com/threads/sandboxie-plus-0-7.436454/page-7#post-3000839
>  
> Steps I've tried include trying various sandboxes, rebooting, running c-cleaner, uninstalling and reinstalling both Sandboxie and Chrome (including previous versions of Sandboxie and starting over with a new ini file), running a SFC & DSIM restore health command. Windows version 20H2 19042.928. Windows Defender only. Only sandboxie settings I've changed is to allow autorecovery and auto delete of the sandbox on recovery, otherwise it's out of the box. None of these things have worked.
> 
> Yeah it's 100% a Chrome 90.x issue. At first for me it was only Google Chrome that wasn't working, it started when it moved from version 89.x to 90.x. I get the attached error in my post when I try and launch it in Sandboxie. Then as other Chrome browsers have updated to 90.x, they too, now fail to open with the same error. Vivaldi still works for me, but that is still on v 89.x on my machine. It's not a Sandboxie 5.49.7 thing because all Chrome based browsers worked fine on 5.49.7 until they updated from 89.x to 90.x. Also, I've tested clean installs of 5.49.5 and 5.49 , but they fail too. FF and all other apps behave as expected though.
> 
> What I don't understand is why it's just one machine for me - my fastest and newest one. All my machines are configured identically in terms of updates, settings and software. The only difference between the working ones and not working one, is that the not working one has an 11th gen CPU and Iris Xe graphics (though not sure what that would have to do with it - probably nothing).
> 
> Since disabling hardware acceleration stops the Edge hangs on launching (introduced with Chrome based browsers updating from 89.x to 90.x), perhaps just perhaps, the CPU/GPU combo of the one machine I cannot launch any Chrome based browsers on at all, is not entirely irrelevant after all? (Disclaimer - I am by no means as tech savvy as most on here). It's pretty much the only difference between that machine and the other 5 that are working.
> 
> The machine in question has an i7-1165G7 with Iris Xe and no dedicated GPU. My other five machines are a mixture of various CPUs and GPUs. Anyone else with an ultrabook with an i7-1165G7 and Iris Xe? Can you launch Chromium browsers running 90.x under Sandboxie without getting [this](https://www.wilderssecurity.com/threads/sandboxie-plus-0-7.436454/page-7#post-3000839) error? I'm not talking about hangs, I mean with the error and nothing launching full stop. 

</details>

<details> 
<summary>Report n. 2</summary>     

> I can no longer use Chrome-based browser with SBIE 5.49.7 either. I think the issue started with chrome version 90 because 
> any version about that will not run in sbie; things act like they are going to load but never do. Using Vivaldi, chrome base 
> 90.0.4430.58, nothing loads at all. I am also using Windows version 20H2 19042.928. 

</details>

<details>
 
<summary>Report n. 3</summary>

> Long time SBIE user but new to the forum.
> 
> I've been having problems with the last several releases of Chromium Edge being a little slow loading sandboxed but the latest release it now takes Edge about 16 seconds to load. Outside the sandbox Edge pops right up. Since I haven't seen any other complaints it must be something specific to my system.
> 
> The details...
> Windows 10 20H2 19042.867 X64
> Sandboxie Plus 0.7.4/5.49.7, I use the classic interface.
> Chromium Edge 90.0.818.39
> 
> What I have tried...
> Clean installed Sandboxie Plus.
> Deleted the Edge profile and started fresh.
> Deleted sandboxie.ini and started fresh.
> Tried running Edge from the default box, normally Edge has a dedicated sandbox.
> Disabled extensions in Edge.
> 
> None of the above has made any difference in Edge's load time, but disabling hardware acceleration did the trick.

</details>

<details> 
<summary>Report n. 4</summary>

> Edge (Chrome v90) will open using Sbie 5.49.7... if I wait for more than 10 seconds.
> In Edge turning off Hardware Acceleration allows Edge to open in Sbie almost instantly.

</details>  

<details> 
<summary>Report n. 5</summary>	

> 
> Suddenly when sandboxed in Sandboxie Plus my Brave browser gives an error page every time:
> https://www.wilderssecurity.com/threads/sandboxie-plus-0-7.436454/page-8#post-3001055
> I suppose Brave updated and now it's not compatible with Sandboxie + any more.
> Unsandboxed it works normally.  

</details>

**Comment by xame-arch** [comment] 2021-04-19 10:19
Maybe try logging between the working and non-working computers and also try in the non-working computer to create a new sandbox with (right click - sandbox setup - resource access - add program - direct access - add program - full access - add program - registry access - add program - IPC access - add program - windows access) the program could be the browser or the Intel driver or both for Tor 32 bit adding Open to it helped me, maybe it will troubleshoot in this case also make logs.
I have a video to help with logging
https://www.youtube.com/watch?v=wXFpo78712M

**Comment by isaak654** [comment] 2021-04-19 13:49
The only workaround for this issue is to disable hw acceleration outside of the sandbox, I hope this can be fixed in a future release.

**Comment by hg421** [comment] 2021-04-21 21:03
Yes, I see this issue with MS Edge 90 as well (on Windows 1909 and 20H2).
What happens actually is that, when starting the browser, the GPU process crashes at a certain point and is then repeatedly launched again, until it gives up. (Effectively one then browses with hardware acceleration disabled...)

Here is what I found while trying to debug this.

Chromium browsers do hardware compositing in a separate process (the GPU process). 
For this, the window that DirectComposition renders into must be owned by the process that does the rendering, i.e. in this case by the GPU process. But the browser windows are attached to the main process.
So, what they do is they create a *child window* owned by a thread of the GPU process (the "`Window owner thread`"),
with window class `Intermediate D3D Window`, which is reparented by the main process to be a child of its window.
(See: https://github.com/chromium/chromium/blob/b1995fbf6d2064776862b0deced3b5220404fad5/ui/gl/child_window_win.h#L17-L19)

Here is an illustration of how this look like:
![screen](https://user-images.githubusercontent.com/78082344/115617989-5c582d00-a2f2-11eb-8081-7af81f7ab332.png)

Now, if the browser is started inside the sandbox, somehow something goes wrong with the window creation.
The function [`ChildWindowWin::Initialize`](https://github.com/chromium/chromium/blob/0eed97327b80d123d2a90379bf1ed3ab201c23ad/ui/gl/child_window_win.cc#L128) launches the "Window owner thread" which then runs the `CreateWindowsOnThread` routine.
It then tries to create the window by calling `CreateWindowEx`:
```cpp
HWND window = CreateWindowEx(
    WS_EX_NOPARENTNOTIFY | WS_EX_LAYERED | WS_EX_TRANSPARENT |
        WS_EX_NOREDIRECTIONBITMAP,
    reinterpret_cast<wchar_t*>(g_window_class), L"",
    WS_CHILDWINDOW | WS_DISABLED | WS_VISIBLE, 0, 0, size.width(),
    size.height(), *parent_window, nullptr, nullptr, nullptr);
if (!window) {
    logging::SystemErrorCode error = logging::GetLastSystemErrorCode();
    base::debug::Alias(&error);
    CHECK(false);
}
```
https://github.com/chromium/chromium/blob/0eed97327b80d123d2a90379bf1ed3ab201c23ad/ui/gl/child_window_win.cc#L96-L106

For some reason `CreateWindowEx` fails and returns NULL, which causes an assertation failure (and, if no debugger is attached, leads to an immediate crash).
Unfortunately I have no idea what is happening here, also `GetLastError` returns 0...

I guess I'll have to leave this for someone else to figure out :)

**Comment by isaak654** [comment] 2021-04-29 09:38
Report n. 6 by stapp:
> 
> I can confirm with Vivaldi 3.8.2259.27 using Chrome/90.0.4430.86 that Sandboxie will not run (using Plus 0.7.4 on this machine) 
> Updated vivaldi to latest release 3.8.2259.37 (Stable channel) (64-bit) which uses Chrome/90.0.4430.95 on my Sbie Classic machine 5.49.7
> I used "C:\Program Files\Sandboxie\Start.exe" vivaldi.exe --no-sandbox" as the target and at least I can run vivaldi under sbie supervision.

**Comment by NewKidOnTheBlock** [comment] 2021-05-06 14:30
I can confirm this error with Brave Portable 1.23.71-72

**Comment by FredB750** [comment] 2021-05-07 05:18
I experienced trouble with all 64 bit chrome v90+ browsers. The 32bit versions seem to run OK.??
Would like to hear if anyone else has found the same to be true?

**Comment by DavidXanatos** [comment] 2021-06-03 21:53
Please try adding
```PreferExternalManifest=y```
to the ini section of your sandbox where you are using the electron app and please report if that solved the issue

**Comment by DavidXanatos** [comment] 2021-06-04 12:45
This issue should be resolved in the next build untill then you can sue this patched SbieDll.dll
https://xanasoft.com/Downloads/SbieDll_5.49.8a.zip

Strangely the window reparrenting @hg421 reported still seams broken,
never the less the HW acceleration seams working when you go to chrome://gpu it tells you whats working and what not

**Closed** 2021-06-05 12:45 UTC
Labels: fixed in next build

**Comment by xame-arch** [comment] 2021-09-12 13:06
I tested on windows 8.1 and it doesn't work

**Comment by isaak654** [comment] 2021-09-12 13:16
> 
> 
> I tested on windows 8.1 and it doesn't work

Could you share your config and your sandboxie version?

**Comment by xame-arch** [comment] 2021-09-12 13:32
Sandboxie 5.49.8

config:
[GlobalSettings]

Template=7zipShellEx
Template=FireFix_for_Win7

[DefaultBox]

ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=FileCopy
Template=SkipHook
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Enabled=y

[UserSettings_11BA028F]

SbieCtrl_UserName=hublot
SbieCtrl_NextUpdateCheck=-1
SbieCtrl_WindowCoords=811,150,789,527
SbieCtrl_ActiveView=40021
SbieCtrl_UpdateCheckNotify=y
SbieCtrl_EnableLogonStart=y
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=y
SbieCtrl_AddQuickLaunchIcon=y
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=y
SbieCtrl_AutoApplySettings=n
SbieCtrl_BoxExpandedView=DefaultBox,f,g,h,i

[f]

Enabled=y
ConfigLevel=9
AutoRecover=y
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=FileCopy
Template=SkipHook
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl

[g]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl,6

[h]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl,6

[i]

Enabled=y
ConfigLevel=9
BlockNetworkFiles=y
Template=OpenSmartCard
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl,6

**Comment by isaak654** [comment] 2021-09-12 13:39
I think the maintainer takes in consideration only the latest sbie version, could you test 5.51.6 please?

**Comment by xame-arch** [comment] 2021-09-13 10:55
Indeed it works I deleted my sandboxes and install the update, I don't know if it's because I had not deleted my sandboxes, probably.
