### ISSUE TITLE
Recovering a file downloaded in Chrome to quickly copies, instead of moves, the file out of the sandbox.

### ISSUE THREAD

**Issue by jedimasterspaz** [sandboxie-plus/Sandboxie#158] opened 2020-10-18 23:26 UTC
Recovering a downloaded file from Chrome before the blue circle around the download icon at the bottom of Chrome stops blinking leaves a copy of the file in the Downloads directory in the sandbox.  So when I close Chrome, the Recovery window shows the same file that I already recovered.  If I wait until the blue circle stops blinking to click on the Quick Recover box then the file is recovered and a copy is not left in the sandbox.
This problem doesn't seem to happen in Firefox.

Thanks for looking into this when you have time.

**Comment by jedimasterspaz** [comment] 2020-10-21 16:19
I don't know how I made this second ticket.
Sorry, just close it.
Thanks

**Comment by isaak654** [comment] 2020-10-25 23:34
Duplicate of #157

**Closed** 2020-10-26 19:09 UTC
