### ISSUE TITLE
BSOD issues with release 1.9.4

### ISSUE THREAD

**Issue by 7starsseeker** [sandboxie-plus/Sandboxie#2958] opened 2023-05-25 10:43 UTC
### Describe what you noticed and did

BSOD happend after I update sandboxie-plus to v1.9.4 x64 and on system reboot, just when I unistall it everything went fine.
Sorry when I encountered this, I didn't have the system's ability to collect dump files turned on. Now I can turn this on, but I don't want to reproduce the problem for the sake of my computer. I hope you can understand. I've posted the ini file and all the other screenshots you need.
![屏幕截图 2023-05-25 184246](https://github.com/sandboxie-plus/Sandboxie/assets/18816083/0364de88-4478-4fa8-8e12-3ecbb9ac1a5f)
![屏幕截图 2023-05-25 184309](https://github.com/sandboxie-plus/Sandboxie/assets/18816083/3ad59ed0-4fcc-4f89-b016-8a38f8784bcf)

### How often did you encounter it so far?

every time on boot

### Affected program

sandboxie-plus-x64-v1.9.4

### Download link

https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.9.4

### Where is the program located?

Not relevant to my request.

### Expected behavior

just fine why and how to fix it

### What is your Windows edition and version?

Windows 10 Enterprise x64 22h2

### In which Windows account you have this problem?

A Microsoft account (Administrator).

### Please mention any installed security software

Huorong security

### What version of Sandboxie are you running?

Sandboxie-plus v1.9.4

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (explicitly mentioned in this issue).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

### Sandboxie.ini configuration

```shell
[GlobalSettings]

Template=QQ
Template=Edge_Fix
Template=RpcPortBindings
Template=Kaspersky
Template=Proxifier
Template=ProxyCap
Template=AdobeLicensing
Template=ComodoInternetSecurity
Template=OfficeClickToRun
Template=Listary
Template=Logitech_G15_Keyboard
Template=NOD32
Template=7zipShellEx
Template=Avast_Antivirus
Template=WindowsRasMan
Template=SynapticsTouchPad
Template=WindowsLive
Template=InternetDownloadManager
Template=nVidia_Stereoscopic3D
Template=OfficeLicensing
ActivationPrompt=n
FileRootPath=G:\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=y
EnableObjectFiltering=n

[UserSettings_0CBE021A]

SbieCtrl_UserName=lmkta
SbieCtrl_NextUpdateCheck=1611142474
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_HideWindowNotify=n
SbieCtrl_WindowCoords=801,532,798,508
SbieCtrl_ActiveView=40021
SbieCtrl_ProcessViewColumnWidths=250,70,300
SbieCtrl_EnableLogonStart=y
SbieCtrl_EnableAutoStart=y
SbieCtrl_AddDesktopIcon=n
SbieCtrl_AddQuickLaunchIcon=n
SbieCtrl_AddContextMenu=y
SbieCtrl_AddSendToMenu=y
SbieCtrl_BoxExpandedView=DefaultBox
SbieCtrl_AutoStartAgent=SandMan.exe
BoxDisplayOrder=DefaultBox

[DefaultBox]

ConfigLevel=10
AutoRecover=y
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Enabled=y
BoxNameTitle=n
FakeAdminRights=y
CopyLimitKb=81920
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
```

**Comment by DavidXanatos** [comment] 2023-05-25 11:37
Would it be to much to ask to switch the UI language to english and re take the 2nd screenshot?

**Comment by DavidXanatos** [comment] 2023-05-25 11:41
PS: With as far asI can tell simmilar setup, same windows version, and VBS enabled i cant reproduce this issue.
To debug it further it would be required to test a couple test build drivers,
for that you would need to enable Test signing mode ```bcdedit /testsigning on``` 
would you be willing to try out a few test drivers?

**Comment by 7starsseeker** [comment] 2023-05-25 12:19
Here.
![Screenshot 2023-05-25 201402](https://github.com/sandboxie-plus/Sandboxie/assets/18816083/aebdb7ce-c4e8-4750-9737-7939c1429de5)
Although I want to continue to follow in to help solve this problem, but on the one hand I am now dealing with my thesis and may not have time to do it; on the other hand I only have this one computer on hand to use for my thesis and dare not let anything go wrong with it.
So I'm sorry I can't continue to offer help.

**Comment by isaak654** [comment] 2023-05-25 13:32
> Template=ComodoInternetSecurity

This product is known to cause BSOD issues, please apply the recommendations described in https://github.com/sandboxie-plus/Sandboxie/issues/1427#issuecomment-1001273168

**Comment by isaak654** [comment] 2023-05-25 13:49
> OK，I'll try and thanks

This is intended as a suggestion that still needs confirmation. 
Please feel free to report back as soon as you are able, no rush.

**Comment by xsmolasses** [comment] 2023-05-25 14:18
I'm mentioning here what I've no reason to think is related, yet to make brief one readily reproducible BSoD case (but on a box start) using combination experimental options UnstrippedToken=y (not to be mistaken for UnfilteredToken) together with SandboxieLogon=y. Win10 [Pro]: vbox guest halts, or applied to the host hardware, a stop error. Tested v1.9.3 and v1.9.4.

**Comment by isaak654** [comment] 2023-05-25 20:20
#2957

**Comment by DavidXanatos** [comment] 2023-05-25 20:32
Is the issue introduced in 5.64.3 or are earlier versions affected as well?
could you please provide a crashdump?

**Comment by reraikes** [comment] 2023-05-25 20:47
>Is the issue introduced in 5.64.3 or are earlier versions affected as well?
5.64.3 had been running since its release without problems until Sunday evening.

>could you please provide a crashdump?
Could you please provide me with instructions?

**Comment by isaak654** [comment] 2023-05-25 20:54
> > could you please provide a crashdump?
>
> Could you please provide me with instructions?

Full list of crash dump locations: https://github.com/sandboxie-plus/Sandboxie/discussions/2487#discussioncomment-4224189

**Comment by isaak654** [comment] 2023-05-25 21:14
> > could you please provide a crashdump?
>
> Could you please provide me with instructions?

List of crash dump locations: https://github.com/sandboxie-plus/Sandboxie/discussions/2487#discussioncomment-4224189

**Comment by reraikes** [comment] 2023-05-25 22:01
5.64.3 had no problems until the BSoD started on Sunday.  5.64.3 and 5.64.4 exhibit the same problem.  Booting is fine and you can always sit on the login screen forever.  If not connected to the Internet, you can log in (using PIN) and all is well forever.  Rebooting with the Internet connected, UNEXPECTED_KERNEL_MODE_TRAP occurs (usually within a few seconds).  Disconnecting from the Internet and rebooted does not allow you to log in again (BSoD immediately after entering your PIN) - Sandboxie or its hooks must be corrupted as you must boot into safe mode, uninstall Sandboxie, and then everything is perfectly healthy again.

[MiniDump.zip](https://github.com/sandboxie-plus/Sandboxie/files/11569677/MiniDump.zip)

**Comment by isaak654** [comment] 2023-05-25 23:05
@DavidXanatos Since we are in the mood here to concentrate different BSODs, then let's go through them all one by one.

The ease with which [this](https://github.com/sandboxie-plus/Sandboxie/issues/2958#issuecomment-1562993926) can be reproduced is alarming. Crash dump: [052623-17968-01.zip](https://github.com/sandboxie-plus/Sandboxie/files/11569980/052623-17968-01.zip)

**Comment by DavidXanatos** [comment] 2023-05-26 05:27
please try https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.9.5

**Comment by DavidXanatos** [comment] 2023-05-26 08:19
We may have here a few different issues at hand,
your report says 5.64.3 is broken as well but was not in the past, so something changed on your system which in combination with 5.64.3 causes a BSOD

Other users reported issues starting with 5.64.4 and I have identified a potential issue in the driver and fixed it.

So I think we need to debug your issue separately, also the crash dump does not point to the SbieDrv.sys so its difficult to pinpoint was the initial problem may be.

Please try the following things:
1. completely uninstall sansboxie including removing the sandboxie.ini and re install it, then test with default settings if everything works, when it does you can restore the old sandboxie.ini from backup and check if the issue is gone or comes back in which case post your sandboxie.ini as some setting or combination of settings causes it
2. if this does not work try older builds of sandboxie untill you find one that works fine, then report back which one works.

**Comment by isaak654** [comment] 2023-05-26 10:47
> please try https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.9.5

The BSOD issue reported in https://github.com/sandboxie-plus/Sandboxie/issues/2958#issuecomment-1563614521 is still on v.1.9.5.

Note: `SandboxieLogon=y` was in [GlobalSettings], `UnstrippedToken=y` in [DefaultBox].

I'm  sorry, but I'm not going to reproduce it a third time to confirm the fix.

**Comment by isaak654** [comment] 2023-05-26 10:48
> please try https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.9.5

The BSOD issue reported in https://github.com/sandboxie-plus/Sandboxie/issues/2958#issuecomment-1563614521 is still on v.1.9.5 x64.

Note: `SandboxieLogon=y` was in [GlobalSettings], `UnstrippedToken=y` in [DefaultBox].

I'm  sorry, but I'm not going to reproduce it a third time to confirm the fix.

**Comment by offhub** [comment] 2023-05-26 13:06
The system still crashes.

> > please try https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.9.5
> 
> The BSOD issue reported in [#2958 (comment)](https://github.com/sandboxie-plus/Sandboxie/issues/2958#issuecomment-1563614521) is still on v.1.9.5 x64.
> 
> Note: `SandboxieLogon=y` was in [GlobalSettings], `UnstrippedToken=y` in [DefaultBox].
> 
> I'm sorry, but I'm not going to reproduce it a third time to confirm the fix.

**Comment by DavidXanatos** [comment] 2023-05-26 15:58
It is not helpful to mash BSOD's together unless one is sure they had all the same cause.

As far as I can tell  we have 3 different BSOD issues in this thread

the first one reported by 7starsseeker which should be fixed in 1.9.5 and was introduced in 1.9.4

the one with SandboxieLogon=y and UnstrippedToken=y which was introduced who knows when as UnstrippedToken=y is a debug option for the most adventurous of all testers

and the one reported by reraikes which seams to have appeared when 1.9.4 came out but then seams to also started happening with 1.9.3 which run just fine before, so it has some strange compound reason.


I fixed one,

now I'll look into the SandboxieLogon=y and UnstrippedToken=y

and for the last one we need more info what else may have changed on the system before I can proceed further with that one

**Comment by DavidXanatos** [comment] 2023-05-26 16:16
LOL my unpublished driver version with some half done hacks around the token mechanics is not affected by the SandboxieLogon=y and UnstrippedToken=y issue, the public version is, lets see which dirty hack for fun actually fixed something unexpectedly....

**Comment by reraikes** [comment] 2023-05-26 18:39
Completely uninstalling Sandboxie (including sandboxie.ini) and reinstalling 5.64.5 with default settings does not correct the problem.  If connected to the Internet when the system is booted, an UNEXPECTED_KERNEL_MODE_TRAP BSoD occurs shortly after logging in to Windows and Sandboxie Control is auto-started.  If not connected to Internet, all is well (Edge can be launched in a Sandbox without a BSoD occurring).  Uninstalling Sandboxie results in a perfectly healthy system.

Installing older versions of Sandboxie which had no problems in the past exhibit the same symptom.

Uninstalling everything possible except Sandboxie still has the problem.  Reinstalling Windows 11 (saving settings and apps) does not correct the problem.

Backups are created at 6:00 am every day.  Restoring backups from weeks ago does not correct the problem.  Only uninstalling Sandboxie eliminates the problem.  I know this makes it sound like a hardware issue, but without Sandboxie installed, numerous diagnostics and stress tests complete without issue (BIOS settings are at default and there is no overclocking or other optimizations in use).

Do you have any knowledge of the Intel CPU microcode updating process in Windows?  Especially how to disable it (it's my understanding it's volatile and reoccurs on every boot).  I use an Intel Core i9-13900K CPU which is a recent offering from Intel and I'm wondering if Sandboxie isn't getting along with an update that was made available this past Sunday.

**Comment by DavidXanatos** [comment] 2023-05-26 18:52
@isaak654 please try the CI drive 1.9.6 it solves the SandboxieLogon=y and UnstrippedToken=y issue

@reraikes this is strange, I don't think its related to a microcode update, and yea these are usually transient in Nature, that unless you update your UEFI then it may bring a new microcode update and upload it to the CPU on each boot.

**Comment by typpos** [comment] 2023-05-28 01:47
@reraikes 
> Reinstalling Windows 11 (saving settings and apps) does not correct the problem.

Just in case: After your re-install/repair, do you have any drivers on your system that are newer than since hte BSOD started?
Powershell admin:
Get-WmiObject Win32_PnPSignedDriver| select DeviceName, Manufacturer, DriverVersion, DriverDate | Sort-Object DriverDate -Descending

**Comment by reraikes** [comment] 2023-05-28 03:31
I don't have a list of driver versions for my system before the BSoD problem started last Sunday evening to compare to.

Since I can't find any way to make my system run without BSoD's with Sandboxie installed, I have no reference point.

Here's the current list which probably isn't of value by itself:

[Devices.txt](https://github.com/sandboxie-plus/Sandboxie/files/11583600/Devices.txt)

**Comment by DavidXanatos** [comment] 2023-05-28 07:14
and trying older builds 1.9.2 1.8.x 1.7.x 1.5.x 0.9.x all have the same issue?

**Comment by reraikes** [comment] 2023-05-28 07:21
>and trying older builds 1.9.2 1.8.x 1.7.x 1.5.x 0.9.x all have the same issue?

I don't remember the specific versions, but I tried a lot of old versions.  Nothing changed.

**Comment by isaak654** [comment] 2023-05-29 07:03
I think one of the following links might be useful to obtain further information from another crash dump:

- [Generate a kernel or complete crash dump -> Enable memory dump setting -> Kernel memory dump](https://learn.microsoft.com/en-us/troubleshoot/windows-client/performance/generate-a-kernel-or-complete-crash-dump#enable-memory-dump-setting)
- [Driver Verifier-- tracking down a mis-behaving driver](https://answers.microsoft.com/en-us/windows/forum/windows_10-update/driver-verifier-tracking-down-a-mis-behaving/f5cb4faf-556b-4b6d-95b3-c48669e4c983)

**Comment by isaak654** [comment] 2023-05-29 07:04
I think one of the following links might be useful to obtain further information from another crash dump:

- [Enable memory dump setting -> Kernel memory dump](https://learn.microsoft.com/en-us/troubleshoot/windows-client/performance/generate-a-kernel-or-complete-crash-dump#enable-memory-dump-setting)
- [Driver Verifier-- tracking down a mis-behaving driver](https://answers.microsoft.com/en-us/windows/forum/windows_10-update/driver-verifier-tracking-down-a-mis-behaving/f5cb4faf-556b-4b6d-95b3-c48669e4c983)

**Comment by isaak654** [comment] 2023-05-29 07:05
One of the following links might be useful to obtain further information from another crash dump:

- [Enable memory dump setting -> Kernel memory dump](https://learn.microsoft.com/en-us/troubleshoot/windows-client/performance/generate-a-kernel-or-complete-crash-dump#enable-memory-dump-setting)
- [Driver Verifier-- tracking down a mis-behaving driver](https://answers.microsoft.com/en-us/windows/forum/windows_10-update/driver-verifier-tracking-down-a-mis-behaving/f5cb4faf-556b-4b6d-95b3-c48669e4c983)

**Comment by reraikes** [comment] 2023-05-30 23:13
5.64.6 also crashes with an UNEXPECTED_KERNEL_MODE_TRAP BSoD.  This is after the system has run continuously for 6 days without a single hiccup with Sandboxie not installed.

I've attached a complete (instead of mini) dump that hopefully sheds additional light on the problem.

[Dump.zip](https://github.com/sandboxie-plus/Sandboxie/files/11606737/Dump.zip)

**Comment by io43** [comment] 2023-05-31 01:30
not sure if related but i tried to update to 1.9.6 from 1.9.4 and my pc froze and i had to force reboot :/

**Comment by isaak654** [comment] 2023-05-31 09:56
> I've attached a complete (instead of mini) dump that hopefully sheds additional light on the problem.

I don't see a significant difference than the previous crash dump.

I'm not familiar with the use of Driver Verifier tool, but seems risky, considering that a system backup is recommended.
You may want to contact Microsoft support to evaluate this option for your issue. Anyway, please keep us updated.

---

> not sure if related but yesnerday i tried to update to 1.9.6 from 1.9.4 on win10 22h2 and my pc totally froze while installing (in silent mode with Winget) it and i had to force reboot and now it say that i'm stil on 1.9.4

As mentioned in the [release](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.9.6):

`If you have issues with an update installation, just uninstall the previous version keeping the sandboxie.ini and reinstall the new build.`

For further support, please open a [problem report](https://github.com/sandboxie-plus/Sandboxie/issues/new/choose).

**Comment by offhub** [comment] 2023-05-31 10:22
@reraikes Test the stability of your system with various stress tests without Sandboxie installed. (prime95, IPDT, Cinebench etc.)

**Comment by reraikes** [comment] 2023-05-31 16:54
There are absolutely ZERO problems with the system if Sandboxie is not installed.  I've run numerous stress tests, including Prime95 and Cinebench, and the system is 100% stable if Sandboxie is not installed.  The crashes are not random.  They occur shortly after Sandboxie Control starts (with nothing else going on).

This did NOT occur following an update installation of Sanboxie or anything else.  It simply started about 10 days ago for no obvious reason.  I can restore any of my 42 daily backups (6 weeks worth) and they all exhibit the same BSoD when Sandboxie Control loads.  Simply uninstalling Sandboxie from any of them results in a perfectly healthy and stable system.

I would contact Microsoft, but I'm confident that since the system is TOTALLY stable without Sanboxie installed, they will tell me to contact Sandboxie's author.

**Comment by DavidXanatos** [comment] 2023-05-31 18:04
Well but the older backups when they were taken, had Sandboxie installed and worked just fine, correct?
then something changed and now when sandboxie runs you get a bsod.
Now you say if you roll back to one of the previous backups which were perfectly fine with sandboxie, they now experience a BSOD as well, correct?

So something changed and its not windows and not sandboxie as booth come from the backups, I assume you don't run windows update after restoring the backup, or do you?
If you do then try not to, restore a known good backup with an unplugged network cable and check if sandboxie which was fine is still fine or if it is not.
If it is fine than the culprit is a windows update, and we need to pinpoint this as more users may be affected...
If however its not fine then whats the only thing that could have changed and can not be rolled back... the hardware itself.

Unfortunately the last dump is broken also a full dump should be hundreds of MB large.

So assuming its not the hardware or even if it is... the only way I see we could proceed form here on is to try to find a driver version which does not cause a BSOD and from there try to deduce what is breaking something in the kernel in a way as to cause a crash not pointing to sbiedrv.sys you know som sort of memory corruption or alike....
First I would ask you to try older versions of sandboxie, much older as old as would run on your system, if you can find a build which is fine and point me to the first build which is not that would be mighty helpful!

If all older builds fail and you still want to try to fix the issue on the software side, I can offer to send you a bunch of chopped down, unsigned test drivers. With those we could pinpoint which routines in the driver cause the issue on your system.
Does not mean we will be able to fix it if its hardware related, that's a lot of testing and a lot of BSOD's to test through.

**Comment by reraikes** [comment] 2023-05-31 23:34
>Well but the older backups when they were taken, had Sandboxie installed and worked just fine, correct?
then something changed and now when sandboxie runs you get a bsod.
Now you say if you roll back to one of the previous backups which were perfectly fine with sandboxie, they now experience a BSOD as well, correct?

Yes/correct to all the above.

>So something changed and its not windows and not sandboxie as booth come from the backups, I assume you don't run windows update after restoring the backup, or do you?
If you do then try not to, restore a known good backup with an unplugged network cable and check if sandboxie which was fine is still fine or if it is not.
If it is fine than the culprit is a windows update, and we need to pinpoint this as more users may be affected...
If however its not fine then whats the only thing that could have changed and can not be rolled back... the hardware itself.

It's not Windows update as I always unplug the network cable on the first boot of a restored backup and immediately pause Windows update.  All is well until I reboot with the network cable plugged in, at which point an UNEXPECTED_KERNEL_MODE_TRAP BSoD occurs within seconds of Sandboxie Control being started.  If I then boot into Safe Mode and uninstall Sandboxie, the same system is then 100% stable with no other changes.  Run all the stress tests you like without Sandboxie installed and the system will not NOT crash once Sandboxie has been removed.  Reinstall Sandboxie and the system will crash once exposed to the Internet.

>So assuming its not the hardware or even if it is... the only way I see we could proceed form here on is to try to find a driver version which does not cause a BSOD and from there try to deduce what is breaking something in the kernel in a way as to cause a crash not pointing to sbiedrv.sys you know som sort of memory corruption or alike....
First I would ask you to try older versions of sandboxie, much older as old as would run on your system, if you can find a build which is fine and point me to the first build which is not that would be mighty helpful!

I have tried numerous older versions of Sandboxie, and none of them will run without an UNEXPECTED_KERNEL_MODE_TRAP BSoD if the system is connected to the Internet.  They are all 100% stable if you don't let them access the Internet.

>If all older builds fail and you still want to try to fix the issue on the software side, I can offer to send you a bunch of chopped down, unsigned test drivers. With those we could pinpoint which routines in the driver cause the issue on your system.
Does not mean we will be able to fix it if its hardware related, that's a lot of testing and a lot of BSOD's to test through.

I cannot crash the system if Sandboxie is not installed. Stress tests take all 24 cores to 100% loading and run the core temps to 100 degrees Celsius and nothing complains as long as Sandboxie is not installed, so I can't believe it's a hardware issue.  I'm willing to try whatever you have.

**Comment by reraikes** [comment] 2023-06-07 16:55
>If all older builds fail and you still want to try to fix the issue on the software side, I can offer to send you a bunch of chopped down, unsigned test drivers. With those we could pinpoint which routines in the driver cause the issue on your system.

@DavidXanatos,

Any further thoughts on this approach to identifying the BSOD problem?  I would love to be able to use Sandboxie adain.

**Comment by Xmarmalade** [comment] 2023-10-02 09:17
Similar problems, when I try to open msedge in the sandbox (open files such as pdf/start edge from the start menu), will cause UNEXPECTED_KERNEL_MODE_TRAP 
I have updated to the latest system and SP

**Comment by offhub** [comment] 2023-11-11 17:41
@Xmarmalade What operating system and processor are you using?

**Comment by Xmarmalade** [comment] 2023-11-12 04:32
> @Xmarmalade What operating system and processor are you using?

Windows 11
when I submitted the problem, my system was up to date

**Comment by e-t-l** [comment] 2023-11-12 05:19
@Xmarmalade your issue may be related to mine, which was triggering UNEXPECTED_KERNEL_MODE_TRAP when Edge tried to run. I actually found a fix/workaround for my situation, which appeared to be some residual virtualized setting within the sandbox that wasn't agreeing with the host machine's setting. I solved it, essentially, by emptying the sandbox. Assuming you won't lose too much data, have you tried totally emptying the sandbox (and/or create a new sandbox and copy over the .ini settings)?

**Comment by Xmarmalade** [comment] 2023-11-12 05:43
> @Xmarmalade your issue may be related to mine, which was triggering UNEXPECTED_KERNEL_MODE_TRAP when Edge tried to run. I actually found a fix/workaround for my situation, which appeared to be some residual virtualized setting within the sandbox that wasn't agreeing with the host machine's setting. I solved it, essentially, by emptying the sandbox. Assuming you won't lose too much data, have you tried totally emptying the sandbox (and/or create a new sandbox and copy over the .ini settings)?

Thanks for your reply. According to your suggestions, I have tried the following steps: 

1. Create a new box "New_Box"
2. Copy the original box settings to the new box
```ini
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%Desktop%
RecoverFolder=%Personal%
RecoverFolder=%{ABCDEFGH-5678-1234-1024-IJKLMNOPQRST}%
BorderColor=#ffffaa,off,2
Template=AutoRecoverIgnore
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=FileCopy
Template=SkipHook
Template=OpenBluetooth
Template=Chrome_Cookies_DirectAccess
Template=Chrome_History_DirectAccess
Template=Chrome_Bookmarks_DirectAccess
Template=Chrome_Phishing_DirectAccess
Template=Chrome_Preferences_DirectAccess
ConfigLevel=10
UseFileDeleteV2=y
UseRegDeleteV2=y
AutoRecover=n
OpenPipePath=C:\Users\User\Downloads
ClosedIpcPath=<StartRunAccess>,*
ProcessGroup=<StartRunAccess>,crashpad_handler.exe
```

3. Save the settings and launch ms edge in this box
4. Crashed

**Comment by isaak654** [comment] 2023-11-25 21:38
@Xmarmalade Could you verify if [this fix](https://github.com/sandboxie-plus/Sandboxie/issues/3427#issuecomment-1826382781) works for you too?

**Comment by isaak654** [comment] 2023-11-25 21:40
@Xmarmalade Could you verify if [this fix](https://github.com/sandboxie-plus/Sandboxie/issues/3427#issuecomment-1826382781) works for you?

**Comment by Xmarmalade** [comment] 2023-11-26 12:37
> @Xmarmalade Could you verify if [this fix](https://github.com/sandboxie-plus/Sandboxie/issues/3427#issuecomment-1826382781) works for you?

Yes, after modifying the configuration file, the issue has been alleviated.

**Comment by isaak654** [comment] 2023-11-26 19:13
> the issue has been alleviated.

@Xmarmalade Could you be more specific? What's left?

**Comment by reraikes** [comment] 2023-11-27 00:19
> What's left?

https://github.com/sandboxie-plus/Sandboxie/issues/3427#issuecomment-1826382781 appears to fix the BSOD's, but leaves all the msedge.exe instances running after Edge is closed: https://github.com/sandboxie-plus/Sandboxie/issues/3427#issuecomment-1826411900

**Comment by Xmarmalade** [comment] 2023-11-27 01:21
@isaak654 @reraikes For me, this problem seems to have been solved. ms-edge will not cause BSOD and will not remain after closing. But I'm not sure why ms-edge can't be closed according to https://github.com/sandboxie-plus/Sandboxie/issues/3427#issuecomment-1826411900, did you enable StartupBoost or something?

**Comment by isaak654** [comment] 2023-11-28 14:31
I think it would be more appropriate to open a new issue for the msedge.exe instances that do not terminate, possibly indicating which sandboxed extensions in the browser are enabled, as one of them could be responsible.

Given that the system crashes in question are no longer present, this issue has served its purpose.

**Closed by isaak654** 2023-11-28 14:31 UTC
Labels: help wanted, Confirmation pending, more info needed, Partially fixed, BSOD
