### ISSUE TITLE
When the main window is closed, clicking OK/Apply/X buttons on other windows will close the SandMan.exe

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#388] opened 2021-01-16 18:25 UTC
1. Open the main window.
2. Open the global settings window.
3. Close the main window.
4. Click OK/Apply/X button.
5. SandMan.exe exits.

**Comment by typpos** [comment] 2021-01-16 19:56
Duplicate of #349

**Comment by DavidXanatos** [comment] 2021-01-16 21:48
will be fixed in next build

**Closed by DavidXanatos** 2021-01-16 21:48 UTC
